{
  "hash": "deb1a27b0057c32828e9bf5596d2ebe8",
  "result": {
    "engine": "jupyter",
    "markdown": "# Datos macroeconómicos {#sec-datos}\n\n::: {.pregunta}\n¿Qué mide en realidad la serie que estamos a punto de modelar, y qué le hicimos antes de verla?\n:::\n\n::: {.aprendizajes}\n1. Reconocer las formas que toma una serie macroeconómica (frecuencia, tendencia, ciclo, estacionalidad, quiebres) y resumirlas en unos pocos hechos estilizados.\n2. Descomponer una serie en tendencia, ciclo, estacionalidad e irregular, y saber qué parte de esa separación es un supuesto.\n3. Entender qué hace un ajuste estacional, cómo leer una serie desestacionalizada y por qué la variación interanual no la reemplaza.\n4. Elegir la transformación con un criterio, y explicar por qué los economistas trabajan casi siempre en logaritmos.\n:::\n\n**Requisitos previos.** Nociones de series de tiempo; `pandas`, fechas y gráficos (secciones [0.7](00-preliminares.qmd#sec-prelim-pandas) y [0.8](00-preliminares.qmd#sec-prelim-graficos)).\n\n::: {.datos-usados}\n| Serie | Fuente | Frecuencia | Código |\n|:-------------------------------|:--------|:-----------|:--------------|\n| Tipo de cambio, dólares por euro | FRED | diaria | `DEXUSEU` |\n| Inicios de construcción de viviendas (sin desestacionalizar) | FRED | mensual | `HOUSTNSA` |\n| Tasa efectiva de fondos federales | FRED | mensual | `FEDFUNDS` |\n| PBI real de EE.UU. (sin desestacionalizar) | FRED | trimestral | `ND000334Q` |\n| PBI real del Perú (sin desestacionalizar) | BCRP | trimestral | `PN02538AQ` |\n\nLos ejercicios usan además dos series mensuales del BCRP: el PBI desestacionalizado (`PN01773AM`) y el IPC de Lima (`PN38705PM`). Los archivos crudos están en `data/raw/` y los CSV que leen los capítulos los construyen `code/python/build_us_data.py` y `code/python/build_peru_data.py`.\n:::\n\n## Cómo se ve una serie macroeconómica {#sec-datos-hechos}\n\nAntes de modelar una serie conviene mirarla. La @fig-datos-formas reúne cuatro series de Estados Unidos elegidas porque no se parecen entre sí: cada una muestra una forma distinta en que llega un dato macroeconómico, y buena parte de lo que el libro hace después es una respuesta a alguna de ellas.\n\n::: {#datos-setup .cell execution_count=1}\n``` {.python .cell-code}\nimport numpy as np\nimport pandas as pd\n\nfrom macrobook import data_path\n\n\ndef read(name, freq):\n    table = pd.read_csv(data_path(name), index_col=\"date\")\n    table.index = pd.PeriodIndex(table.index, freq=freq)\n    return table\n\n\ndaily = read(\"us_daily.csv\", \"D\")\nmonthly = read(\"us_monthly.csv\", \"M\")[\"2000\":]\n\nfx = daily[\"usd_eur\"][\"2000\":].dropna()   # sin feriados\nhousing = monthly[\"housing_nsa\"]\nfed_funds = monthly[\"fed_funds\"]\ngdp_us = read(\"us_quarterly.csv\", \"Q\")[\"gdp_nsa\"]\ngdp_pe = read(\"peru_quarterly.csv\", \"Q\")[\"gdp_nsa\"]\n\nsamples = {\"dólar/euro\": fx, \"viviendas\": housing,\n           \"fondos\": fed_funds, \"PBI EE.UU.\": gdp_us,\n           \"PBI Perú\": gdp_pe}\nfor name, series in samples.items():\n    print(f\"{name:11} {series.index[0]} a {series.index[-1]}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ndólar/euro  2000-01-03 a 2026-09-11\nviviendas   2000-01 a 2026-08\nfondos      2000-01 a 2026-08\nPBI EE.UU.  2002Q1 a 2026Q2\nPBI Perú    1996Q1 a 2026Q2\n```\n:::\n:::\n\n\n::: {.cell execution_count=2}\n``` {.python .cell-code}\nimport matplotlib.pyplot as plt\n\nfrom macrobook import use_style, figsize, PALETTE, charts\n\nuse_style()\n\npanels = [(fx, \"dólares por euro, diario\"),\n          (housing, \"inicios de viviendas (miles), mensual\"),\n          (fed_funds, \"fondos federales (%), mensual\"),\n          (gdp_us, \"PBI real (miles de millones), trimestral\")]\n\nfig, axes = plt.subplots(2, 2, sharex=True,\n                         figsize=figsize(0.62))\nfor ax, (series, title) in zip(axes.ravel(), panels):\n    dates = series.index.to_timestamp(how=\"end\")\n    ax.plot(dates, series, color=PALETTE[\"ink\"], lw=0.8)\n    charts.year_ticks(ax, every=10)\n    ax.set_title(title, fontsize=8.5)\naxes[1, 1].yaxis.set_major_formatter(charts.thousands)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Cuatro series de Estados Unidos desde 2000. El tipo de cambio es diario y no tiene tendencia; los inicios de viviendas, mensuales y sin desestacionalizar, combinan un patrón que se repite cada año con un ciclo largo; la tasa de fondos federales se mueve por escalones y pasa años en su piso; el PBI real trimestral, también sin desestacionalizar, suma tendencia, estacionalidad y la caída de 2020.](01-macro-data_files/figure-pdf/fig-datos-formas-output-1.pdf){#fig-datos-formas fig-pos='H'}\n:::\n:::\n\n\nLas cuatro difieren en casi todo. Difieren en la **frecuencia**: los precios de mercado se observan todos los días, los indicadores de actividad cada mes y las cuentas nacionales cada trimestre, con semanas de rezago. Difieren en la **tendencia**: el PBI crece de manera sostenida, mientras que el tipo de cambio y la tasa de interés deambulan sin una dirección definida. Y difieren en lo que pasa en el **corto plazo**: los inicios de viviendas y el PBI sin ajustar suben y bajan con el calendario; la tasa de fondos federales es una variable de política que cambia por decisiones discretas; el tipo de cambio es un precio financiero que se mueve todos los días.\n\n### Hechos estilizados\n\n::: {#tbl-datos-hechos .cell tbl-cap='Rasgos de las cuatro series. El cambio es la diferencia logarítmica en por ciento (en puntos de tasa para los fondos federales). La columna estacional es la parte de la varianza del cambio que explican las medias por mes, o por trimestre en el PBI.' execution_count=3}\n``` {.python .cell-code}\ndef traits(level, change, season):\n    calendar = change.groupby(season).transform(\"mean\")\n    explained = 1 - ((change - calendar) ** 2).sum() / (\n        (change - change.mean()) ** 2).sum()\n    return {\"obs.\": len(level),\n            \"autocorr. nivel\": level.autocorr(1),\n            \"autocorr. cambio\": change.autocorr(1),\n            \"% estacional\": 100 * explained}\n\n\nd_fx = 100 * np.log(fx).diff().dropna()\nd_housing = 100 * np.log(housing).diff().dropna()\nd_rate = fed_funds.diff().dropna()\nd_gdp = 100 * np.log(gdp_us).diff().dropna()\n\ntable = pd.DataFrame({\n    \"dólar/euro\": traits(fx, d_fx, d_fx.index.month),\n    \"viviendas\": traits(housing, d_housing,\n                        d_housing.index.month),\n    \"fondos federales\": traits(fed_funds, d_rate,\n                               d_rate.index.month),\n    \"PBI\": traits(gdp_us, d_gdp, d_gdp.index.quarter)}).T\ntable = table.round({\"autocorr. nivel\": 2,\n                     \"autocorr. cambio\": 2, \"% estacional\": 0})\ntable.astype({\"obs.\": int, \"% estacional\": int})\n```\n\n::: {.cell-output .cell-output-display execution_count=3}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>obs.</th>\n      <th>autocorr. nivel</th>\n      <th>autocorr. cambio</th>\n      <th>% estacional</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>dólar/euro</th>\n      <td>6693</td>\n      <td>1.00</td>\n      <td>0.01</td>\n      <td>0</td>\n    </tr>\n    <tr>\n      <th>viviendas</th>\n      <td>320</td>\n      <td>0.95</td>\n      <td>0.02</td>\n      <td>39</td>\n    </tr>\n    <tr>\n      <th>fondos federales</th>\n      <td>320</td>\n      <td>1.00</td>\n      <td>0.71</td>\n      <td>2</td>\n    </tr>\n    <tr>\n      <th>PBI</th>\n      <td>98</td>\n      <td>0.98</td>\n      <td>-0.41</td>\n      <td>79</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#hechos-numeros .cell execution_count=4}\n``` {.python .cell-code}\nvol = d_fx.groupby(d_fx.index.year).std() * np.sqrt(252)\nfloor = (fed_funds <= 0.25).sum()\nstarts = housing.groupby(housing.index.year).sum()\nprint(f\"volatilidad mínima: {vol.min():.1f} % en {vol.idxmin()}\")\nprint(f\"volatilidad máxima: {vol.max():.1f} % en {vol.idxmax()}\")\nprint(f\"meses con la tasa en 0.25 % o menos: {floor} \"\n      f\"de {len(fed_funds)}\")\nprint(f\"inicios de viviendas, 2009 contra 2005: \"\n      f\"{100 * (starts[2009] / starts[2005] - 1):.0f} %\")\nprint(\"PBI sin ajustar, cambio medio por trimestre (%):\",\n      d_gdp.groupby(d_gdp.index.quarter).mean().round(1)\n      .to_dict())\nprint(\"mayor cambio trimestral del PBI:\", d_gdp.abs().idxmax())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nvolatilidad mínima: 4.7 % en 2019\nvolatilidad máxima: 14.2 % en 2008\nmeses con la tasa en 0.25 % o menos: 109 de 320\ninicios de viviendas, 2009 contra 2005: -73 %\nPBI sin ajustar, cambio medio por trimestre (%): {1: -3.6, 2: 2.5, 3: 1.3, 4: 2.0}\nmayor cambio trimestral del PBI: 2020Q3\n```\n:::\n:::\n\n\nEl @tbl-datos-hechos resume cuatro hechos que reaparecen en todo el libro.\n\n**Los niveles son muy persistentes; los cambios, mucho menos.** La autocorrelación del nivel está entre 0.95 y 1 en las cuatro series. La de los cambios es nula en el tipo de cambio; es 0.71 en la tasa de fondos federales, que la Reserva Federal mueve de a poco y en la misma dirección; y es negativa en el PBI sin ajustar, donde a una caída estacional le sigue una subida. Por eso el @sec-univariado discute raíces unitarias y casi todos los modelos se estiman sobre cambios.\n\n**Sin ajustar, el calendario domina el corto plazo.** Las medias por trimestre explican 79 % de la varianza de la variación del PBI, y las medias por mes, 39 % de la de los inicios de viviendas. Un primer trimestre típico cae 3.6 % sin que la economía se contraiga.\n\n**La volatilidad cambia en el tiempo.** La del tipo de cambio va de 4.7 % anual en 2019 a 14.2 % en 2008, y un modelo con varianza constante describe mal ambos años (@sec-volatilidad).\n\n**Hay pisos y quiebres.** La tasa de fondos federales pasó 109 de los 320 meses desde 2000 en 0.25 % o menos, un piso que ningún modelo lineal respeta; los inicios de viviendas cayeron 73 % entre 2005 y 2009; y la pandemia produjo el mayor cambio trimestral del PBI en la muestra (@sec-datos-otros).\n\n## La descomposición de una serie {#sec-datos-descomposicion}\n\nLa @fig-datos-formas invita a mirar cada serie como la suma de piezas con interpretación distinta: una tendencia, un ciclo, un patrón que se repite cada año y un ruido. Esa es la tradición que arranca con @burns1946.\n\n::: {#def-descomposicion}\n## Descomposición por componentes no observados\n\nEn logaritmos, una serie se escribe como\n\n$$ \\ln y_t = \\tau_t + c_t + s_t + \\eta_t , $$ {#eq-descomposicion}\n\ndonde $\\tau_t$ es la tendencia, $c_t$ el ciclo, $s_t$ el componente estacional y $\\eta_t$ el irregular. En niveles, la misma relación es multiplicativa: $y_t = T_t \\cdot C_t \\cdot S_t \\cdot I_t$.\n:::\n\nTrabajar en logaritmos convierte la descomposición multiplicativa en aditiva, y esa es la primera razón práctica por la que los economistas usan logaritmos: la amplitud de la estacionalidad de una serie que crece suele ser proporcional al nivel, no fija en unidades.\n\n::: {.cuidado}\nLa @eq-descomposicion no se puede estimar sin supuestos adicionales: cuatro componentes no observados y una sola serie observada. Todo método de descomposición añade restricciones, casi siempre sobre las frecuencias que ocupa cada componente o sobre la forma de su dinámica. Dos métodos razonables dan resultados distintos, y ninguno es \"el\" verdadero. Lo que se puede exigir es que el supuesto sea explícito y que el resultado se reporte junto con él.\n:::\n\nLa separación no es igual de difícil en todos los componentes. La estacionalidad ocupa frecuencias conocidas, se repite y es la parte mejor identificada del problema; separar tendencia de ciclo, en cambio, es una decisión casi puramente teórica, con una literatura entera en desacuerdo: el filtro de @hodrick1997, la crítica de @hamilton2018, la descomposición de @beveridge1981 y los modelos de componentes no observados de @harvey1989 producen ciclos distintos con los mismos datos. El @sec-tendencias trata ese problema. Este capítulo se ocupa del componente estacional, donde el acuerdo es mucho mayor.\n\nVale la pena ver el problema con una serie inventada, donde sí conocemos la respuesta.\n\n::: {.cell execution_count=5}\n``` {.python .cell-code}\nrng = np.random.default_rng(7)\nT = 240\nindex = pd.period_range(\"2006-01\", periods=T, freq=\"M\")\n\ntrend = np.log(100) + 0.0025 * np.arange(T)\ncycle = np.zeros(T)\nfor t in range(2, T):\n    cycle[t] = (1.5 * cycle[t - 1] - 0.6 * cycle[t - 2]\n                + rng.normal(0, 0.004))\npattern = np.array([-1.2, -1.8, 2.8, 0.6, 0.2, -0.4,\n                    0.9, 0.4, -0.3, 0.1, -0.8, -0.5]) / 100\npattern = pattern - pattern.mean()\nseason = pattern[np.arange(T) % 12]\nirregular = rng.normal(0, 0.004, T)\n\nlog_y = trend + cycle + season + irregular\ny_sim = pd.Series(np.exp(log_y), index=index.to_timestamp())\n\nsize = figsize(0.52)\nfig, axes = plt.subplots(2, 2, sharex=True, figsize=size)\npieces = [(log_y, \"serie (en logaritmos)\"),\n          (trend + cycle, \"tendencia y ciclo\"),\n          (season, \"estacional\"),\n          (irregular, \"irregular\")]\nfor ax, (values, title) in zip(axes.ravel(), pieces):\n    ax.plot(y_sim.index, values, color=PALETTE[\"ink\"], lw=0.9)\n    ax.set_title(title, fontsize=8.5)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Una serie simulada y sus cuatro componentes. La tendencia y el ciclo son suaves; la estacionalidad se repite; el irregular no tiene estructura.](01-macro-data_files/figure-pdf/fig-datos-simulacion-output-1.pdf){#fig-datos-simulacion fig-pos='H'}\n:::\n:::\n\n\n## Ajuste estacional {#sec-datos-desestacionalizar}\n\nLa estacionalidad es un fenómeno económico real: en diciembre se produce y se compra más, en marzo empiezan las clases, la pesca depende de las vedas. No es un error de medición. El problema es que domina la variación de corto plazo, como mostró el @tbl-datos-hechos, y esconde justamente lo que interesa: si la economía se está acelerando o desacelerando ahora. Ajustar por estacionalidad es estimar ese componente y restarlo de la serie.\n\n::: {.cell execution_count=6}\n``` {.python .cell-code}\nfrom MacroPy import seasonal_adjust\n\nadjusted = seasonal_adjust(gdp_pe, method=\"x13\", outlier=True)\ngdp_pe_sa = pd.Series(adjusted.seasadj.values,\n                      index=gdp_pe.index)\n\nfig, axes = plt.subplots(1, 2, figsize=figsize(0.40),\n                         gridspec_kw={\"width_ratios\": [1.5, 1]})\nwindows = [slice(None), slice(\"2017\", \"2023\")]\nfor ax, window in zip(axes, windows):\n    dates = gdp_pe[window].index.to_timestamp(how=\"end\")\n    ax.plot(dates, gdp_pe[window] / 1000, lw=0.9,\n            color=PALETTE[\"muted\"], label=\"sin ajustar\")\n    ax.plot(dates, gdp_pe_sa[window] / 1000, lw=1.3,\n            color=PALETTE[\"accent\"], label=\"desestacionalizado\")\ncharts.year_ticks(axes[0], every=10)\ncharts.year_ticks(axes[1], every=2)\ncharts.legend_outside(axes[0], ncol=2)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![PBI real del Perú, sin ajustar y desestacionalizado con X-13, en miles de millones de soles de 2007. A la izquierda, toda la muestra; a la derecha, el detalle de 2017 a 2023. La serie sin ajustar sube y baja cada año con el calendario; la desestacionalizada deja ver la tendencia, el ciclo y la pandemia.](01-macro-data_files/figure-pdf/fig-datos-peru-output-1.pdf){#fig-datos-peru fig-pos='H'}\n:::\n:::\n\n\n::: {#factores .cell execution_count=7}\n``` {.python .cell-code}\nfactor = 100 * np.log(gdp_pe / gdp_pe_sa)\nfirst = factor[factor.index.quarter == 1]\nprint(\"factor medio por trimestre (%):\",\n      factor.groupby(factor.index.quarter).mean().round(1)\n      .to_dict())\nprint(f\"primer trimestre: {first.iloc[0]:.1f} % en \"\n      f\"{first.index[0].year}, {first.iloc[-1]:.1f} % en \"\n      f\"{first.index[-1].year}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nfactor medio por trimestre (%): {1: -4.8, 2: 2.1, 3: -0.2, 4: 2.8}\nprimer trimestre: -3.8 % en 1996, -5.9 % en 2026\n```\n:::\n:::\n\n\nEl factor estacional estimado es grande: en promedio, el primer trimestre está 4.8 % por debajo de lo que dicta la tendencia y el cuarto, 2.8 % por encima. Y no es fijo: el factor del primer trimestre pasa de $-3.8$ % en 1996 a $-5.9$ % en 2026, a medida que cambia la estructura productiva. Por eso ajustar no es restar la media de cada trimestre, que es lo que haría una regresión con variables dummy estacionales.\n\n### Cómo funciona\n\nLos programas que usan las oficinas de estadística siguen la misma receta de dos pasos.\n\n**Primero, limpiar.** Antes de buscar el patrón estacional se quitan los efectos que lo contaminarían: el número de días hábiles, Semana Santa, que cae en marzo o en abril, los feriados y los valores atípicos, como el segundo trimestre de 2020. Se hace con una regresión con errores ARIMA estacionales, llamada regARIMA:\n\n$$ \\ln y_t = \\beta' x_t + z_t, \\qquad \\phi(L)\\Phi(L^{s})(1-L)^d(1-L^{s})^D z_t = \\theta(L)\\Theta(L^{s}) a_t , $$ {#eq-regarima}\n\ndonde $x_t$ reúne esos regresores y $s$ es el número de periodos por año. El mismo modelo pronostica la serie hacia adelante, para que los promedios del segundo paso no se queden sin datos al final de la muestra, que es justamente el tramo que más interesa.\n\n**Segundo, separar.** Con la serie limpia se estima el componente estacional, de una de dos maneras. Con *filtros* (X-11): se quita la tendencia con un promedio móvil, y el factor de cada trimestre se estima promediando ese mismo trimestre en los años vecinos, de modo que puede cambiar lentamente. Con un *modelo* (SEATS): a partir del ARIMA estimado se deduce qué parte de la dinámica es estacional, y se extrae con el filtro que minimiza el error cuadrático medio.\n\n::: {.intuicion}\nEl factor del primer trimestre según X-11 es, en esencia, un promedio de los primeros trimestres de los años cercanos, medidos contra la tendencia. SEATS llega a algo parecido por otro camino: en lugar de fijar los promedios de antemano, los deduce del modelo, y por eso puede decir además cuán incierto es el componente estimado.\n:::\n\nLas dos implementaciones estándar son X-13ARIMA-SEATS, de la Oficina del Censo de Estados Unidos [@findley1998], y TRAMO-SEATS, del Banco de España [@gomez1996]. Ambas hacen los dos pasos y la diferencia es de origen: X-13 desciende del X-11 de los años sesenta [@dagum1980] e incorporó después SEATS, mientras que TRAMO-SEATS nació del lado de los modelos y da más libertad para definir el calendario de cada país. Las directrices europeas [@ess2024] aceptan las dos familias, y la plataforma JDemetra+ las implementa juntas. `seasonal_adjust` de `MacroPy` ejecuta X-13 con los filtros X-11.\n\nQue la separación estacional esté bien identificada se puede comprobar con la serie simulada de la @fig-datos-simulacion, donde el patrón verdadero es conocido.\n\n::: {#x13-simulacion .cell execution_count=8}\n``` {.python .cell-code}\ncheck = seasonal_adjust(y_sim, method=\"x13\", outlier=True)\nfound = 100 * np.log(y_sim / check.seasadj)\nby_month = found.groupby(found.index.month).mean().values\nerror = np.abs(by_month - 100 * pattern).mean()\ncorr = np.corrcoef(by_month, pattern)[0, 1]\nprint(f\"error medio: {error:.2f} puntos; \"\n      f\"correlación: {corr:.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nerror medio: 0.10 puntos; correlación: 0.995\n```\n:::\n:::\n\n\nX-13 recupera el patrón con un error medio de una décima de punto porcentual y una correlación de 0.995 con el verdadero.\n\n### La variación interanual no es un ajuste\n\nLa alternativa gratuita es comparar contra el mismo trimestre del año anterior. Elimina la estacionalidad, pero promedia cuatro trimestres, de modo que llega tarde a los quiebres, y arrastra lo que pasó hace un año: el llamado **efecto base**.\n\n::: {#efecto-base .cell execution_count=9}\n``` {.python .cell-code}\nyoy = 100 * (gdp_pe / gdp_pe.shift(4) - 1)\nqoq_sa = 100 * (gdp_pe_sa / gdp_pe_sa.shift(1) - 1)\ntwo_years = 100 * (gdp_pe_sa / gdp_pe_sa.shift(8) - 1)\nprint(f\"2021T2: interanual {yoy['2021Q2']:.1f} %, \"\n      f\"log {100 * np.log1p(yoy['2021Q2'] / 100):.1f}\")\nprint(f\"2021T2 ajustado: {qoq_sa['2021Q2']:.1f} % contra \"\n      f\"2021T1, {two_years['2021Q2']:.1f} % contra 2019T2\")\n\nadj_us = seasonal_adjust(gdp_us, method=\"x13\", outlier=True)\nsa_us = pd.Series(adj_us.seasadj.values, index=gdp_us.index)\nq_us = pd.DataFrame({\"sin ajustar\": 100 * gdp_us.pct_change(),\n                     \"ajustado\": 100 * sa_us.pct_change()})\nprint(q_us.loc[\"2020Q1\":\"2020Q2\"].round(1))\nprint(\"mayor caída ajustada:\", q_us[\"ajustado\"].idxmin())\nprint(\"Perú ajustado, 2020T2 y 2020T3 (%):\",\n      qoq_sa[\"2020Q2\":\"2020Q3\"].round(1).tolist())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n2021T2: interanual 42.1 %, log 35.1\n2021T2 ajustado: 0.5 % contra 2021T1, -0.1 % contra 2019T2\n        sin ajustar  ajustado\ndate                         \n2020Q1         -5.5      -1.1\n2020Q2         -5.4      -7.7\nmayor caída ajustada: 2020Q2\nPerú ajustado, 2020T2 y 2020T3 (%): [-26.5, 30.3]\n```\n:::\n:::\n\n\nEn el segundo trimestre de 2021 el PBI peruano creció 42.1 % interanual, una cifra histórica. La serie desestacionalizada de la @fig-datos-peru cuenta otra cosa: el nivel era prácticamente el de dos años antes ($-0.1$ %) y había crecido 0.5 % respecto del trimestre anterior. La interanual comparaba contra el peor trimestre del confinamiento y hablaba, sobre todo, del pasado.\n\nEl error opuesto es mirar la variación trimestral sin ajustar. El PBI de Estados Unidos sin ajustar cae 5.5 % en el primer trimestre de 2020 y 5.4 % en el segundo; ajustado, cae 1.1 y 7.7 %. Sin ajustar, los dos trimestres parecen igual de malos; ajustado, uno es una desaceleración y el otro la caída más grande de la muestra.\n\n::: {.cuidado}\nUsar la variación interanual como si fuera una desestacionalización es un error frecuente. La diferencia de un año elimina el patrón estacional, pero introduce una media móvil que crea autocorrelación artificial, desplaza los puntos de quiebre y arrastra los efectos base. Para describir la coyuntura, la serie desestacionalizada; para comparar con el año anterior, la interanual, sabiendo lo que mide.\n:::\n\n**Otros métodos.** Las variables dummy estacionales son la opción más simple y la peor: imponen el mismo factor todos los años, y el primer trimestre peruano muestra que no lo es. STL [@cleveland1990] estima el patrón con regresiones locales, es robusto a atípicos y está en `statsmodels` (`method=\"stl\"` en `MacroPy`), pero no trata el calendario. Los modelos de componentes no observados estiman la estacionalidad junto con la tendencia y el ciclo con el filtro de Kalman [@harvey1989]; es la opción natural cuando el ajuste es parte del modelo y no un paso previo, y es lo que hace el @sec-estado.\n\n## Transformaciones {#sec-datos-transformaciones}\n\nElegir la transformación es elegir qué pregunta se puede responder después. Las opciones usuales son pocas.\n\n| Transformación | Fórmula | Qué preserva |\n|:---------------|:--------|:-------------|\n| Nivel | $y_t$ | todo, incluida la tendencia |\n| Logaritmo | $\\ln y_t$ | la tendencia, en escala proporcional |\n| Diferencia logarítmica | $\\Delta \\ln y_t$ | la dinámica de corto plazo |\n| Tasa interanual | $y_t/y_{t-s} - 1$ | el movimiento de baja frecuencia |\n| Diferencia de orden $s$ | $\\Delta_s \\ln y_t$ | la dinámica sin estacionalidad |\n\n: Transformaciones habituales y qué conserva cada una {#tbl-transformaciones}\n\nLa primera decisión, niveles frente a diferencias, se discute en el @sec-var-otros: la respuesta depende de si interesan las relaciones de largo plazo y de si las series comparten tendencias estocásticas [@nelson1982]. La segunda, que es la de esta sección, es si trabajar con la variable o con su logaritmo.\n\n### Por qué logaritmos\n\nHay cuatro razones.\n\n**Linealiza el crecimiento.** Una serie que crece a tasa constante es una recta en logaritmos, y un cambio de tendencia se ve en esa escala y se esconde en la de niveles.\n\n**Su diferencia es casi la tasa de crecimiento.** Con $g_t = \\Delta y_t / y_{t-1}$, basta sumar y restar uno dentro del logaritmo:\n\n$$\n\\begin{aligned}\n\\Delta \\ln y_t &= \\ln y_t - \\ln y_{t-1} = \\ln \\frac{y_t}{y_{t-1}} \\\\\n&= \\ln\\left(1 + \\frac{y_t}{y_{t-1}} - \\frac{y_{t-1}}{y_{t-1}}\\right) \\\\\n&= \\ln\\left(1 + \\frac{y_t - y_{t-1}}{y_{t-1}}\\right) = \\ln(1 + g_t) \\\\\n&= g_t - \\frac{g_t^2}{2} + \\frac{g_t^3}{3} - \\cdots \\approx g_t .\n\\end{aligned}\n$$ {#eq-aproximacion}\n\nLa última igualdad es la expansión de Taylor de $\\ln(1+g)$ alrededor de cero: si $g$ es pequeña, los términos de orden dos en adelante son despreciables. Si $y$ pasa de 100 a 105, la tasa es 0.05 y $\\ln 1.05 = 0.0488$; si pasa de 100 a 140, la tasa es 0.40 y $\\ln 1.40 = 0.3365$. El 42.1 % interanual del PBI peruano de 2021 es 35.1 en diferencia logarítmica: con tasas así hay que decir cuál se reporta.\n\n::: {.cell execution_count=10}\n``` {.python .cell-code}\ngrid = np.linspace(-0.45, 0.9, 300)\n\nfig, ax = plt.subplots(figsize=figsize(0.55))\nax.plot(grid, grid, color=PALETTE[\"muted\"], lw=1.0,\n        ls=(0, (4, 2)), label=\"$g$ (45 grados, orden 1)\")\nax.plot(grid, grid - grid**2 / 2, color=PALETTE[\"steel\"],\n        lw=1.0, ls=(0, (1, 1.5)), label=\"$g - g^2/2$ (orden 2)\")\nax.plot(grid, np.log1p(grid), color=PALETTE[\"ink\"], lw=1.4,\n        label=\"$\\\\ln(1+g)$\")\nfor g, text in [(0.05, \"105/100\"), (0.40, \"140/100\")]:\n    ax.plot([g, g], [np.log1p(g), g], color=PALETTE[\"accent\"],\n            lw=1.2, marker=\"o\", ms=3)\n    ax.annotate(text, (g, np.log1p(g)), xytext=(6, -12),\n                textcoords=\"offset points\", fontsize=8,\n                color=PALETTE[\"accent\"])\ncharts.zero_line(ax)\nax.axvline(0, color=PALETTE[\"ink\"], lw=0.7, zorder=1)\nax.set_xlabel(\"tasa de crecimiento $g$\")\nax.set_ylabel(\"diferencia logarítmica\")\ncharts.legend_outside(ax, ncol=3)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![La diferencia logarítmica $\\ln(1+g)$ frente a la tasa de crecimiento $g$. Cerca de cero coinciden con la recta de 45 grados, que es la aproximación de Taylor de primer orden; a medida que $g$ se aleja de cero se separan, y la aproximación de segundo orden, $g - g^2/2$, cierra buena parte de la brecha. Los segmentos marcan los dos ejemplos del texto: de 100 a 105 y de 100 a 140.](01-macro-data_files/figure-pdf/fig-datos-aprox-output-1.pdf){#fig-datos-aprox fig-pos='H'}\n:::\n:::\n\n\nLa curva queda bajo la recta a ambos lados de cero: el logaritmo subestima las subidas y exagera las caídas. Por eso una caída de 50 % seguida de una subida de 100 % suma cero en logaritmos, igual que en niveles, mientras que las tasas sumarían 50 %.\n\n**Se suma.** El crecimiento logarítmico de un año es la suma de los cuatro trimestrales, y anualizar es multiplicar por cuatro; con tasas ordinarias hay que multiplicar factores.\n\n**Suele estabilizar la varianza.** Si la amplitud de las fluctuaciones crece con el nivel, los cambios en logaritmos tienen varianza aproximadamente constante (el caso $\\lambda = 0$ de la familia de @boxcox1964), y una estacionalidad multiplicativa se vuelve aditiva.\n\n::: {#varianza .cell execution_count=11}\n``` {.python .cell-code}\ndef sd_growth(level, first, second):\n    out = {}\n    for scale, change in [(\"niveles\", level.diff()),\n                          (\"logaritmos\", np.log(level).diff())]:\n        change = change.drop(change[\"2020\":\"2021\"].index)\n        ratio = change[second:].std() / change[:first].std()\n        out[scale] = round(100 * (ratio - 1))\n    return out\n\n\nprint(\"Perú, 2011-2026 contra 1996-2010 (%):\",\n      sd_growth(gdp_pe, \"2010\", \"2011\"))\nprint(\"EE.UU., 2014-2026 contra 2002-2013 (%):\",\n      sd_growth(gdp_us, \"2013\", \"2014\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nPerú, 2011-2026 contra 1996-2010 (%): {'niveles': 98, 'logaritmos': 2}\nEE.UU., 2014-2026 contra 2002-2013 (%): {'niveles': 49, 'logaritmos': 16}\n```\n:::\n:::\n\n\nEn el PBI peruano sin ajustar, y dejando fuera 2020 y 2021, la desviación estándar de la variación trimestral es 98 % mayor en 2011-2026 que en 1996-2010 medida en soles, y sólo 2 % mayor medida en logaritmos. Pero es una hipótesis que se contrasta serie por serie, no una propiedad del logaritmo: en el PBI de Estados Unidos la misma comparación da 49 y 16 %.\n\nUna advertencia para pronosticar: la exponencial de la media de un logaritmo es la mediana del nivel, no su media, y la diferencia importa cuando la varianza es grande [@lutkepohl2012].\n\n::: {.cuidado}\nEl logaritmo exige variables positivas, y eso descarta más series de las que parece: saldos fiscales, cuenta corriente, brechas y cualquier tasa que pueda ser negativa. Forzar un logaritmo sumando una constante arbitraria cambia la interpretación de los coeficientes y no resuelve nada.\n:::\n\n### Qué transformación usa cada quien\n\nConviene mirar qué hacen los artículos que el libro replica, porque la elección no es arbitraria.\n\n| Artículo | Variables | Transformación |\n|:---------|:----------|:---------------|\n| @sims1980 | producto, precios, dinero, tasas | logaritmos en niveles |\n| @blanchard1989 | PBI, desempleo | tasa de crecimiento, desempleo sin tendencia |\n| @stock2001 | inflación, desempleo, tasa | $400\\,\\Delta \\ln P_t$; tasas en niveles |\n| @uhlig2005 | PBI, deflactor, reservas, tasa | $100 \\ln$ en niveles; tasa en nivel |\n| @banbura2010 | 131 series | logaritmos en niveles, con prior de Minnesota |\n\n: Transformaciones en los artículos que el libro replica {#tbl-papers}\n\nEl patrón es claro. Cuando el objetivo es estructural, es decir estimar respuestas a choques, la práctica dominante es trabajar en logaritmos de los niveles y dejar que los rezagos capturen la persistencia, tal como argumentan @simsstockwatson1990. Cuando el objetivo es pronosticar y las series tienen raíces cercanas a uno, se diferencia, o se encoge hacia una caminata aleatoria con el prior del @sec-bvar, que es una forma más suave de hacer lo mismo. Las tasas de interés y de desempleo se dejan en niveles siempre, porque ya están acotadas y su logaritmo no tiene interpretación útil.\n\n::: {.intuicion}\nLa regla operativa cabe en tres líneas. Si la variable es un índice o un valor que crece de forma multiplicativa, logaritmo. Si es una tasa o un porcentaje, nivel. Si el modelo va a leerse como elasticidades o como respuestas porcentuales a un choque, logaritmo otra vez, porque es lo que hace que los coeficientes tengan esa lectura.\n:::\n\n## De dónde vienen los datos {#sec-datos-medicion}\n\nNingún dato macroeconómico se observa directamente. El PBI no se mide: se estima, combinando censos, encuestas, registros administrativos y supuestos de imputación, y se publica como un índice encadenado cuya unidad depende del año base. La inflación no es el cambio de \"los precios\" sino el de una canasta fija durante un tiempo, con sustituciones y ajustes de calidad que son decisiones metodológicas. Entre el concepto del modelo y la serie que entra al código hay una cadena de convenciones, y tres de sus consecuencias atraviesan el libro.\n\nLa primera es que **el nivel casi nunca es comparable y la tasa casi siempre sí**. Un índice con base 2007 = 100 no dice nada por sí solo; su tasa de crecimiento se compara entre países y épocas.\n\nLa segunda es que **los datos se revisan**. La primera estimación del PBI de un trimestre se publica con semanas de retraso y se corrige durante años, de modo que un pronóstico evaluado con los datos de hoy usa información que su autor no tenía [@croushore2001].\n\nLa tercera es que **una serie puede ser en parte construida**. En Estados Unidos las cuentas nacionales son trimestrales y el PBI mensual no existe como estadística oficial; las series mensuales de PBI que usan muchos VAR, como la de @uhlig2005, interpolan el dato trimestral con indicadores mensuales, y su variación de un mes a otro es en parte producto del método. Eso no las invalida, pero obliga a no leer un movimiento mensual aislado como si fuera un dato.\n\n### Descarga reproducible {#sec-datos-descarga}\n\nLa regla del libro es simple: `data/raw/` es inmutable y todo lo demás se reconstruye con un script. Ninguna serie se edita a mano, y ningún resultado depende de un archivo que sólo existe en la computadora de quien escribe. Las series de este capítulo se descargan así:\n\n::: {#descarga .cell execution_count=12}\n``` {.python .cell-code}\nfrom urllib.request import urlretrieve\n\nfrom MacroPy import get_bcrp_data\n\nFRED = \"https://fred.stlouisfed.org/graph/fredgraph.csv?id=\"\nfor code in [\"DEXUSEU\", \"HOUSTNSA\", \"FEDFUNDS\", \"ND000334Q\"]:\n    urlretrieve(FRED + code, f\"data/raw/fred_{code}.csv\")\n\nperu = get_bcrp_data({\"PN02538AQ\": \"pbi\"}, frequency=\"Q\",\n                     start_period=\"1996-1\")\n```\n:::\n\n\nFRED entrega sus series como CSV sin necesidad de registrarse, y `get_bcrp_data` de `MacroPy` consulta la API del BCRP. Esa celda no se ejecuta al compilar el libro, a propósito. Los archivos que produce están guardados en `data/raw/`, de modo que el libro se compila sin conexión y los resultados no cambian cuando la fuente revisa el pasado. Para actualizar, se corre la descarga y se vuelve a compilar: la diferencia entre las dos versiones es exactamente la revisión de los datos.\n\n## Otros temas {#sec-datos-otros}\n\n### Revisiones y datos en tiempo real\n\nLas bases de datos de *vintages*, como ALFRED de la Reserva Federal de San Luis, guardan lo que se publicó en cada fecha. Un ejercicio de pronóstico honesto usa, en cada momento, sólo lo que estaba disponible entonces [@croushore2001]. La diferencia no es menor: las primeras estimaciones del PBI se revisan en varias décimas, y con series muy revisadas la evaluación con datos finales exagera la calidad del pronóstico.\n\n### Valores atípicos y la pandemia\n\nEl PBI peruano desestacionalizado cae 26.5 % en el segundo trimestre de 2020 y sube 30.3 % en el tercero. Un modelo lineal con errores gaussianos estimado sobre esa muestra interpreta esos trimestres como evidencia sobre la dinámica normal de la economía, y el resultado es una varianza sobreestimada y unos coeficientes deformados. Las opciones son tratarlos como atípicos con variables dummy, escalar la volatilidad de esos periodos [@lenza2022], excluir el tramo o modelar la volatilidad cambiante como en el @sec-volatilidad. Ninguna es gratis, y lo mínimo es decir cuál se usó.\n\n### Frecuencias y agregación\n\nPasar de mensual a trimestral parece inocuo y no lo es. Un promedio de tres meses no es lo mismo que el dato de fin de trimestre: el promedio suaviza y crea autocorrelación, el fin de periodo conserva el ruido. Para variables de flujo, como el PBI, corresponde promediar o sumar; para variables de saldo, como una tasa de interés o el tipo de cambio, el promedio y el fin de periodo responden preguntas distintas y la elección debe declararse. Los capítulos siguientes trabajan con series ya agregadas por la fuente y no re-agregan nada, precisamente para no añadir una decisión propia a las que la fuente ya tomó.\n\n## Ideas clave {.unnumbered}\n\n::: {.ideas-clave}\n1. Las series macroeconómicas difieren en frecuencia, tendencia y dinámica de corto plazo. Sus niveles son casi siempre muy persistentes; sus cambios, mucho menos.\n2. La descomposición en tendencia, ciclo, estacionalidad e irregular necesita supuestos: la parte estacional está bien identificada, la separación entre tendencia y ciclo no.\n3. En una serie sin ajustar el calendario domina el corto plazo. El ajuste estacional lo remueve en dos pasos, limpiar calendario y atípicos y luego separar un patrón que cambia lentamente.\n4. La variación interanual no reemplaza al ajuste: llega tarde a los quiebres y arrastra efectos base, como muestra el Perú de 2021.\n5. El logaritmo se usa porque linealiza el crecimiento, aproxima la tasa cuando es pequeña y se suma; que estabilice la varianza es una hipótesis que hay que contrastar serie por serie.\n:::\n\n## Lecturas recomendadas {.unnumbered}\n\n::: {.lecturas}\nGhysels y Osborn (2001)\n:   el tratamiento econométrico completo de la estacionalidad.\n\nFindley et al. (1998)\n:   la descripción oficial del programa X-12-ARIMA, base del X-13 actual.\n\nGómez y Maravall (1996)\n:   el manual de TRAMO-SEATS, con la lógica de extracción de señal basada en modelos.\n\nEurostat (2024)\n:   las directrices europeas de ajuste estacional; el documento que siguen las oficinas de estadística.\n\nLütkepohl y Xu (2012)\n:   qué gana y qué pierde el pronóstico al tomar logaritmos.\n:::\n\n## Ejercicios {.unnumbered}\n\n::: {#exr-datos-1}\nReproduzca la simulación de la @fig-datos-simulacion con una estacionalidad cuya amplitud crece 2 % por año. Desestacionalice con X-13 y con STL y compare cuál sigue mejor el cambio de patrón.\n:::\n\n::: {#exr-datos-2}\nTome la serie mensual del IPC peruano y calcule la inflación de tres maneras: interanual, mensual anualizada sobre la serie observada y mensual anualizada sobre la desestacionalizada. Grafique las tres desde 2020 y explique cuál habría sido más útil para decidir la tasa de política en cada momento.\n:::\n\n::: {#exr-datos-3}\nDesestacionalice los inicios de viviendas de Estados Unidos con `seasonal_adjust` y estime el factor de cada mes en dos submuestras, 2000-2012 y 2013-2026. ¿Cambió el patrón? Relacione el resultado con el argumento contra las variables dummy estacionales.\n:::\n\n::: {#exr-datos-4}\nVerifique numéricamente la @eq-aproximacion: para las tasas interanuales del PBI peruano, calcule la diferencia entre $\\ln(1+g_t)$ y $g_t$ y encuentre a partir de qué tasa el error supera un punto porcentual. Compare el resultado con el que predice el término $g^2/2$.\n:::\n\n::: {#exr-datos-5}\nConstruya la serie trimestral del PBI peruano a partir del índice mensual desestacionalizado de dos maneras, promediando los meses y tomando el último mes de cada trimestre. Estime un AR(4) sobre la tasa de crecimiento de cada una y compare la persistencia estimada. ¿Cuánto de lo que se lee como dinámica económica es consecuencia de la agregación?\n:::\n\n",
    "supporting": [
      "01-macro-data_files/figure-pdf"
    ],
    "filters": []
  }
}