{
  "hash": "a5c5242a31510f5e8092999880a131bb",
  "result": {
    "engine": "jupyter",
    "markdown": "# Modelos univariados {#sec-univariado}\n\n::: {.pregunta}\n¿Cuánta memoria tiene una serie macroeconómica y cuánto de su futuro puede explicarse con su propio pasado?\n:::\n\n*Capítulo en preparación. El esqueleto de secciones fija el alcance y el orden de la exposición; la estimación bayesiana (@sec-univariado-bayes) ya está escrita.*\n\n::: {.aprendizajes}\n1. Cómo leer la función de autocorrelación de una serie macro y qué modelo sugiere.\n2. Cómo estimar y diagnosticar un AR(p) y un ARMA(p,q) en Python.\n3. Qué dice y qué no dice una prueba de raíz unitaria sobre la especificación.\n4. Por qué la caminata aleatoria es el rival a vencer en cualquier ejercicio de pronóstico.\n:::\n\n**Requisitos previos.** Álgebra matricial básica ([sección 0.3](00-preliminares.qmd#sec-prelim-numpy)), distribuciones y simulación ([secciones 0.10](00-preliminares.qmd#sec-prelim-distribuciones) y [0.11](00-preliminares.qmd#sec-prelim-simulacion)), estimación por máxima verosimilitud y @sec-datos.\n\n::: {.datos-usados}\n| Serie | Fuente | Frecuencia | Transformación |\n|:-------------------------------|:--------|:-----------|:--------------------------|\n| PBI real | BCRP | trimestral | var. % interanual |\n| Inflación | BCRP | mensual | var. % interanual |\n| AR(1) simulado | este capítulo | | estimación bayesiana |\n\nLos datos crudos se descargan a `data/raw/` y las series construidas quedan en `data/processed/`.\n:::\n\n## Estacionariedad en sentido débil\n\n*Por escribir:* qué exige y por qué casi ninguna serie macro en niveles la cumple.\n\n## Procesos AR, MA y ARMA\n\n*Por escribir:* representación, condiciones de estabilidad e invertibilidad, autocorrelaciones teóricas.\n\n## Estimación\n\n*Por escribir:* MCO condicional y máxima verosimilitud exacta; qué cambia en muestras cortas.\n\n### Estimación bayesiana {#sec-univariado-bayes}\n\nLa estimación clásica trata los parámetros como constantes desconocidas y describe la incertidumbre con la distribución del estimador en muestras repetidas. La bayesiana trata los parámetros como variables aleatorias y describe la incertidumbre con una distribución sobre ellos. El teorema de Bayes combina lo que se sabía antes de ver los datos, el **prior**, con lo que dicen los datos, la **verosimilitud**:\n\n$$ p(\\theta \\mid y) \\propto p(y \\mid \\theta)\\, p(\\theta) . $$ {#eq-univariado-bayes}\n\nLa @sec-bvar-bayes muestra el caso más simple, un parámetro con prior normal, en el que la media posterior es un promedio de la del prior y la del dato ponderado por sus precisiones. Aquí el objetivo es el paso siguiente: estimar el AR(1),\n\n$$ y_t = c + \\phi\\, y_{t-1} + \\varepsilon_t, \\qquad \\varepsilon_t \\sim N(0, \\sigma^2), $$\n\ncon **todos** sus parámetros desconocidos, $\\beta = (c, \\phi)'$ y $\\sigma^2$. Con $Y$ el vector de $y_2, \\dots, y_T$ y $X$ la matriz con una columna de unos y otra con $y_1, \\dots, y_{T-1}$, el modelo es la regresión $Y = X\\beta + \\varepsilon$.\n\nLa posterior conjunta de $(\\beta, \\sigma^2)$ no tiene una forma conocida, pero las dos condicionales sí. Con un prior normal $\\beta \\sim N(\\beta_0, V_0)$ y uno inversa-gamma $\\sigma^2 \\sim \\mathcal{IG}(a_0, d_0)$ ([sección 0.10](00-preliminares.qmd#sec-prelim-distribuciones)),\n\n$$\n\\begin{aligned}\n\\beta \\mid \\sigma^2, y &\\sim N(\\bar{\\beta}, \\bar{V}), \\\\\n\\bar{V} &= \\big(V_0^{-1} + \\sigma^{-2} X'X\\big)^{-1}, \\qquad \\bar{\\beta} = \\bar{V}\\big(V_0^{-1}\\beta_0 + \\sigma^{-2} X'Y\\big), \\\\\n\\sigma^2 \\mid \\beta, y &\\sim \\mathcal{IG}\\Big(a_0 + \\tfrac{T-1}{2},\\ d_0 + \\tfrac{1}{2}(Y - X\\beta)'(Y - X\\beta)\\Big).\n\\end{aligned}\n$$ {#eq-univariado-condicionales}\n\n::: {#alg-univariado-gibbs}\n1. Fijar un valor inicial $\\sigma^{2(0)}$.\n2. Para $j = 1, \\dots, J$: extraer $\\beta^{(j)}$ de $N(\\bar{\\beta}, \\bar{V})$, con $\\bar{\\beta}$ y $\\bar{V}$ evaluadas en $\\sigma^{2(j-1)}$, y luego $\\sigma^{2(j)}$ de la inversa-gamma de la @eq-univariado-condicionales evaluada en $\\beta^{(j)}$.\n3. Descartar las primeras $J_0$ extracciones, el periodo inicial, y tratar las restantes como una muestra de la posterior conjunta.\n\nMuestreador de Gibbs para el AR(1)\n:::\n\nEl @alg-univariado-gibbs alterna entre las dos condicionales. Después del periodo inicial, las extracciones se distribuyen según la posterior conjunta. Son exactamente las dos etapas del algoritmo de la @sec-bvar-gibbs con una sola variable: $\\Sigma^{-1} \\otimes X'X$ se vuelve $\\sigma^{-2}X'X$ y la inversa-Wishart se vuelve una inversa-gamma.\n\nPara ver el algoritmo en acción conviene un caso en que se conoce la respuesta: 80 observaciones simuladas de un AR(1) con $c = 0.5$, $\\phi = 0.9$ y $\\sigma = 1$, las mismas del bootstrap de la [sección 0.11](00-preliminares.qmd#sec-prelim-simulacion). El prior para $\\phi$ se centra en uno con desvío 0.2, que es la idea del prior de Minnesota de la @sec-bvar-minnesota: a falta de evidencia en contra, una serie macroeconómica se parece a una caminata aleatoria. El de la constante es difuso.\n\n::: {#univariado-gibbs .cell execution_count=1}\n``` {.python .cell-code}\nimport numpy as np\nfrom scipy import stats\n\n\ndef simulate_ar1(c, phi, sigma, T, seed=None):\n    \"\"\"Simulate an AR(1) starting at its unconditional mean.\"\"\"\n    rng = np.random.default_rng(seed)\n    y = np.empty(T)\n    y[0] = c / (1 - phi)\n    for t in range(1, T):\n        shock = sigma * rng.standard_normal()\n        y[t] = c + phi * y[t - 1] + shock\n    return y\n\n\ny = simulate_ar1(0.5, 0.9, 1.0, T=80, seed=6)\nX = np.column_stack([np.ones(len(y) - 1), y[:-1]])\nY = y[1:]\nb_ols = np.linalg.solve(X.T @ X, X.T @ Y)\n\nbeta0 = np.array([0.0, 1.0])\nV0_inv = np.diag([1 / 10.0, 1 / 0.2**2])\na0, d0 = 2.0, 1.0\n\nrng = np.random.default_rng(9)\nsigma2, keep = 1.0, []\nfor step in range(6000):\n    V = np.linalg.inv(V0_inv + X.T @ X / sigma2)\n    mean = V @ (V0_inv @ beta0 + X.T @ Y / sigma2)\n    beta = rng.multivariate_normal(mean, V)\n    e = Y - X @ beta\n    sigma2 = stats.invgamma.rvs(a0 + len(Y) / 2,\n                                scale=d0 + e @ e / 2,\n                                random_state=rng)\n    keep.append([beta[0], beta[1], sigma2])\n\ndraws = np.array(keep)[1000:]            # discard burn-in\nphi_draws = draws[:, 1]\nprint(f\"media posterior de phi: {phi_draws.mean():.3f} \"\n      f\"(MCO {b_ols[1]:.3f})\")\nprint(\"intervalo al 68 %:\",\n      np.round(np.quantile(phi_draws, [0.16, 0.84]), 3))\nprint(\"intervalo al 95 %:\",\n      np.round(np.quantile(phi_draws, [0.025, 0.975]), 3))\nprint(f\"P(phi >= 1 | y) = {(phi_draws >= 1).mean():.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nmedia posterior de phi: 0.877 (MCO 0.863)\nintervalo al 68 %: [0.816 0.937]\nintervalo al 95 %: [0.761 0.995]\nP(phi >= 1 | y) = 0.022\n```\n:::\n:::\n\n\n::: {#cell-fig-univariado-gibbs .cell execution_count=2}\n``` {.python .cell-code}\nimport matplotlib.pyplot as plt\n\nfrom macrobook import use_style, figsize, charts\n\nuse_style()\n\nall_phi = np.array(keep)[:, 1]\ngrid = np.linspace(0.4, 1.4, 300)\n\nfig, axes = plt.subplots(1, 2, figsize=figsize(0.38))\ncharts.trace(axes[0], all_phi, burn=1000)\naxes[0].set_title(\"cadena de φ\", fontsize=8.5)\naxes[0].set_xlabel(\"iteración\")\nprior_pdf = stats.norm(1, 0.2).pdf(grid)\ncharts.prior_posterior(axes[1], phi_draws,\n                       prior_density=prior_pdf,\n                       grid=grid, ols_value=b_ols[1])\naxes[1].set_xlim(0.4, 1.4)\naxes[1].set_yticks([])\naxes[1].set_title(\"posterior de φ\", fontsize=8.5)\ncharts.legend_outside(axes[1], ncol=3)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Muestreador de Gibbs del AR(1). Izquierda: la cadena de $\\phi$, con el periodo inicial descartado sombreado. Derecha: la posterior de $\\phi$, la densidad del prior y la estimación de mínimos cuadrados.](02-univariate_files/figure-html/fig-univariado-gibbs-output-1.svg){#fig-univariado-gibbs}\n:::\n:::\n\n\nLa media posterior de $\\phi$, 0.877, queda entre el prior y la estimación de mínimos cuadrados, 0.863, mucho más cerca de esta porque 79 observaciones informan más que un prior con desvío 0.2. Y la posterior responde una pregunta que el estimador clásico no puede responder directamente: la probabilidad de que el proceso tenga una raíz unitaria o sea explosivo, $P(\\phi \\geq 1 \\mid y)$, que aquí es de 2 %. La @sec-bvar-gibbs descarta esas extracciones cuando necesita respuestas al impulso bien definidas; aquí se reportan, porque son información.\n\n::: {.intuicion}\nEl muestreador de Gibbs cambia un problema difícil, extraer de una distribución conjunta sin forma conocida, por una sucesión de problemas fáciles, extraer de cada condicional sabiendo el resto. Funciona siempre que cada condicional se pueda muestrear, y esa es la razón por la que los priors conjugados, normal para los coeficientes e inversa-gamma o inversa-Wishart para las varianzas, dominan la macroeconometría bayesiana aplicada.\n:::\n\nEl @sec-bayes trata lo que queda fuera de esta sección: el algoritmo de Metropolis-Hastings, el diagnóstico de convergencia de las cadenas y la elección de los priors.\n\n\n## Selección de rezagos\n\n*Por escribir:* AIC, BIC y validación fuera de muestra: tres criterios que rara vez coinciden.\n\n## Raíces unitarias\n\n*Por escribir:* Dickey-Fuller aumentado, potencia baja y la decisión de diferenciar.\n\n## Pronóstico y evaluación\n\n*Por escribir:* pronóstico a h pasos, intervalos y comparación contra la caminata aleatoria.\n\n## Diagnósticos\n\n*Por escribir:* residuos, estabilidad de parámetros y qué hacer cuando fallan.\n\n\n## Ideas clave {.unnumbered}\n\n::: {.ideas-clave}\n1. Un AR(p) bien especificado ya es un pronosticador difícil de batir a horizontes cortos.\n2. Las pruebas de raíz unitaria tienen poca potencia: la decisión de diferenciar es, en parte, una decisión económica.\n3. Todo lo multivariado del libro es una extensión de este capítulo; conviene tener la intuición univariada firme.\n:::\n\n## Lecturas recomendadas {.unnumbered}\n\n::: {.lecturas}\nHamilton (1994), caps. 3-5\n:   el tratamiento de referencia de los procesos ARMA.\n\nBox y Jenkins (1970)\n:   la metodología original de identificación, estimación y diagnóstico.\n\nDickey y Fuller (1979)\n:   la distribución del estimador bajo raíz unitaria.\n\nGelman et al. (2013)\n:   [*Bayesian Data Analysis*](https://sites.stat.columbia.edu/gelman/book/), gratuito en línea; el tratamiento de referencia de la inferencia bayesiana y del muestreo de Gibbs.\n\n:::\n\n## Ejercicios {.unnumbered}\n\n::: {#exr-univariado-1}\nEstime un AR(4) para la inflación y compare su RECM fuera de muestra con la de una caminata aleatoria a horizontes 1, 4 y 8.\n:::\n\n::: {#exr-univariado-2}\nSimule 500 series de un AR(1) con coeficiente 0.95 y T = 80. ¿En qué fracción de los casos el ADF rechaza la raíz unitaria?\n:::\n\n::: {#exr-univariado-3}\nRepita el muestreador de Gibbs de la @sec-univariado-bayes con un prior para $\\phi$ centrado en cero con desvío 0.5. Compare la media posterior con la del texto y relacione la diferencia con el papel de $\\delta_i$ y $\\lambda_1$ en el prior de Minnesota.\n:::\n\n::: {.solucion}\nCon el prior centrado en cero la media posterior de $\\phi$ queda por debajo de la estimación de mínimos cuadrados, porque el prior empuja hacia la ausencia de persistencia; con el prior centrado en uno queda por encima. La media del prior es el papel de $\\delta_i$, que fija hacia qué valor se encoge el primer rezago propio, y el desvío es el de $\\lambda_1$, que fija con cuánta fuerza. Con las 79 observaciones del texto la media posterior pasa de 0.877 a 0.852, una diferencia de dos centésimas y media; con sólo las primeras 30 la diferencia supera las ocho centésimas, porque el prior pesa más cuando los datos informan menos.\n:::\n\n",
    "supporting": [
      "02-univariate_files/figure-html"
    ],
    "filters": [],
    "includes": {}
  }
}