{
  "hash": "06d34e34b3cf64494fd2262a9f25a17d",
  "result": {
    "engine": "jupyter",
    "markdown": "# Modelos univariados {#sec-univariado}\n\n::: {.pregunta}\nUn trimestre de crecimiento bajo en Estados Unidos dice muy poco sobre el crecimiento de dentro de un año; un trimestre de inflación alta dice bastante sobre la inflación del año siguiente. ¿Cómo se mide esa memoria, y cuánto del futuro de una serie se explica con su propio pasado?\n:::\n\n::: {.aprendizajes}\n1. Leer la memoria de una serie en su función de autocorrelación y en las raíces de su polinomio de rezagos.\n2. Pasar de un AR($p$) a su forma companion y a su representación de Wold, que son el esqueleto del VAR y de sus respuestas al impulso.\n3. Estimar un AR($p$), elegir el número de rezagos y pronosticar con intervalos que salen de los pesos de Wold.\n4. Entender qué dice una prueba de raíz unitaria y por qué la caminata aleatoria es el rival a vencer.\n:::\n\n**Requisitos previos.** Álgebra matricial y autovalores ([secciones 0.3](00-preliminares.qmd#sec-prelim-numpy) y [0.4](00-preliminares.qmd#sec-prelim-autovalores)), distribuciones y simulación ([0.10](00-preliminares.qmd#sec-prelim-distribuciones) y [0.11](00-preliminares.qmd#sec-prelim-simulacion)) y @sec-datos.\n\n::: {.datos-usados}\n| Serie | Fuente | Frecuencia | Transformación |\n|:-------------------------------|:--------|:-----------|:--------------------------|\n| PBI real de EE.UU. (`GDPC1`) | FRED | trimestral | $400\\,\\Delta \\ln$, % anualizado |\n| Índice de precios PCE (`PCEPI`) | FRED | mensual, promediado por trimestre | $400\\,\\Delta \\ln$, % anualizado |\n| AR(1) simulado | este capítulo | | estimación bayesiana |\n\nLa muestra de estimación es 1960T1-2019T4. La pandemia produce variaciones del PBI de otra escala (@sec-datos-otros), y los trimestres de 2020 a 2023 se reservan para evaluar un pronóstico.\n:::\n\n## Memoria y estacionariedad {#sec-univariado-memoria}\n\nLa @fig-univariado-series muestra las dos series del capítulo, el crecimiento del PBI real y la inflación medida con el índice de precios del consumo personal (PCE), la que usa la Reserva Federal para su meta. Las dos oscilan alrededor de un promedio parecido, cerca de 3 %, pero lo hacen de manera muy distinta: el crecimiento salta de un trimestre a otro sin mucho patrón; la inflación se desplaza lentamente, con episodios que duran años.\n\n::: {#univariado-datos .cell execution_count=1}\n``` {.python .cell-code}\nimport numpy as np\nimport pandas as pd\n\nfrom macrobook import data_path, var\n\n\ndef read(name, freq):\n    table = pd.read_csv(data_path(name), index_col=\"date\")\n    table.index = pd.PeriodIndex(table.index, freq=freq)\n    return table\n\n\ngdp = read(\"us_quarterly.csv\", \"Q\")[\"gdp\"]\npce = read(\"us_monthly.csv\", \"M\")[\"pce_price\"]\npce_q = pce.resample(\"Q\").mean()[:\"2026Q2\"]\n\ngrowth_all = 400 * np.log(gdp).diff()      # % anualizado\ninfl_all = 400 * np.log(pce_q).diff()\ngrowth = growth_all[\"1960\":\"2019\"]\ninfl = infl_all[\"1960\":\"2019\"]\nseries = {\"crecimiento\": growth, \"inflación\": infl}\n\nfor name, x in series.items():\n    print(f\"{name:11} T = {len(x)}, media {x.mean():.2f}, \"\n          f\"desvío {x.std():.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ncrecimiento T = 240, media 3.01, desvío 3.25\ninflación   T = 240, media 3.18, desvío 2.54\n```\n:::\n:::\n\n\nLa memoria de una serie se mide con sus autocovarianzas, y para que ese objeto tenga sentido hace falta que no dependa de la fecha.\n\n::: {#def-univariado-estacionariedad}\n## Estacionariedad en covarianza y autocorrelación\n\nUn proceso $\\{y_t\\}$ es estacionario en covarianza si $\\mathbb{E}[y_t] = \\mu$ y $\\operatorname{Cov}(y_t, y_{t-j}) = \\gamma_j$ para todo $t$ y todo $j \\geq 0$, con $\\gamma_0$ finita. Su función de autocorrelación es $\\rho_j = \\gamma_j / \\gamma_0$, y se estima con\n\n$$ \\hat{\\rho}_j = \\frac{\\sum_{t=j+1}^{T} (y_t - \\bar{y})(y_{t-j} - \\bar{y})}{\\sum_{t=1}^{T} (y_t - \\bar{y})^2} . $$ {#eq-univariado-acf}\n:::\n\nSi la serie fuera ruido blanco, es decir, sin ninguna autocorrelación, cada $\\hat{\\rho}_j$ sería aproximadamente normal con media cero y varianza $1/T$, de modo que la banda $\\pm 1.96/\\sqrt{T}$ separa lo que es memoria de lo que puede ser azar. El @sec-var extiende la definición a vectores (@def-estacionariedad), con matrices de autocovarianza en lugar de números.\n\n::: {.cell execution_count=2}\n``` {.python .cell-code}\nimport matplotlib.pyplot as plt\n\nfrom macrobook import use_style, figsize, PALETTE, charts\n\nuse_style()\n\n\ndef acf(x, lags):\n    \"\"\"Sample autocorrelations rho_1, ..., rho_lags.\"\"\"\n    z = np.asarray(x) - np.mean(x)\n    return np.array([z[j:] @ z[:len(z) - j] / (z @ z)\n                     for j in range(1, lags + 1)])\n\n\nlags = np.arange(1, 21)\nband = 1.96 / np.sqrt(len(growth))\nfig, axes = plt.subplots(2, 2, figsize=figsize(0.62))\nfor col, (name, x) in enumerate(series.items()):\n    top, bottom = axes[0, col], axes[1, col]\n    top.plot(x.index.to_timestamp(how=\"end\"), x,\n             color=PALETTE[\"ink\"], lw=0.7)\n    charts.zero_line(top)\n    charts.year_ticks(top, every=10)\n    top.set_title(f\"{name} (%)\", fontsize=8.5)\n    rho = acf(x, 20)\n    bottom.axhspan(-band, band, color=PALETTE[\"surface_strong\"],\n                   lw=0)\n    bottom.vlines(lags, 0, rho, color=PALETTE[\"accent\"], lw=1.2)\n    bottom.plot(lags, rho, \"o\", ms=2.5, color=PALETTE[\"accent\"])\n    charts.zero_line(bottom)\n    bottom.set_ylim(-0.3, 1.0)\n    bottom.set_xlabel(\"rezago (trimestres)\")\n    bottom.set_title(\"autocorrelación\", fontsize=8.5)\nfig.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Crecimiento del PBI real y de los precios PCE de Estados Unidos, 1960-2019, en % anualizado (arriba), y sus autocorrelaciones muestrales hasta 20 trimestres (abajo). La banda gris es $\\pm 1.96/\\sqrt{T}$: lo que cae dentro es compatible con ausencia de memoria.](02-univariate_files/figure-pdf/fig-univariado-series-output-1.pdf){#fig-univariado-series fig-pos='H'}\n:::\n:::\n\n\n\nLas autocorrelaciones confirman lo que se ve a simple vista. La del crecimiento es 0\\.30 a un trimestre y cae dentro de la banda de 0\\.13 antes de los cuatro trimestres: un trimestre malo apenas informa sobre el siguiente año. La de la inflación es 0\\.82 a un trimestre y todavía 0\\.51 a dos años. Esa memoria larga es también la razón para dudar de la estacionariedad de la inflación: su promedio fue 6\\.4 % en los años setenta y 1\\.5 % en 2010-2019, y ninguna prueba sobre una sola muestra distingue con seguridad entre una media que cambia y una memoria muy larga. La @sec-univariado-raices vuelve sobre esto.\n\n## Procesos AR, MA y ARMA {#sec-univariado-arma}\n\nEl operador de rezagos $L$ desplaza una serie un periodo, $L y_t = y_{t-1}$, y permite escribir la dinámica como un polinomio: $\\phi(L) = 1 - \\phi_1 L - \\cdots - \\phi_p L^p$.\n\n::: {#def-univariado-arma}\n## Procesos AR, MA y ARMA\n\nCon $\\varepsilon_t$ ruido blanco de varianza $\\sigma^2$,\n\n- un **AR($p$)** es $y_t = c + \\phi_1 y_{t-1} + \\cdots + \\phi_p y_{t-p} + \\varepsilon_t$, es decir, $\\phi(L)\\, y_t = c + \\varepsilon_t$;\n- un **MA($q$)** es $y_t = \\mu + \\varepsilon_t + \\theta_1 \\varepsilon_{t-1} + \\cdots + \\theta_q \\varepsilon_{t-q}$, es decir, $y_t = \\mu + \\theta(L)\\, \\varepsilon_t$;\n- un **ARMA($p, q$)** combina ambos: $\\phi(L)\\, y_t = c + \\theta(L)\\, \\varepsilon_t$.\n:::\n\nEl AR($p$) es el caso que más importa en este libro, porque es un VAR con una sola variable: todo lo que sigue sobre estabilidad, memoria y pronóstico reaparece en el @sec-var con matrices en lugar de números. Como allí, conviene escribirlo en forma companion, apilando el presente y los $p - 1$ rezagos:\n\n$$\n\\underbrace{\\begin{bmatrix} y_t \\\\ y_{t-1} \\\\ \\vdots \\\\ y_{t-p+1} \\end{bmatrix}}_{\\tilde{y}_t}\n=\n\\begin{bmatrix} c \\\\ 0 \\\\ \\vdots \\\\ 0 \\end{bmatrix}\n+\n\\underbrace{\\begin{bmatrix}\n \\phi_1 & \\phi_2 & \\cdots & \\phi_{p-1} & \\phi_p \\\\\n 1 & 0 & \\cdots & 0 & 0 \\\\\n \\vdots & & \\ddots & & \\vdots \\\\\n 0 & 0 & \\cdots & 1 & 0\n\\end{bmatrix}}_{F}\n\\tilde{y}_{t-1}\n+\n\\begin{bmatrix} \\varepsilon_t \\\\ 0 \\\\ \\vdots \\\\ 0 \\end{bmatrix} .\n$$ {#eq-univariado-companion}\n\nEs la @eq-companion con $n = 1$. Un AR($p$) es así un AR(1) de dimensión $p$, y su comportamiento queda determinado por las potencias de $F$.\n\n::: {#prp-univariado-estabilidad}\n## Estabilidad del AR($p$)\n\nEl AR($p$) es estacionario en covarianza si y sólo si todas las raíces de $\\phi(z) = 0$ están fuera del círculo unitario, lo que equivale a que todos los valores propios de $F$ tengan módulo menor que uno. Su media es entonces $\\mu = c / \\phi(1) = c / (1 - \\phi_1 - \\cdots - \\phi_p)$.\n:::\n\nLa equivalencia es algebraica: los valores propios de $F$ resuelven $\\lambda^p - \\phi_1 \\lambda^{p-1} - \\cdots - \\phi_p = 0$, que es $\\phi(z) = 0$ con $z = 1/\\lambda$. Si hay valores propios complejos, la memoria oscila: es la forma más simple de generar un ciclo, y el @exr-univariado-4 lo muestra.\n\nLa estabilidad permite sustituir hacia atrás indefinidamente y escribir la serie como una suma de choques pasados. Ese resultado vale para cualquier proceso estacionario, no sólo para los AR.\n\n::: {#thm-univariado-wold}\n## Descomposición de Wold\n\nTodo proceso estacionario en covarianza y sin componente determinista se puede escribir como\n\n$$ y_t = \\mu + \\sum_{j=0}^{\\infty} \\psi_j\\, \\varepsilon_{t-j}, \\qquad \\psi_0 = 1, \\qquad \\sum_{j=0}^{\\infty} \\psi_j^2 < \\infty , $$ {#eq-univariado-wold}\n\ndonde $\\varepsilon_t$ es el error del mejor pronóstico lineal de $y_t$ con su propio pasado [@hamilton1994, cap. 4]. En un AR($p$) estable, $\\psi_j = [F^j]_{11}$.\n:::\n\nLos pesos $\\psi_j$ tienen tres lecturas que el libro usa una y otra vez. Son la **respuesta al impulso**: cuánto cambia $y_{t+j}$ si hoy llega un choque de una unidad; el @sec-svar les da a esos choques una interpretación económica, y las proyecciones locales de la @sec-svar-lp los estiman directamente. Determinan el **error de pronóstico**, como se verá en la @sec-univariado-pronostico. Y su suma resume la **persistencia**:\n\n$$ \\sum_{j=0}^{\\infty} \\psi_j = \\frac{1}{\\phi(1)} = \\frac{1}{1 - \\rho}, \\qquad \\rho = \\phi_1 + \\cdots + \\phi_p . $$ {#eq-univariado-largo-plazo}\n\nLa suma de los coeficientes $\\rho$ es la medida de persistencia más usada, y $1/(1-\\rho)$ es el efecto acumulado de un choque. Si $y_t$ es una tasa de crecimiento, ese acumulado es el efecto permanente sobre el nivel, que es exactamente lo que fijan las restricciones de largo plazo de la @sec-svar-largo-plazo.\n\n::: {.intuicion}\nWold dice que los modelos AR y MA no son una elección arbitraria: cualquier serie estacionaria es un MA($\\infty$), y la tarea es aproximar sus pesos $\\psi_j$ con pocos parámetros. Un MA($q$) los corta en $q$; un AR($p$) los genera con una recursión que decae geométricamente; un ARMA combina ambas cosas.\n:::\n\nEl MA($q$) tiene memoria exacta: $\\rho_j = 0$ para $j > q$, y es estacionario para cualquier valor de los $\\theta$. Se le exige otra condición, la **invertibilidad** (raíces de $\\theta(z)$ fuera del círculo unitario), para que los choques se puedan recuperar del pasado observado de la serie; en los VAR estructurales esa misma condición deja de estar garantizada (@sec-svar-otros). Los ARMA son más parsimoniosos que los AR, pero su verosimilitud no es lineal en los parámetros y se evalúa con el filtro de Kalman del @sec-estado. En macroeconometría aplicada dominan los AR por tres razones prácticas: se estiman por mínimos cuadrados, se extienden sin cambios a varias variables, y con suficientes rezagos aproximan cualquier secuencia $\\psi_j$ que decaiga.\n\n## Estimación {#sec-univariado-estimacion}\n\n### Mínimos cuadrados y verosimilitud\n\nCon errores normales y condicionando en las primeras $p$ observaciones, la log-verosimilitud del AR($p$) es\n\n$$ \\ell(\\phi, \\sigma^2) = -\\frac{T - p}{2} \\ln(2\\pi\\sigma^2) - \\frac{1}{2\\sigma^2} \\sum_{t=p+1}^{T} \\big(y_t - c - \\phi_1 y_{t-1} - \\cdots - \\phi_p y_{t-p}\\big)^2 , $$ {#eq-univariado-verosimilitud}\n\ny maximizarla en los coeficientes es minimizar la suma de cuadrados: **mínimos cuadrados ordinarios es el estimador de máxima verosimilitud condicional**. La verosimilitud exacta agrega la densidad de las primeras $p$ observaciones, que depende de la estacionariedad; la diferencia sólo importa en muestras cortas o cerca de una raíz unitaria, y se calcula con el filtro de Kalman.\n\nMínimos cuadrados es consistente y asintóticamente normal si el proceso es estable, pero en muestras finitas subestima la persistencia. En un AR(1), el sesgo es aproximadamente $-(1 + 3\\phi)/T$ [@kendall1954], el mismo que la [sección 0.11](00-preliminares.qmd#sec-prelim-simulacion) midió por Monte Carlo y por bootstrap. Con $T = 240$ y $\\phi = 0.9$ es de dos centésimas, pero crece rápido cuando la muestra se acorta, y por eso las respuestas al impulso de los VAR se corrigen por sesgo [@kilian1998].\n\nEl código usa la misma función que el @sec-var para estimar un VAR, con una sola variable. La matriz de regresores, los coeficientes y la varianza residual son exactamente los mismos objetos.\n\n::: {#univariado-mco .cell execution_count=4}\n``` {.python .cell-code}\norders = {\"crecimiento\": 2, \"inflación\": 3}\nfits = {}\nfor name, x in series.items():\n    p = orders[name]\n    fits[name] = var.ols(x.to_numpy().reshape(-1, 1), p)\n    B = fits[name][\"B\"].ravel()\n    sigma = np.sqrt(fits[name][\"Sigma\"][0, 0])\n    print(f\"{name}: AR({p}), c = {B[0]:.2f}, \"\n          f\"phi = {np.round(B[1:], 3)}, sigma = {sigma:.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ncrecimiento: AR(2), c = 1.65, phi = [0.261 0.192], sigma = 3.01\ninflación: AR(3), c = 0.34, phi = [0.628 0.021 0.244], sigma = 1.37\n```\n:::\n:::\n\n\nLos órdenes, dos rezagos para el crecimiento y tres para la inflación, salen de la subsección siguiente. La desviación estándar residual, $\\hat{\\sigma}$, es un insumo que reaparece: el prior de Minnesota de la @sec-bvar-minnesota la usa para poner en la misma escala las ecuaciones de un VAR.\n\n### Cuántos rezagos {#sec-univariado-rezagos}\n\nLos criterios de información comparan el ajuste con el número de parámetros. Con $\\tilde{\\sigma}^2_p$ la varianza residual del AR($p$) dividida por $T$,\n\n$$ \\text{AIC}(p) = \\ln \\tilde{\\sigma}^2_p + \\frac{2(p+1)}{T}, \\qquad \\text{BIC}(p) = \\ln \\tilde{\\sigma}^2_p + \\frac{(p+1)\\ln T}{T} , $$ {#eq-univariado-criterios}\n\ny se elige el $p$ que minimiza cada uno. El BIC penaliza más y elige modelos más cortos; es consistente para el orden verdadero, mientras que el AIC tiende a elegir modelos que pronostican mejor en muestras cortas. La regla práctica que más errores evita es comparar todos los órdenes sobre la **misma muestra efectiva**, descartando las primeras $p_{\\max}$ observaciones para todos.\n\n::: {#univariado-rezagos .cell execution_count=5}\n``` {.python .cell-code}\ndef criteria(x, p_max=8):\n    y = x.to_numpy().reshape(-1, 1)\n    Y, X_all = var.lag_matrix(y, p_max)     # common sample\n    T = len(Y)\n    rows = []\n    for p in range(p_max + 1):\n        X = X_all[:, :1 + p]\n        e = Y - X @ np.linalg.lstsq(X, Y, rcond=None)[0]\n        s2 = (e ** 2).mean()\n        rows.append({\"AIC\": np.log(s2) + 2 * (p + 1) / T,\n                     \"BIC\": np.log(s2)\n                     + (p + 1) * np.log(T) / T})\n    return pd.DataFrame(rows)\n\n\nfor name, x in series.items():\n    table = criteria(x)\n    print(f\"{name}: AIC elige p = {table['AIC'].idxmin()}, \"\n          f\"BIC elige p = {table['BIC'].idxmin()}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ncrecimiento: AIC elige p = 2, BIC elige p = 2\ninflación: AIC elige p = 3, BIC elige p = 3\n```\n:::\n:::\n\n\nLos dos criterios coinciden en las dos series, lo que no siempre ocurre. El @sec-var discute la versión multivariada y qué criterio conviene según el objetivo (@sec-var-otros).\n\n### Lo que dicen los modelos estimados {#sec-univariado-memoria-estimada}\n\n\nLos dos modelos son estables, pero con márgenes muy distintos. El mayor valor propio de la matriz companion mide 0\\.59 en el crecimiento y 0\\.93 en la inflación, y la suma de coeficientes es 0\\.45 y 0\\.89. La @fig-univariado-irf muestra lo que eso significa: tras un choque, el crecimiento conserva 0\\.26 de su efecto a los dos trimestres y prácticamente nada a los dos años; la inflación conserva 0\\.35 a los dos años y 0\\.15 a los cinco.\n\n::: {.cell execution_count=7}\n``` {.python .cell-code}\nhorizon = np.arange(21)\nfig, ax = plt.subplots(figsize=figsize(0.40))\nfor k, (name, fit) in enumerate(fits.items()):\n    psi = var.ma_weights(fit[\"B\"], 1, fit[\"p\"], 20)[:, 0, 0]\n    ax.plot(horizon, psi, color=PALETTE[\"shocks\"][k],\n            ls=PALETTE[\"shock_linestyle\"][k], lw=1.3,\n            marker=\"o\", ms=2.5, label=name)\ncharts.zero_line(ax)\nax.set_xticks(range(0, 21, 4))\nax.set_xlabel(\"trimestres después del choque\")\ncharts.legend_outside(ax, ncol=2)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Pesos de Wold $\\psi_j$ de los modelos estimados: la respuesta de cada serie a un choque de una unidad en el trimestre 0. El crecimiento olvida el choque en un año; la inflación lo arrastra por varios.](02-univariate_files/figure-pdf/fig-univariado-irf-output-1.pdf){#fig-univariado-irf fig-pos='H'}\n:::\n:::\n\n\nLa @eq-univariado-largo-plazo da la otra lectura. En el crecimiento, el efecto acumulado de un choque es 1\\.83 veces el impacto. Como la serie es la tasa anualizada, un choque que la sube un punto eleva el nivel del PBI en 0.25 % al impacto y, si el crecimiento es de verdad un AR estacionario, en 0\\.46 % para siempre. El nivel no vuelve a su senda anterior: eso es una raíz unitaria en el nivel, y que el efecto permanente supere al del impacto es el hallazgo de @campbell1987. En la inflación el acumulado es 9\\.37: con una suma de coeficientes tan cerca de uno, el efecto de largo plazo es grande y además muy impreciso, porque pequeños cambios en $\\rho$ mueven mucho $1/(1-\\rho)$.\n\n### Estimación bayesiana {#sec-univariado-bayes}\n\nLa estimación clásica trata los parámetros como constantes desconocidas y describe la incertidumbre con la distribución del estimador en muestras repetidas. La bayesiana trata los parámetros como variables aleatorias y describe la incertidumbre con una distribución sobre ellos. El teorema de Bayes combina lo que se sabía antes de ver los datos, el **prior**, con lo que dicen los datos, la **verosimilitud**:\n\n$$ p(\\theta \\mid y) \\propto p(y \\mid \\theta)\\, p(\\theta) . $$ {#eq-univariado-bayes}\n\nLa @sec-bvar-bayes muestra el caso más simple, un parámetro con prior normal, en el que la media posterior es un promedio de la del prior y la del dato ponderado por sus precisiones. Aquí el objetivo es el paso siguiente: estimar el AR(1),\n\n$$ y_t = c + \\phi\\, y_{t-1} + \\varepsilon_t, \\qquad \\varepsilon_t \\sim N(0, \\sigma^2), $$\n\ncon **todos** sus parámetros desconocidos, $\\beta = (c, \\phi)'$ y $\\sigma^2$. Con $Y$ el vector de $y_2, \\dots, y_T$ y $X$ la matriz con una columna de unos y otra con $y_1, \\dots, y_{T-1}$, el modelo es la regresión $Y = X\\beta + \\varepsilon$.\n\nLa posterior conjunta de $(\\beta, \\sigma^2)$ no tiene una forma conocida, pero las dos condicionales sí. Con un prior normal $\\beta \\sim N(\\beta_0, V_0)$ y uno inversa-gamma $\\sigma^2 \\sim \\mathcal{IG}(a_0, d_0)$ ([sección 0.10](00-preliminares.qmd#sec-prelim-distribuciones)),\n\n$$\n\\begin{aligned}\n\\beta \\mid \\sigma^2, y &\\sim N(\\bar{\\beta}, \\bar{V}), \\\\\n\\bar{V} &= \\big(V_0^{-1} + \\sigma^{-2} X'X\\big)^{-1}, \\qquad \\bar{\\beta} = \\bar{V}\\big(V_0^{-1}\\beta_0 + \\sigma^{-2} X'Y\\big), \\\\\n\\sigma^2 \\mid \\beta, y &\\sim \\mathcal{IG}\\Big(a_0 + \\tfrac{T-1}{2},\\ d_0 + \\tfrac{1}{2}(Y - X\\beta)'(Y - X\\beta)\\Big).\n\\end{aligned}\n$$ {#eq-univariado-condicionales}\n\n::: {#alg-univariado-gibbs}\n1. Fijar un valor inicial $\\sigma^{2(0)}$.\n2. Para $j = 1, \\dots, J$: extraer $\\beta^{(j)}$ de $N(\\bar{\\beta}, \\bar{V})$, con $\\bar{\\beta}$ y $\\bar{V}$ evaluadas en $\\sigma^{2(j-1)}$, y luego $\\sigma^{2(j)}$ de la inversa-gamma de la @eq-univariado-condicionales evaluada en $\\beta^{(j)}$.\n3. Descartar las primeras $J_0$ extracciones, el periodo inicial, y tratar las restantes como una muestra de la posterior conjunta.\n\nMuestreador de Gibbs para el AR(1)\n:::\n\nEl @alg-univariado-gibbs alterna entre las dos condicionales. Después del periodo inicial, las extracciones se distribuyen según la posterior conjunta. Son exactamente las dos etapas del algoritmo de la @sec-bvar-gibbs con una sola variable: $\\Sigma^{-1} \\otimes X'X$ se vuelve $\\sigma^{-2}X'X$ y la inversa-Wishart se vuelve una inversa-gamma.\n\nPara ver el algoritmo en acción conviene un caso en que se conoce la respuesta: 80 observaciones simuladas de un AR(1) con $c = 0.5$, $\\phi = 0.9$ y $\\sigma = 1$, las mismas del bootstrap de la [sección 0.11](00-preliminares.qmd#sec-prelim-simulacion). El prior para $\\phi$ se centra en uno con desvío 0.2, que es la idea del prior de Minnesota de la @sec-bvar-minnesota: a falta de evidencia en contra, una serie macroeconómica se parece a una caminata aleatoria. El de la constante es difuso.\n\n::: {#univariado-gibbs .cell execution_count=8}\n``` {.python .cell-code}\nimport numpy as np\nfrom scipy import stats\n\n\ndef simulate_ar1(c, phi, sigma, T, seed=None):\n    \"\"\"Simulate an AR(1) starting at its unconditional mean.\"\"\"\n    rng = np.random.default_rng(seed)\n    y = np.empty(T)\n    y[0] = c / (1 - phi)\n    for t in range(1, T):\n        shock = sigma * rng.standard_normal()\n        y[t] = c + phi * y[t - 1] + shock\n    return y\n\n\ny = simulate_ar1(0.5, 0.9, 1.0, T=80, seed=6)\nX = np.column_stack([np.ones(len(y) - 1), y[:-1]])\nY = y[1:]\nb_ols = np.linalg.solve(X.T @ X, X.T @ Y)\n\nbeta0 = np.array([0.0, 1.0])\nV0_inv = np.diag([1 / 10.0, 1 / 0.2**2])\na0, d0 = 2.0, 1.0\n\nrng = np.random.default_rng(9)\nsigma2, keep = 1.0, []\nfor step in range(6000):\n    V = np.linalg.inv(V0_inv + X.T @ X / sigma2)\n    mean = V @ (V0_inv @ beta0 + X.T @ Y / sigma2)\n    beta = rng.multivariate_normal(mean, V)\n    e = Y - X @ beta\n    sigma2 = stats.invgamma.rvs(a0 + len(Y) / 2,\n                                scale=d0 + e @ e / 2,\n                                random_state=rng)\n    keep.append([beta[0], beta[1], sigma2])\n\ndraws = np.array(keep)[1000:]            # discard burn-in\nphi_draws = draws[:, 1]\nprint(f\"media posterior de phi: {phi_draws.mean():.3f} \"\n      f\"(MCO {b_ols[1]:.3f})\")\nprint(\"intervalo al 68 %:\",\n      np.round(np.quantile(phi_draws, [0.16, 0.84]), 3))\nprint(\"intervalo al 95 %:\",\n      np.round(np.quantile(phi_draws, [0.025, 0.975]), 3))\nprint(f\"P(phi >= 1 | y) = {(phi_draws >= 1).mean():.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nmedia posterior de phi: 0.877 (MCO 0.863)\nintervalo al 68 %: [0.816 0.937]\nintervalo al 95 %: [0.761 0.995]\nP(phi >= 1 | y) = 0.022\n```\n:::\n:::\n\n\n::: {.cell execution_count=9}\n``` {.python .cell-code}\nimport matplotlib.pyplot as plt\n\nfrom macrobook import use_style, figsize, charts\n\nuse_style()\n\nall_phi = np.array(keep)[:, 1]\ngrid = np.linspace(0.4, 1.4, 300)\n\nfig, axes = plt.subplots(1, 2, figsize=figsize(0.38))\ncharts.trace(axes[0], all_phi, burn=1000)\naxes[0].set_title(\"cadena de φ\", fontsize=8.5)\naxes[0].set_xlabel(\"iteración\")\nprior_pdf = stats.norm(1, 0.2).pdf(grid)\ncharts.prior_posterior(axes[1], phi_draws,\n                       prior_density=prior_pdf,\n                       grid=grid, ols_value=b_ols[1])\naxes[1].set_xlim(0.4, 1.4)\naxes[1].set_yticks([])\naxes[1].set_title(\"posterior de φ\", fontsize=8.5)\ncharts.legend_outside(axes[1], ncol=3)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Muestreador de Gibbs del AR(1). Izquierda: la cadena de $\\phi$, con el periodo inicial descartado sombreado. Derecha: la posterior de $\\phi$, la densidad del prior y la estimación de mínimos cuadrados.](02-univariate_files/figure-pdf/fig-univariado-gibbs-output-1.pdf){#fig-univariado-gibbs fig-pos='H'}\n:::\n:::\n\n\nLa media posterior de $\\phi$, 0.877, queda entre el prior y la estimación de mínimos cuadrados, 0.863, mucho más cerca de esta porque 79 observaciones informan más que un prior con desvío 0.2. Y la posterior responde una pregunta que el estimador clásico no puede responder directamente: la probabilidad de que el proceso tenga una raíz unitaria o sea explosivo, $P(\\phi \\geq 1 \\mid y)$, que aquí es de 2 %. La @sec-bvar-gibbs descarta esas extracciones cuando necesita respuestas al impulso bien definidas; aquí se reportan, porque son información.\n\n::: {.intuicion}\nEl muestreador de Gibbs cambia un problema difícil, extraer de una distribución conjunta sin forma conocida, por una sucesión de problemas fáciles, extraer de cada condicional sabiendo el resto. Funciona siempre que cada condicional se pueda muestrear, y esa es la razón por la que los priors conjugados, normal para los coeficientes e inversa-gamma o inversa-Wishart para las varianzas, dominan la macroeconometría bayesiana aplicada.\n:::\n\nEl @sec-bayes trata lo que queda fuera de esta sección: el algoritmo de Metropolis-Hastings, el diagnóstico de convergencia de las cadenas y la elección de los priors.\n\n\n## Raíces unitarias {#sec-univariado-raices}\n\nEl caso límite de la persistencia es la **caminata aleatoria**, $y_t = y_{t-1} + \\varepsilon_t$, un AR(1) con $\\phi = 1$ cuya raíz está exactamente en el círculo unitario. Tres propiedades la separan de un AR estable. Su varianza crece con el tiempo, $\\operatorname{Var}(y_t \\mid y_0) = t\\sigma^2$, de modo que no tiene media ni varianza incondicionales. Sus pesos de Wold son todos iguales a uno: cada choque es permanente. Y su mejor pronóstico, a cualquier horizonte, es el último dato. La serie en diferencias, $\\Delta y_t = \\varepsilon_t$, sí es estacionaria, y por eso se dice que la caminata es integrada de orden uno, I(1).\n\nLas tres propiedades vuelven más adelante. El prior de Minnesota de la @sec-bvar-minnesota centra cada ecuación de un VAR en una caminata aleatoria, porque las series macroeconómicas en niveles suelen comportarse casi como una. Y el último dato es el pronóstico contra el que se compara cualquier modelo (@sec-univariado-pronostico).\n\nPara el PBI, la pregunta tiene contenido económico. Si el logaritmo del PBI es **estacionario alrededor de una tendencia**, una recesión es una desviación transitoria y la economía vuelve a su senda; si tiene una **raíz unitaria**, parte de la caída es permanente. @nelson1982 encontraron que la mayoría de las series macroeconómicas de Estados Unidos no permiten rechazar la raíz unitaria, y el @sec-tendencias muestra cuánto depende de esa elección la medición del ciclo.\n\nLa prueba estándar es la de Dickey y Fuller aumentada (ADF). Se estima\n\n$$ \\Delta y_t = \\alpha + \\delta t + \\gamma\\, y_{t-1} + \\sum_{i=1}^{k} \\beta_i\\, \\Delta y_{t-i} + \\varepsilon_t $$ {#eq-univariado-adf}\n\ny se contrasta $H_0: \\gamma = 0$ (raíz unitaria) contra $\\gamma < 0$ (estacionaria). Los rezagos de $\\Delta y_t$ absorben la autocorrelación restante, y la tendencia $\\delta t$ se incluye cuando la alternativa es la estacionariedad alrededor de una tendencia. Bajo la hipótesis nula el estadístico $t$ de $\\gamma$ no tiene distribución normal sino la de @dickey1979, con valores críticos más negativos: al 5 %, cerca de $-2.87$ con constante y $-3.43$ con constante y tendencia.\n\n::: {#tbl-univariado-adf .cell tbl-cap='Pruebas ADF, 1960T1-2019T4. Los rezagos de la regresión los elige el AIC; el valor p es el de MacKinnon.' execution_count=10}\n``` {.python .cell-code}\nfrom statsmodels.tsa.stattools import adfuller\n\nlog_gdp = np.log(gdp[\"1960\":\"2019\"])\ntests = [(\"log PBI\", log_gdp, \"ct\"),\n         (\"inflación\", infl, \"c\"),\n         (\"crecimiento\", growth, \"c\")]\nterms = {\"ct\": \"constante y tendencia\", \"c\": \"constante\"}\nrows = []\nfor name, x, regression in tests:\n    stat, pvalue, k, *_ = adfuller(x, regression=regression,\n                                   autolag=\"AIC\")\n    rows.append({\"serie\": name, \"términos\": terms[regression],\n                 \"estadístico\": round(stat, 2),\n                 \"valor p\": round(pvalue, 3), \"rezagos\": k})\npd.DataFrame(rows).set_index(\"serie\")\n```\n\n::: {.cell-output .cell-output-display execution_count=10}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>términos</th>\n      <th>estadístico</th>\n      <th>valor p</th>\n      <th>rezagos</th>\n    </tr>\n    <tr>\n      <th>serie</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>log PBI</th>\n      <td>constante y tendencia</td>\n      <td>-2.39</td>\n      <td>0.385</td>\n      <td>2</td>\n    </tr>\n    <tr>\n      <th>inflación</th>\n      <td>constante</td>\n      <td>-2.82</td>\n      <td>0.055</td>\n      <td>2</td>\n    </tr>\n    <tr>\n      <th>crecimiento</th>\n      <td>constante</td>\n      <td>-7.36</td>\n      <td>0.000</td>\n      <td>1</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nSegún la @tbl-univariado-adf, el logaritmo del PBI no permite rechazar la raíz unitaria, el crecimiento la rechaza con holgura, y la inflación queda al borde del 5 %. Ese último resultado es el típico, y para interpretarlo hay que saber cuánto puede ver la prueba. La @fig-univariado-potencia simula series AR(1) estacionarias con distintos valores de $\\phi$ y cuenta en qué fracción de los casos la prueba rechaza correctamente la raíz unitaria.\n\n::: {.cell execution_count=11}\n``` {.python .cell-code}\nfrom statsmodels.tsa.adfvalues import mackinnoncrit\n\n\ndef df_stat(paths):\n    \"\"\"Dickey-Fuller t statistic (constant, no lags), by row.\"\"\"\n    dy, lag = np.diff(paths, axis=1), paths[:, :-1]\n    out = np.empty(len(paths))\n    for r in range(len(paths)):\n        X = np.column_stack([np.ones(lag.shape[1]), lag[r]])\n        b, ssr, *_ = np.linalg.lstsq(X, dy[r], rcond=None)\n        s2 = ssr[0] / (len(dy[r]) - 2)\n        se = np.sqrt(s2 * np.linalg.inv(X.T @ X)[1, 1])\n        out[r] = b[1] / se\n    return out\n\n\ndef simulate_ar1_paths(phi, T, reps, rng, burn=100):\n    e = rng.standard_normal((reps, T + burn))\n    y = np.zeros_like(e)\n    for t in range(1, T + burn):\n        y[:, t] = phi * y[:, t - 1] + e[:, t]\n    return y[:, burn:]\n\n\nrng = np.random.default_rng(12)\nphis = np.round(np.arange(0.80, 1.001, 0.01), 2)\npower = {}\nfor T in (80, 240):\n    critical = mackinnoncrit(N=1, regression=\"c\", nobs=T)[1]\n    power[T] = [(df_stat(simulate_ar1_paths(f, T, 1000, rng))\n                 < critical).mean() for f in phis]\n\nfig, ax = plt.subplots(figsize=figsize(0.40))\nfor k, T in enumerate(power):\n    ax.plot(phis, power[T], color=PALETTE[\"shocks\"][k],\n            ls=PALETTE[\"shock_linestyle\"][k], lw=1.3,\n            label=f\"T = {T} ({T // 4} años)\")\nax.axhline(0.05, color=PALETTE[\"muted\"], lw=0.8, ls=(0, (2, 2)))\nax.set_xlabel(\"$\\\\phi$ verdadero\")\nax.set_ylabel(\"rechazos de $H_0$\")\ncharts.legend_outside(ax, ncol=2)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Potencia de la prueba de Dickey-Fuller al 5 % (con constante): fracción de series AR(1) estacionarias en las que se rechaza la raíz unitaria, con 1000 simulaciones por punto. Con 60 años de datos trimestrales, una serie con $\\phi = 0.95$ se confunde con una caminata aleatoria alrededor de la mitad de las veces.](02-univariate_files/figure-pdf/fig-univariado-potencia-output-1.pdf){#fig-univariado-potencia fig-pos='H'}\n:::\n:::\n\n\n\nCon 240 trimestres, una serie con $\\phi = 0.95$ se detecta como estacionaria sólo en 44 % de los casos, y una con $\\phi = 0.98$ en 11 %; con 20 años de datos, incluso $\\phi = 0.9$ se detecta en apenas 23 %. Una prueba con tan poca potencia no puede cargar sola con la decisión.\n\n::: {.cuidado}\nNo rechazar la raíz unitaria no prueba que exista: cerca de uno, la prueba casi no distingue entre una memoria larga y una infinita. La decisión de diferenciar es, en parte, económica. La inflación bajo una meta creíble no debería tener raíz unitaria aunque la prueba no lo confirme, y el nivel de precios sí la tiene aunque se estime en niveles. El @sec-var estima en niveles y explica por qué (@sec-var-otros).\n:::\n\n## Pronóstico {#sec-univariado-pronostico}\n\nBajo pérdida cuadrática, el mejor pronóstico es la esperanza condicional, y en un AR($p$) se obtiene iterando el modelo con los choques futuros en cero, que es iterar la forma companion. La @eq-univariado-wold da el error: el pronóstico a $h$ periodos se equivoca por los choques que todavía no llegaron,\n\n$$ y_{T+h} - \\hat{y}_{T+h|T} = \\sum_{j=0}^{h-1} \\psi_j\\, \\varepsilon_{T+h-j}, \\qquad \\operatorname{ECM}_h = \\sigma^2 \\sum_{j=0}^{h-1} \\psi_j^2 . $$ {#eq-univariado-ecm}\n\nA medida que $h$ crece, el pronóstico converge a la media $\\mu$ y el error cuadrático medio a la varianza incondicional $\\gamma_0$: a horizontes largos, un modelo estable no sabe nada más que el promedio. Es el @alg-pronostico del @sec-var con una sola variable, y la misma función lo calcula.\n\nLa @fig-univariado-pronostico pone a prueba el modelo de inflación con un caso difícil: el pronóstico hecho a fines de 2019 para los cuatro años siguientes.\n\n::: {.cell execution_count=13}\n``` {.python .cell-code}\nfit = fits[\"inflación\"]\ny_in = infl.to_numpy().reshape(-1, 1)\nh = 16\npath, variance = var.forecast(y_in, fit[\"B\"], fit[\"Sigma\"],\n                              fit[\"p\"], h)\npath, sd = path[:, 0], np.sqrt(variance[:, 0])\nrealized = infl_all[\"2020Q1\":\"2023Q4\"]\noutside = (np.abs(realized.to_numpy() - path) > 1.96 * sd)\nmu_infl = var.unconditional_mean(fit[\"B\"], 1, fit[\"p\"])[0]\n\nhist = infl[\"2014\":]\nhist_dates = hist.index.to_timestamp(how=\"end\")\nfc_dates = realized.index.to_timestamp(how=\"end\")\nedge = np.r_[hist_dates[-1:], fc_dates]\nlast = y_in[-1, 0]\nbands = [(np.r_[last, path - 1.96 * sd],\n          np.r_[last, path + 1.96 * sd])]\n\nfig, ax = plt.subplots(figsize=figsize(0.42))\ncharts.fan_chart(ax, hist_dates, hist, edge, bands,\n                 np.r_[last, path], realized=realized,\n                 dates_realized=fc_dates,\n                 band_labels=[\"IC 95 %\"])\nax.axhline(mu_infl, color=PALETTE[\"accent\"], lw=0.9,\n           ls=(0, (1, 2)))\nax.set_ylabel(\"%\")\ncharts.legend_outside(ax, ncol=4)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Inflación PCE: pronóstico del AR(3) estimado con datos hasta 2019T4, con intervalo al 95 %, y los datos observados de 2020 a 2023, que no entraron en la estimación. La línea punteada es la media del modelo.](02-univariate_files/figure-pdf/fig-univariado-pronostico-output-1.pdf){#fig-univariado-pronostico fig-pos='H'}\n:::\n:::\n\n\n\nEl pronóstico sube lentamente de 1\\.9 % a 2\\.7 %, atraído por la media del modelo, 3\\.2 %, que promedia los años setenta con las décadas de inflación baja. La inflación real hizo algo que el modelo consideraba muy improbable: 4 de los 16 trimestres quedaron fuera del intervalo (2020T2\\, 2021T4\\, 2022T1\\, 2022T2), y en 2022T1 llegó a 7\\.5 %, por encima del límite superior de 6\\.8 %. El intervalo no es malo por construcción: supone que los coeficientes y la varianza de 1960-2019 siguen vigentes, y ese supuesto es el que fallaron la pandemia y el alza de precios que siguió. Los modelos con volatilidad y parámetros cambiantes de los capítulos [-@sec-volatilidad] y [-@sec-tvp] existen para relajarlo.\n\n### La caminata aleatoria como rival\n\nUn pronóstico sólo es bueno en comparación con otro. El rival natural es la caminata aleatoria, que pronostica el último dato a cualquier horizonte, y para la inflación una variante más fuerte: el promedio de los últimos cuatro trimestres, con el que @atkeson2001 mostraron que casi ningún modelo de la curva de Phillips mejoraba el pronóstico de la inflación de Estados Unidos. Para el crecimiento, cuya memoria es corta, el rival sensato es la media histórica.\n\nLa comparación honesta es **pseudo fuera de muestra**: en cada trimestre desde 1985 se reestima el modelo sólo con los datos disponibles hasta ese momento, se pronostica, y se guarda el error. La @tbl-univariado-evaluacion reporta la raíz del error cuadrático medio (RECM) de cada pronóstico dividida por la de la caminata aleatoria.\n\n::: {#tbl-univariado-evaluacion .cell tbl-cap='RECM pseudo fuera de muestra, 1985-2019, relativa a la de la caminata aleatoria, por horizonte en trimestres. Un valor menor que uno significa que el pronóstico le gana a la caminata.' execution_count=15}\n``` {.python .cell-code}\ndef evaluate(x, p, start=\"1985Q1\", horizons=(1, 4, 8)):\n    \"\"\"Recursive pseudo out-of-sample RMSE relative to RW.\"\"\"\n    values = x.to_numpy()\n    first = x.index.get_loc(pd.Period(start, \"Q\"))\n    errors = {h: {\"AR\": [], \"prom. 4 trim.\": [], \"media\": [],\n                  \"caminata\": []} for h in horizons}\n    for t in range(first - 1, len(values) - 1):\n        y = values[:t + 1].reshape(-1, 1)\n        fit = var.ols(y, p)\n        path, _ = var.forecast(y, fit[\"B\"], fit[\"Sigma\"], p,\n                               max(horizons))\n        for h in horizons:\n            if t + h >= len(values):\n                continue\n            actual = values[t + h]\n            errors[h][\"AR\"].append(actual - path[h - 1, 0])\n            errors[h][\"prom. 4 trim.\"].append(\n                actual - y[-4:, 0].mean())\n            errors[h][\"media\"].append(actual - y[:, 0].mean())\n            errors[h][\"caminata\"].append(actual - y[-1, 0])\n    table = {}\n    for h in horizons:\n        rmse = {k: np.sqrt(np.mean(np.square(v)))\n                for k, v in errors[h].items()}\n        table[f\"h = {h}\"] = {k: rmse[k] / rmse[\"caminata\"]\n                             for k in rmse if k != \"caminata\"}\n    return pd.DataFrame(table)\n\n\nratios = pd.concat({name: evaluate(x, orders[name])\n                    for name, x in series.items()})\nratios.round(2)\n```\n\n::: {.cell-output .cell-output-display execution_count=15}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th></th>\n      <th>h = 1</th>\n      <th>h = 4</th>\n      <th>h = 8</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th rowspan=\"3\" valign=\"top\">crecimiento</th>\n      <th>AR</th>\n      <td>0.82</td>\n      <td>0.78</td>\n      <td>0.73</td>\n    </tr>\n    <tr>\n      <th>prom. 4 trim.</th>\n      <td>0.89</td>\n      <td>0.87</td>\n      <td>0.83</td>\n    </tr>\n    <tr>\n      <th>media</th>\n      <td>0.92</td>\n      <td>0.79</td>\n      <td>0.73</td>\n    </tr>\n    <tr>\n      <th rowspan=\"3\" valign=\"top\">inflación</th>\n      <th>AR</th>\n      <td>0.90</td>\n      <td>0.85</td>\n      <td>0.89</td>\n    </tr>\n    <tr>\n      <th>prom. 4 trim.</th>\n      <td>0.94</td>\n      <td>0.78</td>\n      <td>0.84</td>\n    </tr>\n    <tr>\n      <th>media</th>\n      <td>1.37</td>\n      <td>1.12</td>\n      <td>1.13</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n\nLas dos series cuentan historias distintas. En el crecimiento, el AR le gana con holgura a la caminata aleatoria (0\\.82 a un trimestre, 0\\.73 a ocho), pero a dos años empata con la media histórica (0\\.73): cuando la memoria es corta, pronosticar consiste sobre todo en volver al promedio. En la inflación, el AR mejora a la caminata en apenas 10 % a un trimestre (0\\.90), y a un año el promedio de cuatro trimestres le gana al AR (0\\.78 contra 0\\.85), mientras que la media histórica es peor que la caminata (1\\.12). Es el resultado de @atkeson2001, y @stockwatson2007 lo explicaron: desde mediados de los ochenta, la inflación de Estados Unidos se parece a un componente permanente que se mueve lentamente más un ruido transitorio, y para esa estructura un promedio de los datos recientes es casi el pronóstico óptimo.\n\n::: {.intuicion}\nEl rival a vencer depende de la memoria de la serie. Si es corta, el rival es la media; si es muy larga, el último dato. Un modelo que no le gana al rival correcto no está aportando información, y todo modelo de pronóstico del libro se evalúa así. El @sec-pronostico formaliza la comparación, con pruebas para decidir si una diferencia de RECM es estadísticamente distinta de cero.\n:::\n\n## Otros temas {#sec-univariado-otros}\n\n### Diagnóstico de residuos\n\n\nSi el modelo capturó toda la memoria, los residuos no deberían estar autocorrelacionados. La prueba de Ljung y Box acumula las autocorrelaciones residuales al cuadrado hasta un rezago $m$ y las compara con una $\\chi^2$; ante autocorrelación, lo primero es agregar rezagos. Los residuos de ambos modelos pasan la prueba a ocho rezagos (valores p de 0\\.23 y 0\\.14). La heterocedasticidad condicional, varianza que cambia con el tiempo, es otra cosa: se detecta con la prueba ARCH de @engle1982 y se modela en el @sec-volatilidad.\n\n\n### Parámetros que cambian\n\n\nTodo el capítulo supone que los coeficientes son los mismos en toda la muestra, y en la inflación no lo son. La suma de coeficientes del AR(3) es 0\\.92 entre 1960 y 1983 y 0\\.54 entre 1984 y 2019: la inflación perdió buena parte de su memoria cuando la política monetaria cambió. Si esa caída es un quiebre, una deriva gradual o un efecto de la menor volatilidad de los choques es una pregunta abierta [@cogley2005], y es el tema del @sec-tvp.\n\n### Identificación de Box y Jenkins\n\nLa metodología de @boxjenkins1970 elige el orden de un ARMA mirando la función de autocorrelación y la autocorrelación parcial: un AR($p$) tiene autocorrelación parcial nula después de $p$, un MA($q$) tiene autocorrelación nula después de $q$. Fue el método estándar antes de que los criterios de información se volvieran baratos de calcular, y sigue siendo útil como diagnóstico visual.\n\n## Ideas clave {.unnumbered}\n\n::: {.ideas-clave}\n1. La memoria de una serie se lee en su autocorrelación y en las raíces de su polinomio de rezagos. En Estados Unidos, la del crecimiento del PBI dura pocos trimestres; la de la inflación, años.\n2. Un AR($p$) es un VAR con una variable. Su forma companion, su condición de estabilidad (valores propios dentro del círculo unitario) y sus pesos de Wold son los mismos objetos que el @sec-var usa con matrices.\n3. Los pesos de Wold son a la vez la respuesta al impulso y el ingrediente del error de pronóstico; su suma, $1/(1-\\rho)$, es el efecto de largo plazo de un choque.\n4. Mínimos cuadrados es máxima verosimilitud condicional y subestima la persistencia en muestras cortas. Su varianza residual es un insumo del prior de Minnesota.\n5. Las pruebas de raíz unitaria tienen poca potencia cerca de uno: no rechazar no prueba una raíz unitaria, y la decisión de diferenciar es en parte económica.\n6. La caminata aleatoria, o el promedio de los últimos trimestres, es muy difícil de batir para la inflación. Todo modelo de pronóstico debe compararse contra el rival que corresponde a la memoria de la serie.\n:::\n\n## Lecturas recomendadas {.unnumbered}\n\n::: {.lecturas}\nHamilton (1994), caps. 3-5 y 17\n:   el tratamiento de referencia de los procesos ARMA, de su estimación y de las raíces unitarias.\n\nBox y Jenkins (1970)\n:   la metodología original de identificación, estimación y diagnóstico.\n\nDickey y Fuller (1979)\n:   la distribución del estimador bajo raíz unitaria.\n\nAtkeson y Ohanian (2001); Stock y Watson (2007)\n:   por qué la inflación de Estados Unidos es tan difícil de pronosticar mejor que con un promedio de los datos recientes.\n\nGelman et al. (2013)\n:   [*Bayesian Data Analysis*](https://sites.stat.columbia.edu/gelman/book/), gratuito en línea; el tratamiento de referencia de la inferencia bayesiana y del muestreo de Gibbs.\n:::\n\n## Ejercicios {.unnumbered}\n\n::: {#exr-univariado-1}\nRepita la evaluación de la @sec-univariado-pronostico con ventanas móviles de 20 años en lugar de recursivas. ¿Mejora el AR frente al promedio de cuatro trimestres? Relacione el resultado con la caída de la persistencia después de 1984.\n:::\n\n::: {#exr-univariado-2}\nSimule 500 series de un AR(1) con coeficiente 0.95 y $T = 80$. ¿En qué fracción de los casos rechaza la prueba ADF la raíz unitaria? Repita con $T = 400$ y compare con la @fig-univariado-potencia.\n:::\n\n::: {#exr-univariado-3}\nRepita el muestreador de Gibbs de la @sec-univariado-bayes con un prior para $\\phi$ centrado en cero con desvío 0.5. Compare la media posterior con la del texto y relacione la diferencia con el papel de $\\delta_i$ y $\\lambda_1$ en el prior de Minnesota.\n:::\n\n::: {.solucion}\nCon el prior centrado en cero la media posterior de $\\phi$ queda por debajo de la estimación de mínimos cuadrados, porque el prior empuja hacia la ausencia de persistencia; con el prior centrado en uno queda por encima. La media del prior es el papel de $\\delta_i$, que fija hacia qué valor se encoge el primer rezago propio, y el desvío es el de $\\lambda_1$, que fija con cuánta fuerza. Con las 79 observaciones del texto la media posterior pasa de 0.877 a 0.852, una diferencia de dos centésimas y media; con sólo las primeras 30 la diferencia supera las ocho centésimas, porque el prior pesa más cuando los datos informan menos.\n:::\n\n::: {#exr-univariado-4}\nElija $\\phi_1$ y $\\phi_2$ para que el AR(2) tenga raíces complejas con módulo 0.9 (pista: los valores propios de $F$ son $0.9\\,e^{\\pm i\\theta}$, de modo que $\\phi_1 = 1.8\\cos\\theta$ y $\\phi_2 = -0.81$). Grafique $\\psi_j$ para $\\theta = \\pi/10$ y compruebe que la respuesta oscila con un periodo de $2\\pi/\\theta = 20$ trimestres, el largo típico de un ciclo económico.\n:::\n\n::: {#exr-univariado-5}\nAplique la prueba ADF a la inflación por separado en 1960-1983 y en 1984-2019. ¿Cambia la conclusión? Discuta si una prueba con la potencia de la @fig-univariado-potencia puede distinguir entre las dos submuestras.\n:::\n\n",
    "supporting": [
      "02-univariate_files/figure-pdf"
    ],
    "filters": []
  }
}