{
  "hash": "394def4158b1efdf69d9d449bca8e527",
  "result": {
    "engine": "jupyter",
    "markdown": "# Vectores autorregresivos {#sec-var}\n\n::: {.pregunta}\n¿Cómo se mueven juntas varias series macroeconómicas cuando no queremos comprometernos con una teoría completa de la economía?\n:::\n\n::: {.aprendizajes}\n1. Escribir el mismo VAR de tres maneras (ecuación por ecuación, compacta y companion) y saber para qué sirve cada una.\n2. Estimarlo por mínimos cuadrados, verificar su estabilidad y pronosticar con la forma companion.\n3. Entender por qué los residuos de la forma reducida no son choques económicos.\n:::\n\n**Requisitos previos.** @sec-univariado; álgebra matricial (inversa, valores propios, matrices particionadas); distribución normal multivariada.\n\n::: {.datos-usados}\n| Serie | Fuente | Frecuencia | Transformación |\n|:-------------------------------|:--------|:-----------|:--------------------------|\n| Inflación ($\\pi_t$) | BCRP | trimestral | var. % interanual del IPC |\n| Tasa de referencia ($r_t$) | BCRP | trimestral | nivel, % anual |\n\nEl archivo crudo es `data/raw/database_peru.xlsx` (hoja `domestic`) y el CSV que leen los capítulos lo construye `code/python/build_peru_data.py`. El VAR se estima entre 2003Q4 y 2017Q4, y los ocho trimestres siguientes (2018-2019) quedan fuera de la muestra para evaluar el pronóstico.\n:::\n\n## Qué hace un VAR {#sec-var-que-hace}\n\nEn su revisión de 2001, Stock y Watson describen el trabajo del macroeconometrista en cuatro tareas: describir y resumir series macroeconómicas, pronosticar, recuperar la estructura de la economía a partir de los datos y asesorar a quien decide la política. El VAR es la herramienta estadística que sostiene las cuatro.\n\nTomemos dos variables, la inflación ($\\pi_t$) y la tasa de interés de política ($r_t$). Un VAR ayuda a responder:\n\n- ¿Cómo es el comportamiento dinámico de estas variables y cómo interactúan entre sí?\n- ¿Qué inflación es consistente con la trayectoria de tasas de los próximos trimestres?\n- ¿Cuál es el efecto de un choque de política monetaria sobre la inflación?\n- ¿Cuánto aportaron históricamente los choques de política a las fluctuaciones de la inflación?\n\nLas dos primeras se responden con el modelo de forma reducida de este capítulo. Las dos últimas exigen una hipótesis de identificación y son el asunto del @sec-svar. La @fig-mapa ordena el recorrido.\n\n::: {#cell-fig-mapa .cell execution_count=1}\n\n::: {.cell-output .cell-output-display}\n![Del modelo a las preguntas. La forma reducida (este capítulo) alcanza para describir y pronosticar; las preguntas causales exigen identificar los choques.](03-var_files/figure-html/fig-mapa-output-1.svg){#fig-mapa}\n:::\n:::\n\n\n::: {.intuicion}\nUn VAR es una regresión de cada variable sobre el pasado de todas. No hay teoría dentro: la teoría entra al elegir qué variables incluir, en qué transformación, con cuántos rezagos y, sobre todo, al identificar los choques.\n:::\n\n## El VAR(p) ecuación por ecuación {#sec-var-ecuaciones}\n\n::: {#def-var}\n## VAR(p) de forma reducida\n\nSea $\\mathbf{y}_t$ un vector $n \\times 1$ de variables observadas. El VAR de orden $p$ es\n\n$$\n\\mathbf{y}_t = c + \\Phi_1 \\mathbf{y}_{t-1} + \\Phi_2 \\mathbf{y}_{t-2} + \\cdots + \\Phi_p \\mathbf{y}_{t-p} + \\mathbf{u}_t,\n\\qquad \\mathbf{u}_t \\sim N(0, \\Sigma),\n$$ {#eq-var-p}\n\ndonde $c$ es $n \\times 1$, cada $\\Phi_\\ell$ es $n \\times n$, $\\mathbb{E}[\\mathbf{u}_t] = 0$ y $\\mathbb{E}[\\mathbf{u}_t \\mathbf{u}_s'] = 0$ para $t \\neq s$.\n:::\n\nCon dos variables y dos rezagos, la @eq-var-p es un sistema de dos ecuaciones:\n\n$$\n\\begin{bmatrix} \\pi_t \\\\ r_t \\end{bmatrix}\n= \\begin{bmatrix} c_1 \\\\ c_2 \\end{bmatrix}\n+ \\begin{bmatrix} \\phi^1_{11} & \\phi^1_{12} \\\\ \\phi^1_{21} & \\phi^1_{22} \\end{bmatrix}\n  \\begin{bmatrix} \\pi_{t-1} \\\\ r_{t-1} \\end{bmatrix}\n+ \\begin{bmatrix} \\phi^2_{11} & \\phi^2_{12} \\\\ \\phi^2_{21} & \\phi^2_{22} \\end{bmatrix}\n  \\begin{bmatrix} \\pi_{t-2} \\\\ r_{t-2} \\end{bmatrix}\n+ \\begin{bmatrix} u_{1t} \\\\ u_{2t} \\end{bmatrix}.\n$$ {#eq-var-bivariado}\n\nDos detalles que conviene fijar desde el inicio. Primero, $\\mathbf{u}_t$ no tiene autocorrelación pero sí correlación contemporánea: $\\Sigma$ no es diagonal, y por eso no se puede mover $u_{2t}$ dejando fijo $u_{1t}$. A eso vuelve la @sec-var-sigma. Segundo, todas las ecuaciones tienen exactamente los mismos regresores, y de ahí saldrá el resultado de estimación de la @sec-var-mco.\n\nEl conteo de parámetros crece con el cuadrado del número de variables. Cada ecuación tiene $k = np + 1$ coeficientes y el sistema tiene $nk$:\n\n| Variables ($n$) | Rezagos ($p$) | Coeficientes por ecuación | Total |\n|:---|:---|:---|:---|\n| 2 | 2 | 5 | 10 |\n| 3 | 4 | 13 | 39 |\n| 5 | 4 | 21 | 105 |\n| 7 | 4 | 29 | 203 |\n\n: Conteo de parámetros de un VAR sin restricciones {#tbl-conteo}\n\nLa muestra trimestral de este capítulo tiene 57 observaciones para los diez coeficientes del caso más pequeño de la @tbl-conteo. Con cinco variables y cuatro rezagos harían falta 105, más de los datos disponibles en casi cualquier economía. Por eso existe el @sec-bvar.\n\n## La forma compacta {#sec-var-compacta}\n\nPara estimar conviene apilar las $T$ observaciones. Con $p = 2$ y las dos variables de la @eq-var-bivariado:\n\n$$\n\\underbrace{\\begin{bmatrix} \\pi_1 & r_1 \\\\ \\pi_2 & r_2 \\\\ \\vdots & \\vdots \\\\ \\pi_T & r_T \\end{bmatrix}}_{Y\\ (T \\times n)}\n=\n\\underbrace{\\begin{bmatrix}\n 1 & \\pi_0 & r_0 & \\pi_{-1} & r_{-1} \\\\\n 1 & \\pi_1 & r_1 & \\pi_0 & r_0 \\\\\n \\vdots & \\vdots & \\vdots & \\vdots & \\vdots \\\\\n 1 & \\pi_{T-1} & r_{T-1} & \\pi_{T-2} & r_{T-2}\n\\end{bmatrix}}_{X\\ (T \\times k)}\n\\underbrace{\\begin{bmatrix}\n c_1 & c_2 \\\\\n \\phi^1_{11} & \\phi^1_{21} \\\\ \\phi^1_{12} & \\phi^1_{22} \\\\\n \\phi^2_{11} & \\phi^2_{21} \\\\ \\phi^2_{12} & \\phi^2_{22}\n\\end{bmatrix}}_{B\\ (k \\times n)}\n+\n\\underbrace{\\begin{bmatrix} u_{11} & u_{21} \\\\ u_{12} & u_{22} \\\\ \\vdots & \\vdots \\\\ u_{1T} & u_{2T} \\end{bmatrix}}_{U\\ (T \\times n)},\n$$ {#eq-var-compacta-detalle}\n\nes decir\n\n$$ Y = XB + U. $$ {#eq-var-compacta}\n\nLa columna $j$ de $B$ contiene los coeficientes de la ecuación $j$, la primera fila es el intercepto y la matriz $X$ es la misma para todas.\n\n::: {.cuidado}\nEl lugar de la constante es una convención, no un resultado. En el libro va primero, como en las pizarras y en Blake y Mumtaz; `MacroPy` la pone al final, después de todos los rezagos. Si se mezclan las dos convenciones, el prior del @sec-bvar termina encogiendo el intercepto en lugar del primer rezago. Conviene imprimir una fila de $B$ y verificar el orden antes de seguir.\n:::\n\n## Los datos: inflación y tasa de referencia {#sec-var-datos}\n\nEl resto del capítulo trabaja con dos series trimestrales del Perú: la inflación interanual y la tasa de referencia del BCRP. La muestra de estimación va de 2003Q4 a 2017Q4, y los dos años siguientes se reservan para evaluar el pronóstico.\n\nLas dos fechas de corte son decisiones sustantivas, no detalles técnicos. El inicio viene impuesto por los datos: el BCRP adopta las metas explícitas de inflación en 2002 y publica la tasa de referencia recién desde septiembre de 2003, de modo que antes de esa fecha no hay un instrumento de política observado que poner en el sistema. El final deja fuera la pandemia y el episodio inflacionario posterior, dos movimientos de una magnitud que un VAR lineal con innovaciones gaussianas no describe bien: incluirlos haría que unos pocos trimestres determinaran los coeficientes. El costo de ambos recortes es una muestra de 57 observaciones para 10 parámetros, que es exactamente la tensión que motiva el @sec-bvar.\n\n::: {#cell-setup .cell execution_count=2}\n``` {.python .cell-code}\nimport numpy as np\nimport pandas as pd\n\nfrom macrobook import data_path, var\n\ncsv = data_path(\"peru_domestic.csv\")\ndata = pd.read_csv(csv, index_col=\"date\")\ndata.index = pd.PeriodIndex(data.index, freq=\"Q\")\n\nseries = [\"inf\", \"mpr\"]\nsample = data.loc[\"2003Q4\":\"2017Q4\", series]   # estimación\nfuture = data.loc[\"2018Q1\":\"2019Q4\", series]   # evaluación\ndates = sample.index.to_timestamp(how=\"end\")\ny = sample.to_numpy()\nn, p = y.shape[1], 2\n\nspan = f\"{sample.index[0]} a {sample.index[-1]}\"\nprint(f\"muestra: {span}, {len(sample)} observaciones\")\nsample.describe().round(2).T\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nmuestra: 2003Q4 a 2017Q4, 57 observaciones\n```\n:::\n\n::: {#setup .cell-output .cell-output-display execution_count=2}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>count</th>\n      <th>mean</th>\n      <th>std</th>\n      <th>min</th>\n      <th>25%</th>\n      <th>50%</th>\n      <th>75%</th>\n      <th>max</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>inf</th>\n      <td>57.0</td>\n      <td>3.01</td>\n      <td>1.34</td>\n      <td>0.41</td>\n      <td>2.17</td>\n      <td>3.01</td>\n      <td>3.60</td>\n      <td>6.65</td>\n    </tr>\n    <tr>\n      <th>mpr</th>\n      <td>57.0</td>\n      <td>3.83</td>\n      <td>1.12</td>\n      <td>1.15</td>\n      <td>3.13</td>\n      <td>4.16</td>\n      <td>4.37</td>\n      <td>6.56</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#cell-fig-series .cell execution_count=3}\n``` {.python .cell-code}\nimport matplotlib.pyplot as plt\n\nfrom macrobook import use_style, figsize, PALETTE, charts\n\nuse_style()\n\nsize = figsize(0.58)\nfig, axes = plt.subplots(2, 1, sharex=True, figsize=size)\nlabels = [\"inflación (%)\", \"tasa de referencia (%)\"]\nfor ax, column, label in zip(axes, sample.columns, labels):\n    ax.plot(dates, sample[column], color=PALETTE[\"ink\"], lw=1.0)\n    ax.set_ylabel(label)\ncharts.zero_line(axes[0])\naxes[1].set_xlabel(\"\")\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Inflación interanual y tasa de referencia del BCRP en la muestra de estimación, 2003Q4 a 2017Q4. Fuente: BCRP.](03-var_files/figure-html/fig-series-output-1.svg){#fig-series}\n:::\n:::\n\n\nLas dos series se mueven juntas y con persistencia: los episodios de inflación alta (2008, 2011) vienen acompañados de subidas de la tasa, con rezago. Ese comovimiento es lo que el VAR va a describir, y también la razón por la que describirlo no basta para hablar de efectos de política.\n\n## La forma companion {#sec-var-companion}\n\nTodo VAR(p) es un VAR(1) de mayor dimensión. Con el sistema de la @eq-var-bivariado, basta apilar el vector de hoy con el de ayer:\n\n$$\n\\underbrace{\\begin{bmatrix} \\pi_t \\\\ r_t \\\\ \\pi_{t-1} \\\\ r_{t-1} \\end{bmatrix}}_{\\tilde{\\mathbf{y}}_t}\n=\n\\underbrace{\\begin{bmatrix} c_1 \\\\ c_2 \\\\ 0 \\\\ 0 \\end{bmatrix}}_{\\tilde{c}}\n+\n\\underbrace{\\begin{bmatrix}\n \\phi^1_{11} & \\phi^1_{12} & \\phi^2_{11} & \\phi^2_{12} \\\\\n \\phi^1_{21} & \\phi^1_{22} & \\phi^2_{21} & \\phi^2_{22} \\\\\n 1 & 0 & 0 & 0 \\\\\n 0 & 1 & 0 & 0\n\\end{bmatrix}}_{F\\ (4 \\times 4)}\n\\begin{bmatrix} \\pi_{t-1} \\\\ r_{t-1} \\\\ \\pi_{t-2} \\\\ r_{t-2} \\end{bmatrix}\n+\n\\underbrace{\\begin{bmatrix} u_{1t} \\\\ u_{2t} \\\\ 0 \\\\ 0 \\end{bmatrix}}_{\\tilde{\\mathbf{u}}_t}.\n$$ {#eq-companion-bivariado}\n\nLas dos últimas filas son identidades contables: dicen que $\\pi_{t-1}$ de hoy es $\\pi_t$ de ayer. En general, con $\\tilde{\\mathbf{y}}_t = (\\mathbf{y}_t', \\mathbf{y}_{t-1}', \\ldots, \\mathbf{y}_{t-p+1}')'$ de dimensión $np$,\n\n$$\n\\tilde{\\mathbf{y}}_t = \\tilde{c} + F \\tilde{\\mathbf{y}}_{t-1} + \\tilde{\\mathbf{u}}_t,\n\\qquad\nF = \\begin{bmatrix}\n \\Phi_1 & \\Phi_2 & \\cdots & \\Phi_{p-1} & \\Phi_p \\\\\n I_n & 0 & \\cdots & 0 & 0 \\\\\n 0 & I_n & \\cdots & 0 & 0 \\\\\n \\vdots & & \\ddots & & \\vdots \\\\\n 0 & 0 & \\cdots & I_n & 0\n\\end{bmatrix},\n$$ {#eq-companion}\n\ny con el selector $J = [\\,I_n \\; 0 \\; \\cdots \\; 0\\,]$ se recupera el vector original, $\\mathbf{y}_t = J \\tilde{\\mathbf{y}}_t$.\n\n::: {.intuicion}\nLa forma companion cambia $p$ matrices por una sola. Todo lo que quiera decirse sobre el futuro del sistema, o sobre su estabilidad, se vuelve una afirmación sobre potencias de $F$.\n:::\n\nEl código imprime, junto con $F$, el módulo del mayor de sus valores propios. Ese número decide si el sistema es estable, que es el asunto de la sección siguiente.\n\n::: {.panel-tabset}\n#### Desde cero (NumPy)\n\n::: {#cell-companion-manual .cell execution_count=4}\n``` {.python .cell-code}\ndef companion(B, n, p):\n    \"\"\"Build F from B (k x n, constant in the first row).\"\"\"\n    F = np.zeros((n * p, n * p))\n    for lag in range(p):\n        rows = slice(1 + lag * n, 1 + (lag + 1) * n)\n        F[:n, lag * n : (lag + 1) * n] = B[rows, :].T\n    if p > 1:\n        F[n:, : n * (p - 1)] = np.eye(n * (p - 1))\n    return F\n\nfit = var.ols(y, p)\nF = companion(fit[\"B\"], n, p)\neigenvalues = np.linalg.eigvals(F)\n\nprint(\"máximo módulo:\", np.abs(eigenvalues).max().round(3))\nnp.round(F, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nmáximo módulo: 0.838\n```\n:::\n\n::: {#companion-manual .cell-output .cell-output-display execution_count=4}\n```\narray([[ 1.297,  0.16 , -0.6  , -0.081],\n       [ 0.145,  1.326, -0.217, -0.493],\n       [ 1.   ,  0.   ,  0.   ,  0.   ],\n       [ 0.   ,  1.   ,  0.   ,  0.   ]])\n```\n:::\n:::\n\n\n#### macrobook\n\n::: {#cell-companion-package .cell execution_count=5}\n``` {.python .cell-code}\nF_package = var.companion(fit[\"B\"], n, p)\nnp.allclose(F, F_package)\n```\n\n::: {#companion-package .cell-output .cell-output-display execution_count=5}\n```\nTrue\n```\n:::\n:::\n\n\n:::\n\n## Estabilidad y estacionariedad {#sec-var-estabilidad}\n\n::: {#def-estacionariedad}\n## Estacionariedad en covarianza\n\nEl proceso $\\{\\mathbf{y}_t\\}_{t \\in \\mathbb{Z}}$ es estacionario en covarianza, o débilmente estacionario, si sus dos primeros momentos existen y no dependen de la fecha:\n\n- **Media constante:** $\\mathbb{E}[\\mathbf{y}_t] = \\mu$ para todo $t$.\n- **Autocovarianzas que sólo dependen del rezago:** $\\mathbb{E}\\big[(\\mathbf{y}_t - \\mu)(\\mathbf{y}_{t-j} - \\mu)'\\big] = \\Gamma_j$ para todo $t$ y todo $j \\geq 0$, con $\\Gamma_0$ finita.\n:::\n\nLa @def-estacionariedad es una propiedad del proceso, no de la muestra: ninguna prueba la verifica directamente. La condición que la garantiza en un VAR es una propiedad de $F$.\n\n::: {#prp-estabilidad}\n## Estabilidad\n\nEl VAR de la @eq-var-p es estable si y sólo si todos los valores propios de la matriz companion $F$ tienen módulo menor que uno,\n\n$$ \\max_i |\\lambda_i(F)| < 1 \\iff \\det\\big(I_n - \\Phi_1 z - \\cdots - \\Phi_p z^p\\big) \\neq 0 \\ \\text{ para } |z| \\leq 1 . $$\n\nSi el VAR es estable, admite la representación de Wold\n\n$$ \\mathbf{y}_t = \\mu + \\sum_{j=0}^{\\infty} \\Psi_j \\mathbf{u}_{t-j}, \\qquad \\Psi_j = J F^j J', $$ {#eq-wold}\n\ncon media incondicional $\\mu = (I_n - \\Phi_1 - \\cdots - \\Phi_p)^{-1} c$, y es estacionario en covarianza.\n:::\n\nLa idea detrás de la @eq-wold es una sustitución recursiva. Partiendo de $\\mathbf{y}_t = \\Phi_1 \\mathbf{y}_{t-1} + \\mathbf{u}_t$ y reemplazando el rezago una y otra vez,\n\n$$\n\\mathbf{y}_t = \\Phi_1(\\Phi_1 \\mathbf{y}_{t-2} + \\mathbf{u}_{t-1}) + \\mathbf{u}_t\n= \\cdots = \\Phi_1^{t}\\mathbf{y}_0 + \\sum_{j=0}^{t-1} \\Phi_1^{j} \\mathbf{u}_{t-j},\n$$\n\nde modo que cada observación es una combinación de los choques presentes y pasados más una condición inicial. Si $\\Phi_1^{j}$ no converge a cero, la condición inicial nunca se olvida y la varianza crece sin límite.\n\n::: {#cell-fig-roots .cell execution_count=6}\n``` {.python .cell-code}\nroots = var.roots(fit[\"B\"], n, p)\n\nratios = {\"width_ratios\": [1, 1.4]}\nfig, (ax_plane, ax_mod) = plt.subplots(\n    1, 2, figsize=figsize(0.36), gridspec_kw=ratios)\ncharts.unit_circle(ax_plane, roots)\n\nmodulus = np.abs(roots)\nposition = np.arange(len(modulus))[::-1]\nax_mod.hlines(position, 0, modulus,\n              color=PALETTE[\"rule\"], lw=1.0)\nax_mod.plot(modulus, position, ls=\"none\", marker=\"o\", ms=4,\n            color=PALETTE[\"accent\"])\nax_mod.axvline(1.0, color=PALETTE[\"ink\"], lw=0.8,\n               ls=(0, (4, 2)))\nn_roots = len(modulus)\ntick_labels = [f\"$\\\\lambda_{{{i+1}}}$\" for i in range(n_roots)]\nax_mod.set_yticks(position, tick_labels)\nax_mod.set_xlim(0, 1.15)\nax_mod.set_xlabel(\"módulo\")\nax_mod.grid(False, axis=\"y\")\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Valores propios de la matriz companion estimada: en el plano complejo (izquierda) y ordenados por módulo (derecha). El sistema es estable.](03-var_files/figure-html/fig-roots-output-1.svg){#fig-roots}\n:::\n:::\n\n\nLa estabilidad tiene consecuencias visibles: sin choques, el sistema regresa a su media incondicional desde cualquier punto de partida.\n\n::: {#cell-fig-convergence .cell execution_count=7}\n``` {.python .cell-code}\nmu = var.unconditional_mean(fit[\"B\"], n, p)\nphis, c_hat = var.coefficients_by_lag(fit[\"B\"], n, p)\n\ndef path_without_shocks(start, steps=24):\n    history = [np.asarray(start, float)] * p\n    out = []\n    for _ in range(steps):\n        terms = (Phi @ history[lag]\n                 for lag, Phi in enumerate(phis))\n        nxt = c_hat + sum(terms)\n        out.append(nxt)\n        history = [nxt] + history[:-1]\n    return np.array(out)\n\nfig, ax = plt.subplots(figsize=figsize(0.52))\nfor k, start in enumerate([[0.0, 2.0], [7.0, 3.0], [3.0, 7.0]]):\n    path = path_without_shocks(start)\n    ax.plot(path[:, 0], color=PALETTE[\"shocks\"][k], lw=1.1,\n            ls=PALETTE[\"shock_linestyle\"][k],\n            label=f\"$\\\\pi_0 = {start[0]:.0f}$, \"\n                  f\"$r_0 = {start[1]:.0f}$\")\nax.axhline(mu[0], color=PALETTE[\"accent\"], lw=1.0,\n           ls=(0, (1, 2)))\nax.set_ylabel(\"inflación (%)\")\nax.set_xlabel(\"trimestres\")\ncharts.legend_outside(ax, ncol=3)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Sendas sin choques desde tres puntos de partida. Con el VAR estable, todas convergen a la media incondicional (línea punteada).](03-var_files/figure-html/fig-convergence-output-1.svg){#fig-convergence}\n:::\n:::\n\n\n::: {.cuidado}\nLa estabilidad hace falta para que existan los momentos incondicionales, para que las respuestas al impulso converjan a cero y para que la descomposición de varianza tenga sentido. No hace falta para estimar: mínimos cuadrados está bien definido aunque haya una raíz unitaria, y el pronóstico a horizonte finito también. La práctica estándar no es diferenciar por reflejo [@simsstockwatson1990]: qué variable entra al sistema y en qué transformación se decide antes de estimar, y la @sec-var-otros discute con qué criterio.\n:::\n\n## Estimación por mínimos cuadrados {#sec-var-mco}\n\n::: {#prp-mco}\n## Mínimos cuadrados ecuación por ecuación\n\nEn el VAR sin restricciones, donde todas las ecuaciones comparten los regresores $X$, el estimador de mínimos cuadrados ecuación por ecuación\n\n$$ \\hat{B} = (X'X)^{-1}X'Y, \\qquad \\hat{\\Sigma} = \\frac{(Y - X\\hat{B})'(Y - X\\hat{B})}{T - k} $$ {#eq-var-mco}\n\ncoincide con el estimador de mínimos cuadrados generalizados del sistema completo y, bajo normalidad, con el estimador de máxima verosimilitud condicionado a las $p$ observaciones iniciales.\n:::\n\nEl resultado, que se demuestra en el @exr-bvar-1 con el sistema escrito como una sola regresión, es el que permite tratar $n$ ecuaciones como $n$ regresiones separadas. Su contracara aparece en el @sec-bvar: en cuanto el prior enlaza las ecuaciones, o $\\Sigma$ entra en la restricción, la separabilidad se pierde.\n\n::: {.panel-tabset}\n#### Desde cero (NumPy)\n\n::: {#cell-ols-manual .cell execution_count=8}\n``` {.python .cell-code}\ndef lag_matrix(y, p):\n    \"\"\"Y = y[p:] and X = [1, y_{t-1}, ..., y_{t-p}].\"\"\"\n    T, n = y.shape\n    columns = [y[p - lag : T - lag] for lag in range(1, p + 1)]\n    X = np.column_stack([np.ones(T - p)] + columns)\n    return y[p:], X\n\nY, X = lag_matrix(y, p)\nB_ols = np.linalg.solve(X.T @ X, X.T @ Y)\nU = Y - X @ B_ols\nT_eff, k = X.shape\nSigma_ols = U.T @ U / (T_eff - k)\n\n# Standard errors: equation i uses Sigma_ii * (X'X)^{-1}.\nXtX_inv = np.linalg.inv(X.T @ X)\nse = np.sqrt(np.outer(np.diag(XtX_inv), np.diag(Sigma_ols)))\n\nrows = [\"constante\", \"π(-1)\", \"r(-1)\", \"π(-2)\", \"r(-2)\"]\ncols = sample.columns\ncoef = pd.DataFrame(B_ols, index=rows, columns=cols).round(3)\nstderr = pd.DataFrame(se, index=rows, columns=cols).round(3)\nreport = coef.astype(str) + \" (\" + stderr.astype(str) + \")\"\nreport.columns = [\"ecuación de π\", \"ecuación de r\"]\nreport\n```\n\n::: {#ols-manual .cell-output .cell-output-display execution_count=8}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>ecuación de π</th>\n      <th>ecuación de r</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>constante</th>\n      <td>0.583 (0.3)</td>\n      <td>0.867 (0.193)</td>\n    </tr>\n    <tr>\n      <th>π(-1)</th>\n      <td>1.297 (0.139)</td>\n      <td>0.145 (0.09)</td>\n    </tr>\n    <tr>\n      <th>r(-1)</th>\n      <td>0.16 (0.19)</td>\n      <td>1.326 (0.123)</td>\n    </tr>\n    <tr>\n      <th>π(-2)</th>\n      <td>-0.6 (0.139)</td>\n      <td>-0.217 (0.09)</td>\n    </tr>\n    <tr>\n      <th>r(-2)</th>\n      <td>-0.081 (0.19)</td>\n      <td>-0.493 (0.122)</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n#### macrobook\n\n::: {#cell-ols-package .cell execution_count=9}\n``` {.python .cell-code}\nfit = var.ols(y, p)\n(np.allclose(fit[\"B\"], B_ols),\n np.allclose(fit[\"Sigma\"], Sigma_ols))\n```\n\n::: {#ols-package .cell-output .cell-output-display execution_count=9}\n```\n(True, True)\n```\n:::\n:::\n\n\n:::\n\nEntre paréntesis van los errores estándar de mínimos cuadrados, $\\sqrt{\\hat{\\sigma}_{ii}\\,[(X'X)^{-1}]_{jj}}$ para el coeficiente $j$ de la ecuación $i$. La lectura inmediata es que cada serie depende sobre todo de su propio pasado. En la ecuación de la inflación los coeficientes de la tasa son pequeños frente a su error estándar; en la ecuación de la tasa los de la inflación son mayores, pero con signos opuestos entre el primer y el segundo rezago. Leer coeficientes de a uno en un VAR rara vez informa: conviene mirar sumas que resuman el sistema.\n\n::: {#sumas .cell execution_count=10}\n``` {.python .cell-code}\nphis, c_hat = var.coefficients_by_lag(np.asarray(B_ols), n, p)\npersistence = [sum(Phi[i, i] for Phi in phis) for i in range(n)]\nrate_on_inflation = sum(Phi[0, 1] for Phi in phis)  # r -> π\ninflation_on_rate = sum(Phi[1, 0] for Phi in phis)  # π -> r\n\nprint(f\"persistencia propia de π: {persistence[0]:.2f}\")\nprint(f\"persistencia propia de r: {persistence[1]:.2f}\")\nprint(f\"suma de r en ecuación de π: {rate_on_inflation:+.2f}\")\nprint(f\"suma de π en ecuación de r: {inflation_on_rate:+.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\npersistencia propia de π: 0.70\npersistencia propia de r: 0.83\nsuma de r en ecuación de π: +0.08\nsuma de π en ecuación de r: -0.07\n```\n:::\n:::\n\n\nCada cifra es la suma de los dos coeficientes correspondientes de la tabla anterior: la persistencia de la inflación es $1.297 - 0.600$, y la suma de los coeficientes de la tasa en esa misma ecuación es $0.160 - 0.081$. Las dos series son persistentes y las sumas cruzadas son casi cero, con la de la tasa sobre la inflación incluso ligeramente positiva. Sería un error leer esa cifra como \"subir la tasa no baja la inflación, o la sube\": lo que mide es la correlación parcial entre la tasa de ayer y la inflación de hoy en una muestra donde el banco central subía la tasa precisamente cuando esperaba más inflación. La @sec-var-sigma desarrolla ese punto.\n\n## La matriz de covarianzas y el problema de los choques {#sec-var-sigma}\n\nHasta aquí $\\Sigma$ ha sido un objeto secundario. Es, en realidad, donde se esconde todo lo que la forma reducida no puede responder. Por definición,\n\n$$\n\\Sigma = \\mathbb{E}[\\mathbf{u}_t \\mathbf{u}_t'] =\n\\begin{bmatrix}\n \\mathbb{E}[u_{1t}^2] & \\mathbb{E}[u_{1t} u_{2t}] \\\\\n \\mathbb{E}[u_{2t} u_{1t}] & \\mathbb{E}[u_{2t}^2]\n\\end{bmatrix}\n=\n\\begin{bmatrix} \\sigma_1^2 & \\sigma_{12} \\\\ \\sigma_{12} & \\sigma_2^2 \\end{bmatrix},\n$$ {#eq-sigma}\n\nuna matriz simétrica con $n(n+1)/2$ elementos distintos: tres en el caso bivariado. El elemento que importa es el de fuera de la diagonal.\n\n::: {#sigma .cell execution_count=11}\n``` {.python .cell-code}\nSigma_hat = fit[\"Sigma\"]\nsd = np.sqrt(np.diag(Sigma_hat))\nrho = Sigma_hat[0, 1] / (sd[0] * sd[1])\nbeta = Sigma_hat[0, 1] / Sigma_hat[1, 1]      # E[u_1 | u_2 = 1]\n\nprint(\"Sigma estimada:\\n\", np.round(Sigma_hat, 3))\nprint(f\"desviaciones estándar: π {sd[0]:.2f}, r {sd[1]:.2f}\")\nprint(f\"correlación entre innovaciones: {rho:.2f}\")\nprint(f\"E[u_π | u_r = 1] = {beta:.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSigma estimada:\n [[0.363 0.101]\n [0.101 0.151]]\ndesviaciones estándar: π 0.60, r 0.39\ncorrelación entre innovaciones: 0.43\nE[u_π | u_r = 1] = 0.67\n```\n:::\n:::\n\n\nLos residuos de la forma reducida son **errores de pronóstico**, no choques económicos: $u_{1t}$ es la parte de la inflación de hoy que el pasado del sistema no anticipaba, y lo mismo $u_{2t}$ para la tasa. Nada garantiza que esas sorpresas tengan una interpretación económica, y de hecho están correlacionadas entre sí.\n\n::: {.cuidado}\nCon $\\rho \\neq 0$, la pregunta \"¿qué pasa con la inflación si la tasa sube una unidad de manera inesperada, manteniendo todo lo demás constante?\" no tiene respuesta dentro de este modelo. En los datos, las veces en que $u_{2t} = 1$ vienen acompañadas en promedio por $u_{1t} = \\sigma_{12}/\\sigma_2^2 \\neq 0$: mover una innovación dejando la otra fija describe una combinación de sorpresas que la muestra no contiene. Una supuesta impulso-respuesta calculada sobre $\\mathbf{u}_t$ no es causal; es una correlación dinámica disfrazada.\n:::\n\nVale la pena leer lo mismo a nivel de coeficientes. En la ecuación de la inflación, la suma de los coeficientes de la tasa resultó prácticamente nula, y en la ecuación de la tasa la suma de los coeficientes de la inflación también. Ninguna de las dos cifras mide un efecto causal, porque ambas describen una muestra en la que el banco central movía la tasa **en respuesta a** lo que veía venir en los precios. Si la política fue sistemática y razonablemente exitosa, la tasa sube justo antes de los episodios inflacionarios y baja cuando ceden: la correlación parcial resultante puede tener cualquier signo, y de hecho la literatura empírica encontró durante años coeficientes con el signo \"equivocado\", el llamado *price puzzle*, precisamente por esta razón.\n\nLa salida es suponer que las sorpresas observadas son combinaciones lineales de choques no observados con significado económico,\n\n$$ \\mathbf{u}_t = S \\varepsilon_t, \\qquad \\mathbb{E}[\\varepsilon_t \\varepsilon_t'] = I_n, \\qquad \\text{de modo que} \\quad \\Sigma = S S'. $$ {#eq-identificacion}\n\nAquí $\\varepsilon_t$ son, por ejemplo, un choque de demanda y un choque de política monetaria, y la matriz de impacto $S$ dice cuánto mueve cada choque a cada variable en el momento cero. El problema es de conteo: $\\Sigma$ ofrece $n(n+1)/2 = 3$ ecuaciones y $S$ tiene $n^2 = 4$ incógnitas, así que faltan $n(n-1)/2 = 1$ restricciones que los datos no pueden entregar.\n\n::: {.intuicion}\nLa estimación de la forma reducida es un problema estadístico y tiene solución única. La identificación es un problema económico: hay que aportar información que no está en los datos. Todo el @sec-svar trata de dónde sacar esas restricciones y de cuánto dependen los resultados de haberlas elegido así.\n:::\n\n## Pronóstico con la forma companion {#sec-var-pronostico}\n\nEl pronóstico óptimo bajo pérdida cuadrática es la esperanza condicional, y en el VAR se obtiene iterando la @eq-companion hacia adelante con los choques futuros puestos en su media.\n\n::: {#alg-pronostico}\n1. Construir el estado inicial apilado con las últimas $p$ observaciones:\n\n   $$\\tilde{\\mathbf{y}}_T = (\\mathbf{y}_T',\\ \\mathbf{y}_{T-1}',\\ \\ldots,\\ \\mathbf{y}_{T-p+1}')'.$$\n\n2. Iterar la recursión companion hasta el horizonte deseado y recuperar el vector original con el selector $J$:\n\n   $$\\hat{\\tilde{\\mathbf{y}}}_{T+h|T} = \\tilde{c} + F\\, \\hat{\\tilde{\\mathbf{y}}}_{T+h-1|T},\n   \\qquad \\hat{\\mathbf{y}}_{T+h|T} = J\\, \\hat{\\tilde{\\mathbf{y}}}_{T+h|T}.$$\n\n3. Acumular la matriz de error cuadrático medio con los pesos de Wold:\n\n   $$\\operatorname{ECM}_h = \\sum_{j=0}^{h-1} \\Psi_j\\, \\Sigma\\, \\Psi_j', \\qquad \\Psi_j = J F^j J'.$$\n\n4. Formar el intervalo al 95 % para cada variable $i$:\n\n   $$\\hat{y}_{i,T+h|T} \\pm 1.96\\,\\sqrt{\\big[\\operatorname{ECM}_h\\big]_{ii}}.$$\n\nPronóstico puntual e intervalos en un VAR estimado\n:::\n\n::: {#cell-fig-forecast .cell execution_count=12}\n``` {.python .cell-code}\nh = len(future)\npaths, variances = var.forecast(y, fit[\"B\"], fit[\"Sigma\"], p, h)\nsd_h = np.sqrt(variances)\n\nhist = sample.iloc[-32:]\nhist_dates = hist.index.to_timestamp(how=\"end\")\nfc_dates = future.index.to_timestamp(how=\"end\")\nedge_dates = np.r_[hist_dates[-1:], fc_dates]\n\nsize = figsize(0.66)\nfig, axes = plt.subplots(2, 1, sharex=True, figsize=size)\nlabels = [\"inflación (%)\", \"tasa de referencia (%)\"]\nfor i, (ax, label) in enumerate(zip(axes, labels)):\n    last = y[-1, i]\n    band = [(np.r_[last, paths[:, i] - 1.96 * sd_h[:, i]],\n             np.r_[last, paths[:, i] + 1.96 * sd_h[:, i]])]\n    band_labels = [\"IC 95 %\"] if i == 0 else None\n    charts.fan_chart(ax, hist_dates, hist.iloc[:, i],\n                     edge_dates, band, np.r_[last, paths[:, i]],\n                     realized=future.iloc[:, i],\n                     dates_realized=fc_dates,\n                     band_labels=band_labels)\n    ax.axvline(hist_dates[-1], color=PALETTE[\"muted\"],\n               lw=0.8, ls=(0, (3, 2)), zorder=1)\n    ax.set_ylabel(label)\ntop = axes[0].get_ylim()[1]\naxes[0].annotate(\"pronóstico\", xy=(edge_dates[2], top),\n                 xytext=(0, -10), textcoords=\"offset points\",\n                 fontsize=7.5, color=PALETTE[\"muted\"])\ncharts.legend_outside(axes[0], ncol=4)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Pronóstico a ocho trimestres con intervalo al 95 %, y los datos observados de 2018 y 2019, que no entraron en la estimación. La línea vertical marca el final de la muestra.](03-var_files/figure-html/fig-forecast-output-1.svg){#fig-forecast}\n:::\n:::\n\n\nLos dos años reservados permiten una evaluación mínima: qué tan lejos quedó el pronóstico puntual y con qué frecuencia el intervalo contuvo al dato.\n\n::: {#evaluacion .cell execution_count=13}\n``` {.python .cell-code}\nactual = future.to_numpy()\nerror = actual - paths\nrmse = np.sqrt((error ** 2).mean(axis=0))\ninside = (np.abs(error) <= 1.96 * sd_h).mean(axis=0)\n\npct = [f\"{x:.0%}\" for x in inside]\n\nprint(f\"RMSE a 8 trimestres: π {rmse[0]:.2f}, r {rmse[1]:.2f}\")\nprint(f\"dentro del IC 95 %: π {pct[0]}, r {pct[1]}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRMSE a 8 trimestres: π 0.94, r 1.38\ndentro del IC 95 %: π 100%, r 100%\n```\n:::\n:::\n\n\nEl pronóstico no se equivoca al azar. Sobreestima las dos series, el error crece con el horizonte y la @fig-forecast muestra por qué: con el sistema estable, la proyección converge a la media incondicional implícita, $\\hat{\\mu} = (2.94,\\ 3.92)$, mientras que la economía de 2018 y 2019 se quedó en un régimen de inflación cerca de 2 % con la tasa de referencia alrededor de 2.75 %. A ocho trimestres el pronóstico de la tasa erra por más de dos puntos porcentuales, y los ocho errores tienen el mismo signo.\n\nLos ocho datos caen dentro del intervalo al 95 %, y eso no es evidencia de que el intervalo esté bien calibrado: son ocho observaciones correlacionadas entre sí, con las que no se distingue una cobertura de 95 % de una de 100 %. El intervalo tampoco es exigente. A ocho trimestres mide casi tres puntos porcentuales hacia cada lado para la inflación, un rango que la serie no iba a abandonar. Que sea ancho y aun así optimista es el punto del recuadro siguiente.\n\n::: {.cuidado}\nEl intervalo trata $\\hat{B}$ y $\\hat{\\Sigma}$ como si fueran los valores verdaderos, de modo que subestima la incertidumbre. El sesgo crece cuando la muestra es corta o el sistema es grande, justo donde más importa. La versión honesta integra sobre la distribución de los parámetros, que es lo que hace el pronóstico por densidad del @sec-bvar.\n:::\n\nQueda una decisión de reporte: el nivel. En pronóstico frecuentista lo habitual es 90 % o 95 %, y los abanicos de banca central muestran varios tramos hasta el 90 %. Las bandas al 68 %, tan frecuentes en la literatura de VAR estructurales, vienen de otra tradición: son intervalos de una desviación estándar, popularizados por Sims y Zha [-@simszha1999], que argumentaron que en muestras cortas el 95 % queda tan ancho que no disciplina nada. La crítica moderna es que esas bandas ni son intervalos de confianza al 68 % en sentido estricto ni son simultáneas a lo largo del horizonte, de modo que la cobertura conjunta es bastante menor de lo que el número sugiere [@montielolea2019]. La regla del libro: declarar el nivel, decir si es puntual o simultáneo, y no cambiarlo de capítulo en capítulo para que la figura se vea mejor.\n\n\n## Otros temas del VAR clásico {#sec-var-otros}\n\nLo que sigue son cuestiones estándar de la práctica con VAR que este libro no desarrolla, porque están bien tratadas en los manuales y porque el hilo del texto va hacia la identificación y los métodos bayesianos. Van aquí los criterios que conviene tener presentes y la referencia donde estudiarlos.\n\n### Selección de rezagos\n\nLos criterios de información penalizan el ajuste por el número de parámetros: AIC penaliza $2k$, el de Hannan y Quinn $2k\\ln(\\ln T)$, con el logaritmo aplicado dos veces, y el bayesiano (BIC o SIC) $k\\ln T$. El BIC es consistente para el orden verdadero y el AIC no, pero el AIC suele elegir modelos que pronostican mejor en muestras cortas, así que la elección depende del objetivo. Dos reglas prácticas: comparar siempre sobre la misma muestra efectiva, porque cambiar $p$ cambia el número de observaciones utilizables; y, si el fin es el análisis de impulso-respuesta con datos trimestrales, seguir a Ivanov y Kilian [-@ivanov2005], que recomiendan AIC en esa configuración y HQ en muestras largas o en frecuencia mensual. Con datos trimestrales, $p = 4$ es el punto de partida habitual y $p = 2$ una elección defendible cuando la muestra es corta. Véase Lütkepohl [-@lutkepohl2005, cap. 4].\n\n### Diagnóstico de residuos\n\nEl supuesto que hay que vigilar es la ausencia de autocorrelación, porque de él depende que los rezagos incluidos basten para blanquear el error. Se contrasta con un estadístico Portmanteau (Ljung-Box multivariado) o con la prueba LM de Breusch y Godfrey. La normalidad se examina con una versión multivariada de Jarque-Bera, y conviene recordar que no es necesaria para la consistencia: sólo afecta a la inferencia en muestras pequeñas. La heterocedasticidad condicional se detecta con ARCH-LM y se modela en el @sec-volatilidad. Para la estabilidad de los coeficientes existen pruebas de quiebre y estadísticos CUSUM, y el tratamiento explícito está en el @sec-tvp. Buena práctica: ante autocorrelación residual, agregar rezagos antes que cambiar de modelo. Véase Lütkepohl [-@lutkepohl2005, cap. 4].\n\n### Niveles, diferencias y cointegración\n\nConviene separar dos decisiones que suelen confundirse. La primera es **qué variable económica interesa**: el nivel de precios o la inflación, el PIB o su tasa de crecimiento. Esa elección es sustantiva y viene antes que la econometría; en este capítulo interesan la inflación y la tasa de política, no el índice de precios. La segunda, ya fijadas las variables, es **si las series que entran al sistema tienen raíz unitaria** y qué hacer al respecto. La discusión que sigue es sobre la segunda.\n\n- **Variables con tendencia estocástica, estimadas en niveles.** Mínimos cuadrados sigue siendo consistente y las respuestas de corto plazo no se distorsionan, pero la inferencia sobre funciones de largo plazo deja de ser estándar y algunos estadísticos ya no son asintóticamente normales [@simsstockwatson1990]. Es lo que hace la mayor parte de la literatura estructural desde Sims [-@sims1980], con un argumento claro: si las series comparten una relación de equilibrio, diferenciarlas la destruye.\n- **Variables con tendencia estocástica, en diferencias o con cointegración explícita.** Si el objeto de interés es esa relación de largo plazo, el modelo correcto es el VECM, que separa el ajuste de corto plazo del equilibrio; diferenciar sin el término de corrección de error pierde el equilibrio, y dejarlo implícito en un VAR en niveles complica la inferencia sobre él. El número de vectores de cointegración se contrasta con el procedimiento de máxima verosimilitud de Johansen [-@johansen1995], sobre la representación de Engle y Granger [-@engle1987].\n\nEste capítulo no está en ninguno de los dos casos, y vale la pena ver por qué. La inflación interanual es una transformación del IPC, pero no es la variable original diferenciada para forzar estacionariedad: es la variable que el banco central controla y sobre la que anuncia su meta. Lo mismo la tasa de referencia, que es un nivel. Ninguna de las dos es candidata natural a raíz unitaria bajo un régimen de metas, y el módulo máximo de las raíces estimadas (0.84) es compatible con ello, aunque mínimos cuadrados sesga las raíces hacia abajo en muestras de este tamaño. La discusión anterior se vuelve inevitable cuando al sistema entran el producto, el tipo de cambio o los precios en logaritmos. Para el tratamiento completo, Lütkepohl [-@lutkepohl2005, caps. 6-8].\n\n### Tamaño del sistema\n\nLa decisión que más determina los resultados no es el orden de rezagos sino qué variables entran. Un VAR pequeño y bien argumentado suele ser preferible a uno grande estimado sin restricciones, y cuando el sistema debe crecer la respuesta no es eliminar variables sino encogerlas: eso es el @sec-bvar.\n\n## Ideas clave {.unnumbered}\n\n::: {.ideas-clave}\n1. El VAR es un dispositivo de resumen de la dinámica conjunta: describe correlaciones dinámicas, no efectos causales.\n2. Las tres representaciones son el mismo modelo: la compacta sirve para estimar y la companion para proyectar y para estudiar la estabilidad. El @sec-bvar agrega una cuarta, la vectorizada, cuando hace falta enlazar las ecuaciones.\n3. La estabilidad es una propiedad de los valores propios de la companion, y es lo que permite hablar de media incondicional, de representación de Wold y de respuestas que se disipan.\n4. Con los mismos regresores en todas las ecuaciones, mínimos cuadrados ecuación por ecuación no deja nada sobre la mesa; con priors o restricciones cruzadas, sí.\n5. $\\Sigma$ no es diagonal, y por eso los residuos de la forma reducida no se pueden mover de a uno: sin una hipótesis de identificación no hay impulso-respuesta con interpretación causal.\n:::\n\n## Lecturas recomendadas {.unnumbered}\n\n::: {.lecturas}\nSims (1980)\n:   El artículo que inició el programa; conviene leer la crítica a las restricciones increíbles de los modelos de ecuaciones simultáneas.\n\nStock y Watson (2001)\n:   Revisión breve y honesta de lo que un VAR puede y no puede hacer.\n\nLütkepohl (2005), caps. 2 y 3\n:   El tratamiento completo de la forma companion, la estabilidad y la inferencia asintótica.\n\nKilian y Lütkepohl (2017), cap. 2\n:   La misma materia con el énfasis puesto en lo que hará falta para el capítulo siguiente.\n\nSims y Zha (1999)\n:   El origen de las bandas al 68 % y el argumento a su favor.\n:::\n\n## Ejercicios {.unnumbered}\n\n::: {#exr-var-1}\nEscriba a mano la matriz companion de un VAR(3) con dos variables y verifique en Python que iterarla reproduce el pronóstico obtenido por recursión directa sobre la @eq-var-p.\n:::\n\n::: {#exr-var-2}\nEstime el VAR con $p = 1, 2, 3, 4$ sobre la misma muestra efectiva y compare AIC, BIC y el módulo máximo de las raíces. ¿Coinciden los criterios? ¿Cambia alguna conclusión sobre la persistencia del sistema?\n:::\n\n::: {#exr-var-3}\nReestime el modelo extendiendo la muestra hasta 2019Q4, es decir agregando las ocho observaciones que aquí se reservaron. Compare los coeficientes, la correlación entre innovaciones y el ancho del intervalo a ocho trimestres. ¿Cuánto mueven ocho observaciones a un sistema estimado con 57?\n:::\n\n::: {#exr-var-4}\nCalcule $\\hat{\\mu} = (I - \\hat{\\Phi}_1 - \\hat{\\Phi}_2)^{-1}\\hat{c}$ y compárela con el promedio muestral de cada serie. ¿Por qué la media implícita se estima mejor que el intercepto? Compare también $\\hat{\\mu}_\\pi$ con la meta de inflación del BCRP.\n:::\n\n::: {#exr-var-5}\nSimule con `var.simulate` un sistema con los coeficientes estimados pero con $\\sigma_{12} = 0$, y vuelva a estimar. ¿Cambian los coeficientes? ¿Cambia lo que se puede afirmar sobre el efecto de un choque de tasa? Use el resultado para explicar por qué la identificación es un problema aparte de la estimación.\n:::\n\n::: {#exr-var-6}\nTome $\\hat{\\Phi}_1$ y multiplíquelo por un escalar creciente hasta que el módulo máximo de los valores propios pase de uno. Simule el sistema justo antes y justo después del umbral y grafique las trayectorias. ¿Qué cambia en la escala del eje vertical?\n:::\n\n",
    "supporting": [
      "03-var_files/figure-html"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}