{
  "hash": "f5f73367a6288756ef098a1ec5798336",
  "result": {
    "engine": "jupyter",
    "markdown": "# [0]{.chapter-number}&nbsp; [Python, álgebra y probabilidad]{.chapter-title} {#sec-prelim .unnumbered .capitulo-cero}\n\n::: {.pregunta}\n¿Qué hace falta saber de Python, de álgebra matricial y de probabilidad para leer el resto del libro, y dónde se usa cada cosa?\n:::\n\n::: {.aprendizajes}\n1. Leer y escribir el código del libro: NumPy, pandas, matplotlib, funciones y clases.\n2. Repasar el álgebra matricial que sostiene a los VAR: productos, potencias, autovalores, Cholesky, Kronecker y el operador vec.\n3. Simular de las distribuciones que usa el libro y entender, en su versión más simple, el Monte Carlo, el bootstrap y el muestreo de Gibbs.\n:::\n\n**Requisitos previos.** Un curso de álgebra lineal y uno de estadística. No hace falta haber programado en Python.\n\n::: {.datos-usados}\n| Serie | Fuente | Frecuencia | Código |\n|:-------------------------------|:--------|:-----------|:--------------|\n| IPC de Lima Metropolitana | BCRP | mensual | `PN38705PM` |\n| Series simuladas | este capítulo | | |\n\nTodo lo demás se simula con semilla fija, de modo que cada número del texto se reproduce exactamente al ejecutar el código.\n:::\n\n## [0.1]{.header-section-number} Cómo leer este capítulo {#sec-prelim-mapa .unnumbered}\n\nEste capítulo no es un curso de Python ni de álgebra lineal. Los hay excelentes y gratuitos, y se citan a lo largo del texto. Es un repaso dirigido: para escribirlo se recorrieron los capítulos del libro, se anotó cada herramienta que dan por sabida y se reunieron aquí, en el orden en que conviene aprenderlas, con un ejemplo que se puede ejecutar y un enlace al lugar donde se vuelven a usar.\n\nSe puede leer de dos maneras. Quien empieza con Python conviene que lo lea de corrido, ejecutando cada celda. Quien ya programa puede usarlo como referencia: cada capítulo abre con una línea de **requisitos previos** que enlaza con la sección de este capítulo que la cubre.\n\n| Herramienta | Se repasa en | Se usa en |\n|:--------------------------------|:------|:----------------------------------------|\n| Bucles y funciones | [0.2](#sec-prelim-python) | [pronóstico recursivo](03-var.qmd#sec-var-pronostico), [bootstrap](04-svar.qmd#sec-svar-bandas) |\n| Arreglos, producto matricial, sistemas lineales | [0.3](#sec-prelim-numpy) | [MCO del VAR](03-var.qmd#sec-var-mco) |\n| Potencias y autovalores | [0.4](#sec-prelim-autovalores) | [estabilidad y Wold](03-var.qmd#sec-var-estabilidad), [impulso-respuesta](04-svar.qmd#sec-svar-irf) |\n| Determinante, Cholesky, matrices ortogonales | [0.5](#sec-prelim-factorizaciones) | [identificación recursiva](04-svar.qmd#sec-svar-cholesky), [restricciones de signo](04-svar.qmd#sec-svar-signo) |\n| Kronecker y vec | [0.6](#sec-prelim-kronecker) | [forma vectorizada](05-bvar.qmd#sec-bvar-vectorizada), [posterior](05-bvar.qmd#sec-bvar-gibbs) |\n| Series, fechas y transformaciones | [0.7](#sec-prelim-pandas) | [datos macroeconómicos](01-macro-data.qmd#sec-datos-transformaciones) |\n| Gráficos | [0.8](#sec-prelim-graficos) | todas las figuras |\n| Módulos y clases | [0.9](#sec-prelim-clases) | `macrobook` y `MacroPy`, en todos los capítulos |\n| Normal multivariada, gamma, beta, inversa-Wishart | [0.10](#sec-prelim-distribuciones) | [prior de Minnesota](05-bvar.qmd#sec-bvar-minnesota), [prior de $\\Sigma$](05-bvar.qmd#sec-bvar-gibbs) |\n| Monte Carlo y bootstrap | [0.11](#sec-prelim-simulacion) | [bandas](04-svar.qmd#sec-svar-bandas), [densidad predictiva](05-bvar.qmd#sec-bvar-pronostico) |\n| Bayes y Gibbs | [0.12](#sec-prelim-bayes) | todo el [capítulo 5](05-bvar.qmd) |\n\n: Qué herramienta se repasa dónde y en qué capítulo se usa\n\nUn solo modelo recorre todo el capítulo: el autorregresivo de orden uno,\n\n$$ y_t = c + \\phi\\, y_{t-1} + \\varepsilon_t, \\qquad \\varepsilon_t \\sim N(0, \\sigma^2), $$\n\nque es el VAR del [capítulo 3](03-var.qmd) con una sola variable. Si $|\\phi| < 1$, el proceso es estacionario, con media $\\mu = c/(1-\\phi)$ y varianza $\\sigma^2/(1-\\phi^2)$. Cada sección le aplica una herramienta: se simula con un bucle, se estima por mínimos cuadrados con matrices, se estudia su estabilidad con autovalores, se construye su distribución muestral por bootstrap y se estima con un muestreador de Gibbs. Quien entiende el AR(1) con estas herramientas ya entiende el VAR: es el mismo cálculo con matrices en lugar de escalares.\n\n## [0.2]{.header-section-number} Python en lo esencial {#sec-prelim-python .unnumbered}\n\nEl entorno del libro se instala con [uv](https://docs.astral.sh/uv/), que descarga la versión correcta de Python y fija la de cada paquete: `uv sync` en la carpeta del repositorio y `uv run jupyter lab` para trabajar en cuadernos. La presentación del libro explica los detalles. Todo el código se puede ejecutar celda por celda, en el orden en que aparece.\n\nPython tiene pocos tipos básicos y conviene conocerlos antes que nada. Los números y las cadenas de texto se comportan como se espera; las **listas** guardan secuencias que pueden cambiar; las **tuplas**, secuencias fijas; y los **diccionarios** asocian claves con valores, que es como se pasan opciones con nombre.\n\n::: {#prelim-tipos .cell execution_count=1}\n``` {.python .cell-code}\nphi = 0.8                         # float\nname = \"inflación\"                # str\nlags = [1, 2, 4]                  # list: mutable\nshape = (200, 3)                  # tuple: fixed\nprior = {\"lambda1\": 0.2, \"lambda2\": 0.5}   # dict\n\nprint(lags[0], lags[-1], lags[1:])\nprint(prior[\"lambda1\"], shape[0])\nprint(f\"{name}: phi = {phi:.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n1 4 [2, 4]\n0.2 200\ninflación: phi = 0.80\n```\n:::\n:::\n\n\nLa primera línea impresa resume las dos convenciones que más confunden a quien llega de MATLAB: los índices **empiezan en cero**, de modo que `lags[0]` es el primer elemento, y los cortes `a:b` **incluyen `a` y excluyen `b`**. El índice `-1` es el último elemento. En series de tiempo esto importa todo el tiempo: `y[1:]` son las observaciones de la 2 a la $T$ y `y[:-1]` las de la 1 a la $T-1$, justo los dos vectores que se alinean para regresar $y_t$ sobre $y_{t-1}$.\n\nUna recursión se escribe con un **bucle** `for`, y un bloque de código que se va a reutilizar se envuelve en una **función**. La función de abajo simula el AR(1): recibe los parámetros, crea un generador de números aleatorios con semilla (se discute en la [sección 0.10](#sec-prelim-distribuciones)) y recorre el tiempo aplicando la ecuación del modelo.\n\n::: {#prelim-ar1 .cell execution_count=2}\n``` {.python .cell-code}\nimport numpy as np\n\n\ndef simulate_ar1(c, phi, sigma, T, seed=None):\n    \"\"\"Simulate y_t = c + phi y_{t-1} + sigma e_t, e_t ~ N(0,1).\n\n    The first value is the unconditional mean, so the path\n    starts in the stationary region when |phi| < 1.\n    \"\"\"\n    rng = np.random.default_rng(seed)\n    y = np.empty(T)\n    y[0] = c / (1 - phi)\n    for t in range(1, T):\n        shock = sigma * rng.standard_normal()\n        y[t] = c + phi * y[t - 1] + shock\n    return y\n\n\nc, phi, sigma = 0.5, 0.8, 1.0\ny = simulate_ar1(c, phi, sigma, T=200, seed=11)\n\nmean_theory = c / (1 - phi)\nvar_theory = sigma**2 / (1 - phi**2)\nprint(f\"media:    {y.mean():.2f}  (teórica {mean_theory:.2f})\")\nprint(f\"varianza: {y.var():.2f}  (teórica {var_theory:.2f})\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nmedia:    2.60  (teórica 2.50)\nvarianza: 2.17  (teórica 2.78)\n```\n:::\n:::\n\n\nCon 200 observaciones, la media muestral queda cerca de la teórica, pero la varianza queda un 20 % por debajo. No hay error en el código: con $\\phi = 0.8$ cada observación trae poca información nueva respecto de la anterior, y la muestra efectiva es mucho menor que 200. Es la primera aparición de un tema que vuelve en todo el libro, el de la persistencia como enemiga de la precisión.\n\nTres detalles de la función se repiten en todo el código del libro. La cadena entre comillas triples es la **documentación** (*docstring*), que se consulta con `help(simulate_ar1)`. Los argumentos con valor por defecto, como `seed=None`, son opcionales y se pasan por nombre. Y la función **devuelve** un resultado en lugar de imprimirlo, de modo que se puede seguir usando.\n\nPara aprender el lenguaje con más calma hay tres recursos excelentes y gratuitos: el [tutorial oficial de Python](https://docs.python.org/3/tutorial/), [*Python Programming for Economics and Finance*](https://python-programming.quantecon.org/intro.html) de QuantEcon [@sargent_python] y [*Coding for Economists*](https://aeturrell.github.io/coding-for-economists/) [@turrell_coding], este último pensado para economistas que hacen investigación aplicada.\n\n## [0.3]{.header-section-number} Vectores y matrices con NumPy {#sec-prelim-numpy .unnumbered}\n\nNumPy [@harris2020] es la base de todo el cálculo numérico en Python. Su objeto central es el **arreglo** (`ndarray`): una tabla de números de un solo tipo, con una forma (`shape`) que dice cuántas dimensiones tiene y cuántos elementos hay en cada una.\n\n::: {#prelim-arreglos .cell execution_count=3}\n``` {.python .cell-code}\na = np.array([1.0, 2.0, 3.0])            # 1-D, shape (3,)\nA = np.array([[2.0, 1.0],\n              [1.0, 3.0]])               # 2-D, shape (2, 2)\nb = np.array([1.0, 2.0])\n\nprint(a.shape, A.shape)\nprint(\"A * A  =\", (A * A).ravel())       # element by element\nprint(\"A @ A  =\", (A @ A).ravel())       # matrix product\nprint(\"A' b   =\", A.T @ b)\nprint(\"x: A x = b ->\", np.linalg.solve(A, b))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n(3,) (2, 2)\nA * A  = [4. 1. 1. 9.]\nA @ A  = [ 5.  5.  5. 10.]\nA' b   = [4. 7.]\nx: A x = b -> [0.2 0.6]\n```\n:::\n:::\n\n\nCuatro operaciones cubren casi todo el libro. El **producto matricial** se escribe `@`; el asterisco `*` multiplica elemento por elemento. La **transpuesta** es `.T`. Para resolver un sistema $Ax = b$ se usa `np.linalg.solve(A, b)`, no `np.linalg.inv(A) @ b`: el resultado es el mismo en aritmética exacta, pero `solve` es más rápido y numéricamente más estable, porque no calcula una inversa que no hace falta. Y la **difusión** (*broadcasting*) permite operar arreglos de formas distintas cuando una dimensión vale uno: `X - X.mean(axis=0)` resta a cada columna su media sin escribir un bucle.\n\nCon eso se escribe el estimador de mínimos cuadrados. Apilando la ecuación del AR(1) para $t = 2, \\ldots, T$,\n\n$$ \\underbrace{\\begin{bmatrix} y_2 \\\\ y_3 \\\\ \\vdots \\\\ y_T \\end{bmatrix}}_{Y} = \\underbrace{\\begin{bmatrix} 1 & y_1 \\\\ 1 & y_2 \\\\ \\vdots & \\vdots \\\\ 1 & y_{T-1} \\end{bmatrix}}_{X} \\begin{bmatrix} c \\\\ \\phi \\end{bmatrix} + \\begin{bmatrix} \\varepsilon_2 \\\\ \\varepsilon_3 \\\\ \\vdots \\\\ \\varepsilon_T \\end{bmatrix}, \\qquad \\hat{\\beta} = (X'X)^{-1} X'Y , $$\n\ncon varianza estimada $\\hat{\\sigma}^2 (X'X)^{-1}$, donde $\\hat{\\sigma}^2$ es la suma de residuos al cuadrado dividida por $T - 1 - 2$. En código:\n\n::: {#prelim-mco .cell execution_count=4}\n``` {.python .cell-code}\nX = np.column_stack([np.ones(len(y) - 1), y[:-1]])\nY = y[1:]\n\nbeta = np.linalg.solve(X.T @ X, X.T @ Y)\nresid = Y - X @ beta\ns2 = resid @ resid / (len(Y) - X.shape[1])\nse = np.sqrt(np.diag(s2 * np.linalg.inv(X.T @ X)))\n\nfor name, b_, s_ in zip([\"c\", \"phi\"], beta, se):\n    print(f\"{name:>4}: {b_:.3f}  (e.e. {s_:.3f})\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   c: 0.559  (e.e. 0.134)\n phi: 0.783  (e.e. 0.045)\n```\n:::\n:::\n\n\nLa estimación está cerca de los valores con que se simuló, $c = 0.5$ y $\\phi = 0.8$, y a menos de un error estándar de cada uno. El VAR del [capítulo 3](03-var.qmd#sec-var-mco) se estima con esta misma fórmula: como todas las ecuaciones comparten los regresores $X$, basta reemplazar el vector $Y$ por la matriz que tiene una columna por variable, $\\hat{B} = (X'X)^{-1}X'Y$.\n\nLos bucles de Python son lentos comparados con las operaciones de NumPy, que se ejecutan en código compilado. Por eso se **vectoriza**: se reemplaza un bucle sobre elementos por una operación sobre el arreglo entero.\n\n::: {#prelim-vectorizar .cell execution_count=5}\n``` {.python .cell-code}\nimport time\n\nbig = simulate_ar1(c, phi, sigma, T=100_000, seed=2)\n\nstart = time.perf_counter()\ntotal = 0.0\nfor value in big:\n    total += value * value\nloop_time = time.perf_counter() - start\n\nstart = time.perf_counter()\ntotal_vec = big @ big\nvec_time = time.perf_counter() - start\n\nprint(f\"mismo resultado: {np.isclose(total, total_vec)}\")\nprint(f\"el bucle tarda {loop_time / vec_time:.0f} veces más\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nmismo resultado: True\nel bucle tarda 84 veces más\n```\n:::\n:::\n\n\nLa proporción exacta depende de la máquina y cambia de una ejecución a otra, pero ronda los dos órdenes de magnitud a favor de la versión vectorizada. No todo se puede vectorizar: una recursión como la del AR(1) necesita el valor anterior para calcular el siguiente, y ahí el bucle es la forma natural de escribirla. La regla práctica es escribir primero la versión clara y vectorizar sólo lo que de verdad pesa.\n\n::: {.cuidado}\nUn arreglo de una dimensión no es un vector columna ni un vector fila: no tiene orientación, y `a.T` lo deja igual. Si hace falta un vector columna, `a.reshape(-1, 1)` lo construye; si hace falta el producto exterior $aa'$, `np.outer(a, a)`. Confundir `*` con `@` es el otro error clásico, y no siempre da un error de forma: con matrices cuadradas ambos productos funcionan y dan resultados distintos.\n:::\n\nQuien llega de MATLAB encontrará útil la [tabla de equivalencias de NumPy para usuarios de MATLAB](https://numpy.org/doc/stable/user/numpy-for-matlab-users.html). Para el álgebra lineal detrás de todo esto, la [lección de álgebra lineal de QuantEcon](https://python.quantecon.org/linear_algebra.html) [@sargent_intermediate] y el [curso 18.06 de Gilbert Strang en el MIT](https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/) [@strang2016] son las dos referencias más recomendables.\n\n## [0.4]{.header-section-number} Potencias, autovalores y estabilidad {#sec-prelim-autovalores .unnumbered}\n\nUn VAR(1) sin constante, $\\mathbf{y}_t = A\\,\\mathbf{y}_{t-1} + \\mathbf{u}_t$, se puede resolver hacia atrás sustituyendo el rezago una y otra vez:\n\n$$ \\mathbf{y}_t = A^{t}\\mathbf{y}_0 + \\sum_{j=0}^{t-1} A^{j}\\mathbf{u}_{t-j} . $$\n\nTodo depende entonces de qué pasa con las **potencias** $A^j$. Si convergen a cero, la condición inicial se olvida y un choque de hace $j$ periodos pesa cada vez menos. Si no convergen, el sistema no vuelve nunca a su media.\n\nLa herramienta para saberlo son los **autovalores** (o valores propios). Un escalar $\\lambda$ y un vector $v \\neq 0$ son autovalor y autovector de $A$ si $Av = \\lambda v$: en la dirección $v$, multiplicar por $A$ equivale a multiplicar por $\\lambda$. Si $A$ tiene $n$ autovectores independientes, reunidos en las columnas de $V$, se puede escribir $A = V \\Lambda V^{-1}$ con $\\Lambda$ diagonal, y entonces\n\n$$ A^j = V \\Lambda^j V^{-1}, \\qquad \\Lambda^j = \\operatorname{diag}(\\lambda_1^j, \\ldots, \\lambda_n^j). $$\n\nLas potencias de $A$ se reducen a potencias de escalares. De ahí sale la condición de estabilidad: $A^j \\to 0$ si y sólo si todos los autovalores tienen módulo menor que uno, es decir si el **radio espectral** $\\rho(A) = \\max_i |\\lambda_i|$ es menor que uno. Si un autovalor es complejo, $\\lambda = r e^{\\pm i\\omega}$, su potencia $r^j e^{\\pm i\\omega j}$ gira mientras se achica: la respuesta **oscila** con periodo $2\\pi/\\omega$ y se amortigua al ritmo $r^j$. Los VAR macroeconómicos suelen tener autovalores complejos, y por eso sus respuestas al impulso tienen forma de joroba o de onda.\n\n::: {#prelim-eig .cell execution_count=6}\n``` {.python .cell-code}\ncases = {\n    \"reales\":  np.array([[0.6, 0.2], [0.1, 0.5]]),\n    \"complejos\": np.array([[0.9, -0.4], [0.3, 0.7]]),\n    \"raíz unitaria\": np.array([[1.0, 0.1], [0.0, 0.6]]),\n}\nfor label, A in cases.items():\n    lam = np.linalg.eigvals(A)\n    print(f\"{label:>13}: {np.round(lam, 3)}  \"\n          f\"radio espectral {np.abs(lam).max():.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       reales: [0.7 0.4]  radio espectral 0.700\n    complejos: [0.8+0.332j 0.8-0.332j]  radio espectral 0.866\nraíz unitaria: [1.  0.6]  radio espectral 1.000\n```\n:::\n:::\n\n\n::: {.cell execution_count=7}\n``` {.python .cell-code}\nimport matplotlib.pyplot as plt\n\nfrom macrobook import use_style, figsize, PALETTE, charts\n\nuse_style()\n\nhorizon = np.arange(31)\nsize = figsize(0.32)\nfig, axes = plt.subplots(1, 3, figsize=size, sharey=True)\nfor ax, (label, A) in zip(axes, cases.items()):\n    path = [np.linalg.matrix_power(A, j)[0, 0]\n            for j in horizon]\n    ax.plot(horizon, path, color=PALETTE[\"ink\"], lw=1.2)\n    charts.zero_line(ax)\n    ax.set_title(label, fontsize=8.5)\n    ax.set_xlabel(\"periodos\")\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Respuesta de la primera variable a un choque unitario en ella misma, $(A^j)_{11}$, para las tres matrices. Con autovalores reales la respuesta decae sin cambiar de signo; con autovalores complejos oscila mientras se amortigua; con un autovalor igual a uno no vuelve a cero.](00-preliminares_files/figure-pdf/fig-prelim-autovalores-output-1.pdf){#fig-prelim-autovalores fig-pos='H'}\n:::\n:::\n\n\nUn AR(2) se analiza igual, después de escribirlo como un VAR(1) en el vector $(y_t, y_{t-1})'$. La matriz de ese sistema es la **companion**, y sus autovalores son las raíces inversas del polinomio de rezagos:\n\n$$ \\begin{bmatrix} y_t \\\\ y_{t-1} \\end{bmatrix} = \\underbrace{\\begin{bmatrix} \\phi_1 & \\phi_2 \\\\ 1 & 0 \\end{bmatrix}}_{F} \\begin{bmatrix} y_{t-1} \\\\ y_{t-2} \\end{bmatrix} + \\begin{bmatrix} \\varepsilon_t \\\\ 0 \\end{bmatrix} . $$\n\n::: {#prelim-companion .cell execution_count=8}\n``` {.python .cell-code}\nphi1, phi2 = 1.3, -0.6\nF = np.array([[phi1, phi2],\n              [1.0, 0.0]])\nlam = np.linalg.eigvals(F)\nperiod = 2 * np.pi / abs(np.angle(lam[0]))\n\nprint(\"autovalores:\", np.round(lam, 3))\nprint(f\"módulo {abs(lam[0]):.3f}, periodo {period:.1f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nautovalores: [0.65+0.421j 0.65-0.421j]\nmódulo 0.775, periodo 10.9\n```\n:::\n:::\n\n\nCon $\\phi_1 = 1.3$ y $\\phi_2 = -0.6$ los autovalores son complejos de módulo 0.775: el proceso es estable y sus ciclos duran unos once periodos, que en datos trimestrales es la duración de un ciclo económico corto. Así se lee la estabilidad de un VAR($p$) en el [capítulo 3](03-var.qmd#sec-var-companion): se escribe en forma companion y se miran los autovalores de $F$. Las respuestas al impulso del [capítulo 4](04-svar.qmd#sec-svar-irf) son exactamente las potencias $F^j$, recortadas por la matriz de selección $J$.\n\n::: {.cuidado}\nLos autovalores de una matriz no simétrica pueden ser complejos: el módulo se calcula con `np.abs`, no con el valor absoluto de la parte real, y NumPy no los devuelve en ningún orden particular. Para matrices simétricas, como una covarianza, conviene `np.linalg.eigh`, que es más rápida, garantiza autovalores reales y los ordena de menor a mayor.\n:::\n\nLa lección [*Eigenvalues and Eigenvectors*](https://intro.quantecon.org/eigen_I.html) de QuantEcon desarrolla la intuición geométrica con más detalle, y el apéndice A de @lutkepohl2005 reúne los resultados de álgebra matricial que usan los VAR.\n\n## [0.5]{.header-section-number} Determinantes y factorizaciones {#sec-prelim-factorizaciones .unnumbered}\n\nEl **determinante** de una matriz cuadrada es el producto de sus autovalores, $\\det(A) = \\prod_i \\lambda_i$, y mide cuánto multiplica $A$ los volúmenes. Una matriz es invertible si y sólo si su determinante no es cero. En el libro aparece en dos lugares: en la condición de estabilidad del VAR, que el [capítulo 3](03-var.qmd#sec-var-estabilidad) escribe como $\\det(I_n - \\Phi_1 z - \\cdots - \\Phi_p z^p) \\neq 0$ para $|z| \\leq 1$, y en la densidad de la normal multivariada, donde $|\\Sigma|^{-1/2}$ ajusta la escala.\n\nCasi nunca hace falta el determinante en sí, sino su logaritmo, y conviene calcularlo sin pasar por el determinante: con muchas variables, $\\det(\\Sigma)$ puede ser tan grande o tan pequeño que se sale del rango de los números de máquina, mientras que su logaritmo no. Ahí entra la factorización más útil del libro.\n\n**Cholesky.** Toda matriz simétrica definida positiva, como una covarianza, se escribe de una única manera como\n\n$$ \\Sigma = L L', $$\n\ncon $L$ triangular inferior y diagonal positiva. Es la raíz cuadrada de una matriz. Sirve para tres cosas. La primera, calcular $\\log|\\Sigma| = 2\\sum_i \\log L_{ii}$ sin riesgo numérico. La segunda, simular: si $z \\sim N(0, I)$, entonces $u = Lz$ tiene covarianza $\\mathbb{E}[Lzz'L'] = LL' = \\Sigma$. La tercera, que es la del [capítulo 4](04-svar.qmd#sec-svar-cholesky): esa misma identidad, escrita $\\mathbf{u}_t = S\\varepsilon_t$ con $S = L$, es la identificación recursiva de un VAR estructural.\n\n::: {#prelim-cholesky .cell execution_count=9}\n``` {.python .cell-code}\nSigma = np.array([[1.0, 0.5],\n                  [0.5, 2.0]])\nL = np.linalg.cholesky(Sigma)\nprint(\"L =\\n\", np.round(L, 3))\n\nsign, logdet = np.linalg.slogdet(Sigma)\nprint(f\"log|Sigma|: {logdet:.4f} (slogdet), \"\n      f\"{2 * np.log(np.diag(L)).sum():.4f} (Cholesky)\")\n\nrng = np.random.default_rng(3)\nz = rng.standard_normal((100_000, 2))\nu = z @ L.T                      # each row is L z_t\nprint(\"covarianza simulada:\\n\", np.round(np.cov(u.T), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nL =\n [[1.    0.   ]\n [0.5   1.323]]\nlog|Sigma|: 0.5596 (slogdet), 0.5596 (Cholesky)\ncovarianza simulada:\n [[0.997 0.496]\n [0.496 1.996]]\n```\n:::\n:::\n\n\n::: {.cell execution_count=10}\n``` {.python .cell-code}\nsize = figsize(0.50)\nfig, axes = plt.subplots(1, 2, figsize=size)\nfor ax, data, title in [(axes[0], z[:2000], \"z ~ N(0, I)\"),\n                        (axes[1], u[:2000], \"u = L z\")]:\n    ax.scatter(data[:, 0], data[:, 1], s=2, alpha=0.4,\n               color=PALETTE[\"steel\"], lw=0)\n    ax.set_xlim(-5, 5)\n    ax.set_ylim(-5, 5)\n    ax.set_aspect(\"equal\", adjustable=\"box\")\n    ax.set_title(title, fontsize=8.5)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Dos mil extracciones de una normal estándar bivariada (izquierda) y las mismas extracciones multiplicadas por el factor de Cholesky de $\\Sigma$ (derecha). $L$ estira la nube en la dirección de la segunda variable y la inclina según la correlación.](00-preliminares_files/figure-pdf/fig-prelim-cholesky-output-1.pdf){#fig-prelim-cholesky fig-pos='H'}\n:::\n:::\n\n\n**Matrices ortogonales.** Una matriz $Q$ es ortogonal si $QQ' = I$: rota o refleja sin cambiar longitudes. Si $\\Sigma = LL'$, entonces para cualquier $Q$ ortogonal\n\n$$ (LQ)(LQ)' = L\\,QQ'\\,L' = LL' = \\Sigma , $$\n\nde modo que $LQ$ es otra \"raíz cuadrada\" igual de válida. La descomposición $QR$ de una matriz de normales independientes produce una $Q$ ortogonal extraída al azar de manera uniforme, con una corrección de signos para que la distribución sea exactamente la uniforme:\n\n::: {#prelim-qr .cell execution_count=11}\n``` {.python .cell-code}\nrng = np.random.default_rng(4)\nQ, R = np.linalg.qr(rng.standard_normal((2, 2)))\nQ = Q * np.sign(np.diag(R))        # Haar-uniform rotation\n\nS = L @ Q\nprint(\"Q Q' = I:\", np.allclose(Q @ Q.T, np.eye(2)))\nprint(\"S S' = Sigma:\", np.allclose(S @ S.T, Sigma))\nprint(\"S =\\n\", np.round(S, 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nQ Q' = I: True\nS S' = Sigma: True\nS =\n [[-0.365  0.931]\n [ 1.049  0.948]]\n```\n:::\n:::\n\n\nEsas líneas son el problema de identificación del [capítulo 4](04-svar.qmd#sec-svar-identificacion) en miniatura. La covarianza de los residuos no distingue entre $L$ y $LQ$, así que los datos solos no dicen cuál es la matriz de impacto correcta. La identificación recursiva elige $L$; las [restricciones de signo](04-svar.qmd#sec-svar-signo) recorren muchas $Q$ y se quedan con las que producen respuestas de signo razonable.\n\n## [0.6]{.header-section-number} Producto de Kronecker y el operador vec {#sec-prelim-kronecker .unnumbered}\n\nDos operaciones permiten escribir un sistema de ecuaciones como una sola regresión, y el [capítulo 5](05-bvar.qmd#sec-bvar-vectorizada) no se entiende sin ellas.\n\nEl operador $\\operatorname{vec}$ apila las **columnas** de una matriz en un solo vector:\n\n$$ \\operatorname{vec}\\begin{bmatrix} a & c \\\\ b & d \\end{bmatrix} = \\begin{bmatrix} a \\\\ b \\\\ c \\\\ d \\end{bmatrix} . $$\n\nEl **producto de Kronecker** de $A$ ($m \\times n$) y $B$ ($p \\times q$) es la matriz de bloques $mp \\times nq$ que multiplica cada elemento de $A$ por la matriz $B$ entera:\n\n$$ A \\otimes B = \\begin{bmatrix} a_{11} B & \\cdots & a_{1n} B \\\\ \\vdots & \\ddots & \\vdots \\\\ a_{m1} B & \\cdots & a_{mn} B \\end{bmatrix} . $$\n\nCuatro reglas bastan para todo el libro:\n\n$$ (A \\otimes B)(C \\otimes D) = AC \\otimes BD, \\quad (A \\otimes B)^{-1} = A^{-1} \\otimes B^{-1}, \\quad (A \\otimes B)' = A' \\otimes B', $$\n\n$$ \\operatorname{vec}(ABC) = (C' \\otimes A)\\operatorname{vec}(B) . $$\n\nLa última es la que se usa: con $A = X$, $B$ la matriz de coeficientes y $C = I_n$, dice que $\\operatorname{vec}(XB) = (I_n \\otimes X)\\operatorname{vec}(B)$. Aplicada a $Y = XB + U$, convierte el VAR en la regresión $y = (I_n \\otimes X)\\,b + u$ sobre el vector de todos los coeficientes, que es donde el [capítulo 5](05-bvar.qmd#sec-bvar-vectorizada) pone el prior.\n\n::: {#prelim-kron .cell execution_count=12}\n``` {.python .cell-code}\ndef vec(M):\n    \"\"\"Stack the columns of M (column-major order).\"\"\"\n    return M.flatten(order=\"F\")\n\n\nrng = np.random.default_rng(5)\nA = rng.standard_normal((2, 3))\nB = rng.standard_normal((3, 4))\nC = rng.standard_normal((4, 2))\n\nleft = vec(A @ B @ C)\nright = np.kron(C.T, A) @ vec(B)\nprint(\"vec(ABC) = (C' kron A) vec(B):\",\n      np.allclose(left, right))\n\nM = np.array([[1, 2, 3],\n              [4, 5, 6]])\nprint(\"vec(M):         \", vec(M))\nprint(\"M.flatten():    \", M.flatten())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nvec(ABC) = (C' kron A) vec(B): True\nvec(M):          [1 4 2 5 3 6]\nM.flatten():     [1 2 3 4 5 6]\n```\n:::\n:::\n\n\n::: {.cuidado}\nNumPy guarda y recorre las matrices **por filas**, y $\\operatorname{vec}$ apila **columnas**. `M.flatten()` devuelve las filas una tras otra y no es $\\operatorname{vec}(M)$; hay que escribir `M.flatten(order=\"F\")`, y para volver atrás, `reshape(..., order=\"F\")`. El error es silencioso: las formas coinciden y el resultado está mal. En el [capítulo 5](05-bvar.qmd#sec-bvar-gibbs) todas las conversiones entre $B$ y $b$ llevan `order=\"F\"` por esta razón.\n:::\n\nUn producto de Kronecker crece rápido: $\\Sigma \\otimes I_T$ con siete variables y 200 observaciones es una matriz de $1400 \\times 1400$. Las fórmulas del libro están escritas para no formarlo nunca, aprovechando la primera regla: $\\Sigma^{-1} \\otimes X'X$ es sólo de $nk \\times nk$.\n\n## [0.7]{.header-section-number} Series y fechas con pandas {#sec-prelim-pandas .unnumbered}\n\npandas [@mckinney2010] agrega a NumPy lo que falta para trabajar con datos: nombres para las columnas y, sobre todo, un **índice** que en series de tiempo son las fechas. Sus dos objetos son la `Series`, una columna con índice, y el `DataFrame`, una tabla de columnas que comparten el índice.\n\n::: {#prelim-pandas .cell execution_count=13}\n``` {.python .cell-code}\nimport pandas as pd\n\nfrom macrobook import data_path\n\nperu = pd.read_csv(data_path(\"peru_monthly.csv\"),\n                   index_col=\"date\")\nperu.index = pd.PeriodIndex(peru.index, freq=\"M\")\ncpi = peru[\"cpi\"].dropna()\n\nprint(type(peru).__name__, peru.shape)\nprint(cpi.tail(3))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nDataFrame (368, 4)\ndate\n2026-06    120.292167\n2026-07    120.635759\n2026-08    120.716351\nFreq: M, Name: cpi, dtype: float64\n```\n:::\n:::\n\n\nEl índice es un `PeriodIndex` de frecuencia mensual: cada elemento representa un **mes entero**, no un instante. Es la representación natural de datos macroeconómicos, que son flujos o promedios de un periodo. La alternativa, un `DatetimeIndex`, representa instantes, y es la que piden algunas funciones y los gráficos; se pasa de una a otra con `.to_timestamp()` y `.to_period()`. La aritmética con periodos respeta el calendario, de modo que sumar doce meses a abril de 2021 da abril de 2022.\n\n::: {#prelim-fechas .cell execution_count=14}\n``` {.python .cell-code}\nimport datetime\n\napril = pd.Period(\"2021-04\", freq=\"M\")\nprint(april + 12, \"|\", april.to_timestamp(how=\"end\").date())\nprint(april.quarter, april.year, april.days_in_month)\nprint(datetime.date(2021, 4, 30) - datetime.date(2020, 4, 30))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n2022-04 | 2021-04-30\n2 2021 30\n365 days, 0:00:00\n```\n:::\n:::\n\n\nLas transformaciones del [capítulo 1](01-macro-data.qmd#sec-datos-transformaciones) son operaciones de una línea. `shift(k)` desplaza la serie $k$ periodos, de modo que `cpi / cpi.shift(12)` divide cada mes por el mismo mes del año anterior; `np.log(cpi).diff()` es la diferencia logarítmica; y la selección por fechas funciona con cadenas, `cpi[\"2002\":]`. Para cambiar de frecuencia se usa `resample`, y para agrupar por una característica de la fecha, `groupby`.\n\n::: {#prelim-transformar .cell execution_count=15}\n``` {.python .cell-code}\ninfl_yoy = 100 * (cpi / cpi.shift(12) - 1)\ninfl_mom = 100 * np.log(cpi).diff()\ncpi_q = cpi.resample(\"Q\").mean()\nby_month = infl_mom.groupby(infl_mom.index.month).mean()\n\nprint(f\"inflación interanual, {infl_yoy.index[-1]}: \"\n      f\"{infl_yoy.iloc[-1]:.2f} %\")\nprint(f\"IPC trimestral: {len(cpi_q)} trimestres, \"\n      f\"el último {cpi_q.index[-1]}\")\nprint(\"variación mensual media por mes (%):\")\nprint(by_month.round(2).to_string())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ninflación interanual, 2026-08: 4.44 %\nIPC trimestral: 123 trimestres, el último 2026Q3\nvariación mensual media por mes (%):\ndate\n1     0.20\n2     0.37\n3     0.84\n4     0.28\n5     0.18\n6     0.20\n7     0.39\n8     0.24\n9     0.19\n10    0.13\n11    0.09\n12    0.33\n```\n:::\n:::\n\n\nEl promedio por mes es la versión más cruda de un factor estacional: marzo concentra el alza de precios de la temporada escolar. El [capítulo 1](01-macro-data.qmd#sec-datos-desestacionalizar) explica cómo estimar ese factor con métodos que permiten que cambie de un año a otro.\n\nUn último ejemplo combina fechas y selección lógica. El BCRP adoptó metas de inflación en 2002, con una meta de 2.5 % y un rango de tolerancia de un punto, y en febrero de 2007 la bajó a 2 % con el mismo rango [@velarde2023]. Construir el rango como una serie con el mismo índice permite comparar mes a mes:\n\n::: {#prelim-meta .cell execution_count=16}\n``` {.python .cell-code}\nsince = infl_yoy[\"2002\":]\nlow = pd.Series(1.5, index=since.index)\nhigh = pd.Series(3.5, index=since.index)\nlow[\"2007-02\":] = 1.0\nhigh[\"2007-02\":] = 3.0\n\ninside = (since >= low) & (since <= high)\nabove = since > high\nprint(f\"dentro del rango: {inside.mean():.0%}, \"\n      f\"por encima: {above.mean():.0%}\")\nprint(f\"máximo: {since.max():.2f} % en {since.idxmax()}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ndentro del rango: 46%, por encima: 42%\nmáximo: 8.81 % en 2022-06\n```\n:::\n:::\n\n\nLa inflación estuvo dentro del rango en algo menos de la mitad de los meses desde 2002, y cuando salió fue sobre todo por arriba. Las salidas no son meses sueltos sino episodios largos, que coinciden con choques externos de precios: el alza mundial de alimentos y combustibles de 2007-2008 y la de 2021-2022, que dejó la inflación por encima del rango casi tres años. Es un dato para tener presente al leer los VAR peruanos del [capítulo 3](03-var.qmd), que tratan esos episodios como parte de la dinámica normal del sistema.\n\nLa referencia para pandas es el libro de su creador, [*Python for Data Analysis*](https://wesmckinney.com/book/) [@mckinney2022], gratuito en línea; la [guía de series de tiempo de pandas](https://pandas.pydata.org/docs/user_guide/timeseries.html) cubre fechas, frecuencias y ventanas móviles en detalle.\n\n## [0.8]{.header-section-number} Gráficos con matplotlib {#sec-prelim-graficos .unnumbered}\n\nmatplotlib [@hunter2007] dibuja con dos objetos: la **figura**, que es el lienzo, y los **ejes**, que son cada panel. `plt.subplots(filas, columnas)` crea ambos, y después se dibuja llamando a los métodos de cada eje: `ax.plot`, `ax.fill_between`, `ax.set_title`. Trabajar siempre con los ejes explícitos, en lugar de las funciones sueltas de `plt`, evita la mayoría de las sorpresas cuando hay más de un panel.\n\nEl libro agrega tres convenciones, reunidas en el paquete `macrobook`. `use_style()` aplica una sola hoja de estilo a todas las figuras, de modo que ningún capítulo elige tipografías ni colores por su cuenta. `figsize(ratio)` devuelve el tamaño de la figura como una proporción del ancho de la columna, que es distinto en la web y en el PDF. Y `PALETTE` y `charts` reúnen los colores y los gráficos que se repiten: líneas de referencia, leyendas, bandas, abanicos.\n\n::: {.cell execution_count=17}\n``` {.python .cell-code}\ndates = since.index.to_timestamp(how=\"end\")\n\nsize = figsize(0.40)\nfig, ax = plt.subplots(figsize=size)\nax.fill_between(dates, low, high, step=\"mid\", lw=0,\n                color=PALETTE[\"surface_strong\"],\n                label=\"rango de la meta\")\nax.plot(dates, since, color=PALETTE[\"accent\"], lw=1.2,\n        label=\"inflación interanual\")\nax.set_ylabel(\"%\")\ncharts.year_ticks(ax, every=4)\ncharts.legend_outside(ax, ncol=2)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Inflación interanual del Perú y el rango de la meta del BCRP: 1.5 a 3.5 % entre 2002 y enero de 2007, 1 a 3 % desde entonces.](00-preliminares_files/figure-pdf/fig-prelim-inflacion-output-1.pdf){#fig-prelim-inflacion fig-pos='H'}\n:::\n:::\n\n\nLa [guía de inicio rápido de matplotlib](https://matplotlib.org/stable/users/explain/quick_start.html) explica la relación entre figura y ejes, y el cuarto capítulo del [*Python Data Science Handbook*](https://jakevdp.github.io/PythonDataScienceHandbook/) [@vanderplas2016] recorre los tipos de gráfico más comunes.\n\n## [0.9]{.header-section-number} Organizar el código: módulos y clases {#sec-prelim-clases .unnumbered}\n\nEl código del libro vive en dos lugares con dos estilos distintos, y conviene reconocerlos.\n\nEl paquete **`macrobook`**, que acompaña al libro, está hecho de **funciones** agrupadas en **módulos**: `var` para la mecánica del VAR, `svar` para la identificación y el análisis estructural, `bvar` para el VAR bayesiano. Cada función hace un solo paso, recibe arreglos y devuelve arreglos. Es el estilo que conviene para aprender, porque cada paso del algoritmo queda a la vista.\n\n::: {#prelim-modulos .cell execution_count=18}\n``` {.python .cell-code}\nfrom macrobook import var\n\nfit = var.ols(y.reshape(-1, 1), p=1)   # a VAR(1) with n = 1\nprint(sorted(fit))\nprint(\"B =\", np.round(fit[\"B\"].ravel(), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n['B', 'Sigma', 'T', 'X', 'Y', 'constant', 'k', 'p', 'residuals']\nB = [0.559 0.783]\n```\n:::\n:::\n\n\nEl VAR de una variable y un rezago es el AR(1), y la función del [capítulo 3](03-var.qmd#sec-var-mco) devuelve los mismos coeficientes que se calcularon a mano en la [sección 0.3](#sec-prelim-numpy), con la constante en la primera fila de $B$.\n\n**`MacroPy`**, la biblioteca que el libro usa como tercer nivel, está hecha de **clases**. Una clase agrupa datos y las operaciones sobre esos datos: se construye un **objeto** una vez, con los datos y las opciones, y después se le piden cosas. Lo que el objeto sabe son sus **atributos**; lo que sabe hacer, sus **métodos**. Una clase mínima para el AR(1) muestra el patrón:\n\n::: {#prelim-clase .cell execution_count=19}\n``` {.python .cell-code}\nclass AR1:\n    \"\"\"AR(1) with an intercept, estimated by OLS.\"\"\"\n\n    def __init__(self, y):\n        self.y = np.asarray(y, dtype=float)\n\n    def fit(self):\n        X = np.column_stack([np.ones(len(self.y) - 1),\n                             self.y[:-1]])\n        self.c, self.phi = np.linalg.solve(\n            X.T @ X, X.T @ self.y[1:])\n        return self                     # allows chaining\n\n    def forecast(self, h):\n        path, last = [], self.y[-1]\n        for _ in range(h):\n            last = self.c + self.phi * last\n            path.append(last)\n        return np.array(path)\n\n\nmodel = AR1(y).fit()\nprint(f\"phi = {model.phi:.3f}\")\nprint(\"pronóstico:\", np.round(model.forecast(4), 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nphi = 0.783\npronóstico: [1.16 1.47 1.71 1.89]\n```\n:::\n:::\n\n\n`__init__` se ejecuta al crear el objeto y guarda los datos en `self`, que es el propio objeto. `fit` estima y guarda los coeficientes como atributos. `forecast` los usa. MacroPy funciona igual, con clases más completas. El fragmento siguiente, que no se ejecuta aquí, es el patrón que aparece en el [capítulo 4](04-svar.qmd#sec-svar-fevd):\n\n::: {#prelim-macropy .cell execution_count=20}\n``` {.python .cell-code}\nfrom MacroPy import ClassicVAR\n\nmodel = ClassicVAR(data, lags=4)      # data go in once\nmodel.Sigma_ols                        # estimates: attributes\nmodel.compute_fevd(plot_fevd=False)    # analyses: methods\n```\n:::\n\n\n::: {.cuidado}\nUn valor por defecto mutable, como una lista o un diccionario, se crea **una sola vez**, cuando se define la función, y se comparte entre todas las llamadas. Si la función lo modifica, la modificación persiste en la llamada siguiente. Por eso los argumentos opcionales que son diccionarios, como los hiperparámetros de un prior, se declaran `prior=None` y se construyen dentro de la función. Es un error frecuente incluso en bibliotecas publicadas.\n:::\n\n## [0.10]{.header-section-number} Aleatoriedad y distribuciones {#sec-prelim-distribuciones .unnumbered}\n\n**Generadores y semillas.** Todo número aleatorio de un computador es pseudoaleatorio: sale de una secuencia determinista que parte de una **semilla**. Fijar la semilla hace que una simulación sea reproducible, y en un libro eso no es opcional: las bandas del [capítulo 4](04-svar.qmd#sec-svar-bandas) y las posteriores del [capítulo 5](05-bvar.qmd#sec-bvar-gibbs) tienen que salir iguales cada vez que se compila. La forma moderna en NumPy es crear un generador propio, `rng = np.random.default_rng(semilla)`, y pedirle las extracciones: `rng.standard_normal(n)`, `rng.normal(media, desvío, n)`, `rng.integers(0, T, T)`, `rng.choice(x, n)`. Cada función de `macrobook` que simula recibe un argumento `seed` por esta razón. La interfaz antigua, `np.random.seed`, fija un estado global compartido por todo el programa y conviene evitarla [@harris2020].\n\n**`scipy.stats`** [@virtanen2020] reúne las distribuciones con una interfaz común: se construye la distribución con sus parámetros y se le piden la densidad (`pdf`), la función de distribución (`cdf`), los cuantiles (`ppf`), la media o extracciones (`rvs`).\n\n**Normal multivariada.** Un vector $x$ de dimensión $n$ con media $\\mu$ y covarianza $\\Sigma$ tiene densidad\n\n$$ p(x) = (2\\pi)^{-n/2}\\, |\\Sigma|^{-1/2} \\exp\\!\\Big(-\\tfrac{1}{2}(x - \\mu)'\\Sigma^{-1}(x - \\mu)\\Big) . $$\n\nEs el supuesto sobre los errores de todos los VAR del libro, y la verosimilitud de un VAR es la suma de los logaritmos de esta densidad sobre las observaciones. Se simula con Cholesky, como en la [sección 0.5](#sec-prelim-factorizaciones), o con `rng.multivariate_normal(mu, Sigma)`. Toda combinación lineal de una normal multivariada es normal, y sus marginales y condicionales también lo son: esa propiedad es la que hace manejable al filtro de Kalman del [capítulo 7](07-state-space.qmd).\n\n**Gamma e inversa-gamma.** La gamma, $x \\sim \\text{Gamma}(a, \\theta)$ con forma $a$ y escala $\\theta$, vive en los positivos y tiene media $a\\theta$. Si $x$ es gamma con forma $a$ y **tasa** $b$ (escala $1/b$), su inversa $1/x$ es **inversa-gamma** con forma $a$ y escala $b$, $\\mathcal{IG}(a, b)$, con media $b/(a-1)$ para $a > 1$. La inversa-gamma es el prior conjugado de una varianza en un modelo normal: con un prior $\\mathcal{IG}$ para $\\sigma^2$, la posterior también lo es, y por eso aparece en la [sección 0.12](#sec-prelim-bayes) y en los modelos de espacio de estados y volatilidad de los capítulos 7 a 9.\n\n**Beta.** La beta, $x \\sim \\text{Beta}(a, b)$, vive en el intervalo $(0, 1)$, con media $a/(a+b)$. Es el prior natural para un parámetro acotado, como la persistencia de un componente cíclico o una probabilidad de transición entre regímenes. Una $\\text{Beta}(8, 2)$ tiene media 0.8 y desvío 0.12: dice \"persistente, pero no tanto como una raíz unitaria\".\n\n**Wishart e inversa-Wishart.** Son las distribuciones de matrices de covarianza. Una matriz $\\Sigma$ de $n \\times n$ es inversa-Wishart, $\\Sigma \\sim \\mathcal{IW}(S, \\nu)$, con escala $S$ y $\\nu$ grados de libertad, si $\\Sigma^{-1}$ es Wishart con escala $S^{-1}$ y los mismos grados de libertad. Su media es $S/(\\nu - n - 1)$ para $\\nu > n + 1$. Es el prior conjugado de la covarianza de un VAR, el que usa el [capítulo 5](05-bvar.qmd#sec-bvar-gibbs), y con $n = 1$ se reduce a la inversa-gamma: $\\mathcal{IW}(s, \\nu) = \\mathcal{IG}(\\nu/2,\\ s/2)$. Los grados de libertad controlan cuán informativo es el prior: con $\\nu$ pequeño, casi cualquier correlación entre las variables es plausible.\n\n| Distribución | Notación del libro | `scipy.stats` | Media |\n|:--------------|:-----------|:-----------------------------|:---------|\n| Normal multivariada | $N(\\mu, \\Sigma)$ | `multivariate_normal(m, S)` | $\\mu$ |\n| Gamma | $\\text{Gamma}(a, \\theta)$ | `gamma(a, scale=theta)` | $a\\theta$ |\n| Inversa-gamma | $\\mathcal{IG}(a, b)$ | `invgamma(a, scale=b)` | $b/(a-1)$ |\n| Beta | $\\text{Beta}(a, b)$ | `beta(a, b)` | $a/(a+b)$ |\n| Inversa-Wishart | $\\mathcal{IW}(S, \\nu)$ | `invwishart(df=nu, scale=S)` | $S/(\\nu-n-1)$ |\n\n: Distribuciones del libro, su parametrización y su equivalente en `scipy.stats`\n\n::: {#prelim-distribuciones .cell execution_count=21}\n``` {.python .cell-code}\nfrom scipy import stats\n\nnu, s = 10, 8.0\niw = stats.invwishart(df=nu, scale=s)       # 1 x 1\nig = stats.invgamma(nu / 2, scale=s / 2)\nprint(f\"media IW(8, 10): {iw.mean():.3f}   \"\n      f\"media IG(5, 4): {ig.mean():.3f}   \"\n      f\"s/(nu-2): {s / (nu - 2):.3f}\")\n\nS0, nu0 = np.array([[1.0, 0.3], [0.3, 0.5]]), 6\nprint(\"media IW 2x2:\\n\", np.round(\n    stats.invwishart(df=nu0, scale=S0).mean(), 3))\nprint(\"S0/(nu0-n-1):\\n\", np.round(S0 / (nu0 - 3), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nmedia IW(8, 10): 1.000   media IG(5, 4): 1.000   s/(nu-2): 1.000\nmedia IW 2x2:\n [[0.333 0.1  ]\n [0.1   0.167]]\nS0/(nu0-n-1):\n [[0.333 0.1  ]\n [0.1   0.167]]\n```\n:::\n:::\n\n\n::: {.cell execution_count=22}\n``` {.python .cell-code}\nrng = np.random.default_rng(6)\ngrid = np.linspace(0.01, 4, 400)\ndraws_iw = iw.rvs(size=20_000, random_state=rng)\n\nsize = figsize(0.34)\nfig, axes = plt.subplots(1, 3, figsize=size)\naxes[0].hist(draws_iw, bins=80, range=(0, 4), density=True,\n             color=PALETTE[\"steel\"], alpha=0.5, lw=0)\naxes[0].plot(grid, ig.pdf(grid), color=PALETTE[\"ink\"], lw=1.2)\naxes[0].set_title(\"IW 1×1 = gamma inversa\", fontsize=8.5)\n\nx = np.linspace(0.001, 0.999, 400)\nfor (a, b), style in zip([(2, 2), (8, 2), (0.5, 0.5)],\n                         PALETTE[\"shock_linestyle\"]):\n    axes[1].plot(x, stats.beta(a, b).pdf(x), ls=style, lw=1.2,\n                 color=PALETTE[\"ink\"], label=f\"Beta({a}, {b})\")\naxes[1].set_ylim(0, 4.5)\naxes[1].set_title(\"beta\", fontsize=8.5)\naxes[1].legend(fontsize=7, frameon=False)\n\npairs = [(3, PALETTE[\"muted\"]), (20, PALETTE[\"accent\"])]\nfor df, color in pairs:\n    W = stats.invwishart(df=df, scale=np.eye(2)).rvs(\n        size=20_000, random_state=rng)\n    rho = W[:, 0, 1] / np.sqrt(W[:, 0, 0] * W[:, 1, 1])\n    axes[2].hist(rho, bins=60, range=(-1, 1), density=True,\n                 color=color, alpha=0.5, lw=0,\n                 label=f\"ν = {df}\")\naxes[2].set_title(\"correlación en IW 2×2\", fontsize=8.5)\naxes[2].legend(fontsize=7, frameon=False)\nfor ax in axes:\n    ax.set_yticks([])\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Tres distribuciones del libro. Izquierda: extracciones de una inversa-Wishart de $1 \\times 1$ y la densidad de la inversa-gamma equivalente, que coinciden. Centro: tres betas con parámetros distintos. Derecha: correlación implícita en una inversa-Wishart de $2 \\times 2$ con escala identidad; con pocos grados de libertad casi cualquier correlación es plausible.](00-preliminares_files/figure-pdf/fig-prelim-distribuciones-output-1.pdf){#fig-prelim-distribuciones fig-pos='H'}\n:::\n:::\n\n\n::: {.cuidado}\nCada libro y cada programa parametriza estas distribuciones a su manera: forma y escala o forma y tasa en la gamma, $S$ o $S^{-1}$ en la inversa-Wishart, $\\nu$ o $\\nu/2$ en la inversa-gamma. Un prior escrito en una convención y muestreado en otra da resultados plausibles y equivocados. La defensa es mecánica: antes de usar un muestreador, comparar la media de las extracciones con la fórmula de la tabla, como en la celda de arriba.\n:::\n\nEl apéndice A de [*Bayesian Data Analysis*](https://sites.stat.columbia.edu/gelman/book/) [@gelman2013], gratuito en línea, reúne las densidades, medias y varianzas de todas estas distribuciones con una parametrización única, y el manual de @blake2017 muestra cómo aparecen en los muestreadores de los modelos macroeconómicos.\n\n## [0.11]{.header-section-number} Simulación: Monte Carlo y bootstrap {#sec-prelim-simulacion .unnumbered}\n\n**Monte Carlo.** Si se pueden extraer valores $x_1, \\ldots, x_M$ de una distribución, cualquier esperanza se aproxima por un promedio,\n\n$$ \\mathbb{E}[g(x)] \\approx \\frac{1}{M}\\sum_{m=1}^{M} g(x_m), \\qquad \\text{con error estándar } \\frac{\\operatorname{sd}(g(x))}{\\sqrt{M}} . $$\n\nLa ley de los grandes números garantiza la convergencia, y el error se achica con $\\sqrt{M}$: para ganar un decimal de precisión hacen falta cien veces más extracciones. Lo mismo vale para cuantiles, probabilidades y cualquier otra característica de la distribución, que es lo que hacen la [densidad predictiva](05-bvar.qmd#sec-bvar-pronostico) y las bandas de todo el libro.\n\nEl ejemplo elegido conecta con el [capítulo 1](01-macro-data.qmd#sec-datos-transformaciones). Si $z \\sim N(0, 1)$ es el logaritmo de una variable, la variable es $e^{z}$, y su media no es $e^{\\mathbb{E}[z]} = 1$ sino $e^{1/2} \\approx 1.649$. Revertir un logaritmo tomando la exponencial de la media devuelve la mediana, no la media.\n\n::: {.cell execution_count=23}\n``` {.python .cell-code}\ndef mc_means(m, reps, rng, batch=50):\n    \"\"\"reps Monte Carlo estimates of E[exp(z)], m draws each.\"\"\"\n    out = [np.exp(rng.standard_normal((batch, m))).mean(axis=1)\n           for _ in range(reps // batch)]\n    return np.concatenate(out)\n\n\nrng = np.random.default_rng(7)\nsizes = np.unique(np.logspace(1, 5, 17).astype(int))\nq = np.array([np.quantile(mc_means(m, 400, rng),\n                          [0.025, 0.5, 0.975]) for m in sizes])\nexact = np.exp(0.5)\nsd_g = np.sqrt(np.exp(2) - np.exp(1))     # sd of exp(z)\n\nsize = figsize(0.40)\nfig, ax = plt.subplots(figsize=size)\nax.fill_between(sizes, q[:, 0], q[:, 2], lw=0,\n                color=PALETTE[\"bands\"][1], alpha=0.7)\nax.plot(sizes, q[:, 1], color=PALETTE[\"ink\"], lw=1.2)\nfor k in (-2, 0, 2):\n    ax.plot(sizes, exact + k * sd_g / np.sqrt(sizes),\n            color=PALETTE[\"accent\"], lw=1.0, ls=(0, (4, 2)))\nax.axhline(1.0, color=PALETTE[\"muted\"], lw=0.8)\nax.set_xscale(\"log\")\nax.set_ylim(0.4, 3.0)\nax.set_xlabel(\"extracciones, M (escala logarítmica)\")\nplt.show()\n\nfor m in (10, 100, 100_000):\n    row = q[list(sizes).index(m)]\n    print(f\"M = {m:>7,}: mediana {row[1]:.3f}, \"\n          f\"95 % entre {row[0]:.3f} y {row[2]:.3f}\")\n```\n\n::: {.cell-output .cell-output-display}\n![Distribución de la estimación de Monte Carlo de $\\mathbb{E}[e^{z}]$, con $z \\sim N(0, 1)$, según el número de extracciones $M$: mediana (línea) y rango entre los percentiles 2.5 y 97.5 (banda) en 400 repeticiones. Las líneas punteadas son el valor exacto, $e^{1/2}$, y la aproximación normal de más y menos dos errores estándar; la línea gris es $e^{\\mathbb{E}[z]} = 1$.](00-preliminares_files/figure-pdf/fig-prelim-montecarlo-output-1.pdf){#fig-prelim-montecarlo fig-pos='H'}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nM =      10: mediana 1.506, 95 % entre 0.719 y 3.131\nM =     100: mediana 1.649, 95 % entre 1.284 y 2.111\nM = 100,000: mediana 1.649, 95 % entre 1.635 y 1.662\n```\n:::\n:::\n\n\nCon diez extracciones la estimación típica queda por debajo del valor exacto y su rango es muy asimétrico, de 0.72 a 3.13: los valores grandes de $e^{z}$, que son los que suben el promedio, son raros, y con pocas extracciones casi nunca aparecen. Con cien extracciones el rango ya excluye el uno, y con cien mil se reduce a más o menos 0.013 alrededor de $e^{1/2}$. Lo mismo vale, con más fuerza, para los cuantiles extremos que definen las bandas al 95 %: la varianza de un cuantil estimado crece donde la densidad es baja, de modo que las colas de una posterior piden muchas más extracciones que su media.\n\n**Bootstrap.** Monte Carlo resuelve el problema cuando se conoce la distribución de la que se extrae. El bootstrap [@efron1993] lo resuelve cuando no se conoce: la distribución muestral de un estimador se aproxima reestimándolo sobre muestras artificiales generadas a partir de los propios datos. Con observaciones independientes basta remuestrear con reemplazo. Con series de tiempo eso destruiría la dependencia, así que se remuestrean los **residuos** y se reconstruye la serie **iterando el modelo estimado**, que es el [algoritmo del capítulo 4](04-svar.qmd#sec-svar-bandas) en su versión escalar.\n\nEl ejemplo usa una muestra corta y persistente, $T = 80$ y $\\phi = 0.9$, porque es el caso en que el bootstrap más aporta: el estimador de mínimos cuadrados de $\\phi$ está sesgado hacia abajo en muestras pequeñas, en aproximadamente $-(1 + 3\\phi)/T$ [@kilian1998], y el bootstrap permite estimar ese sesgo.\n\n::: {#prelim-bootstrap .cell execution_count=24}\n``` {.python .cell-code}\ndef ols_ar1(y):\n    \"\"\"OLS of y_t on (1, y_{t-1}): ((c, phi), residuals).\"\"\"\n    X = np.column_stack([np.ones(len(y) - 1), y[:-1]])\n    b = np.linalg.solve(X.T @ X, X.T @ y[1:])\n    return b, y[1:] - X @ b\n\n\ny_short = simulate_ar1(0.5, 0.9, 1.0, T=80, seed=6)\nb_hat, e_hat = ols_ar1(y_short)\n\nrng = np.random.default_rng(8)\nphi_star = np.empty(2000)\nfor r in range(len(phi_star)):\n    e_star = rng.choice(e_hat, size=len(e_hat), replace=True)\n    y_star = np.empty_like(y_short)\n    y_star[0] = y_short[0]\n    for t in range(1, len(y_short)):     # iterate the model\n        y_star[t] = (b_hat[0] + b_hat[1] * y_star[t - 1]\n                     + e_star[t - 1])\n    phi_star[r] = ols_ar1(y_star)[0][1]\n\nbias = phi_star.mean() - b_hat[1]\nlo, hi = np.quantile(phi_star, [0.025, 0.975])\nprint(f\"phi estimado:        {b_hat[1]:.3f}\")\nprint(f\"sesgo bootstrap:    {bias:+.3f}\")\nprint(f\"phi corregido:       {b_hat[1] - bias:.3f}\")\nprint(f\"intervalo al 95 %:  [{lo:.3f}, {hi:.3f}]\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nphi estimado:        0.863\nsesgo bootstrap:    -0.047\nphi corregido:       0.910\nintervalo al 95 %:  [0.655, 0.924]\n```\n:::\n:::\n\n\n::: {#prelim-sesgo-mc .cell execution_count=25}\n``` {.python .cell-code}\n# The true bias, by Monte Carlo: possible only because here\n# the data-generating process is known.\nphi_mc = np.array([ols_ar1(simulate_ar1(0.5, 0.9, 1.0, 80,\n                                        seed=100 + i))[0][1]\n                   for i in range(3000)])\ntrue_bias = phi_mc.mean() - 0.9\napprox = -(1 + 3 * 0.9) / 80\nprint(f\"sesgo verdadero (Monte Carlo): {true_bias:+.3f}\")\nprint(f\"aproximación -(1+3 phi)/T:     {approx:+.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nsesgo verdadero (Monte Carlo): -0.055\naproximación -(1+3 phi)/T:     -0.046\n```\n:::\n:::\n\n\n::: {.cell execution_count=26}\n``` {.python .cell-code}\nsize = figsize(0.40)\nfig, ax = plt.subplots(figsize=size)\nax.hist(phi_star, bins=60, density=True, lw=0,\n        color=PALETTE[\"steel\"], alpha=0.55)\nax.axvline(b_hat[1], color=PALETTE[\"ink\"], lw=1.2)\nax.axvline(0.9, color=PALETTE[\"accent\"], lw=1.2,\n           ls=(0, (4, 2)))\nax.set_yticks([])\nax.set_xlabel(\"φ\")\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Distribución bootstrap de $\\hat{\\phi}$ en un AR(1) con $T = 80$. La línea continua es la estimación sobre la muestra y la punteada, el valor verdadero con que se simuló. La distribución está desplazada hacia la izquierda de la estimación: ese desplazamiento es la estimación bootstrap del sesgo.](00-preliminares_files/figure-pdf/fig-prelim-bootstrap-output-1.pdf){#fig-prelim-bootstrap fig-pos='H'}\n:::\n:::\n\n\nEl bootstrap estima un sesgo de $-0.047$ y el verdadero, calculado por Monte Carlo con 3000 muestras del proceso conocido, es de $-0.055$. La aproximación analítica da $-0.046$. Corregir la estimación por el sesgo bootstrap la acerca al valor verdadero, y esa es la idea del bootstrap con corrección de sesgo de @kilian1998, el estándar para las bandas de los VAR estructurales.\n\n::: {.cuidado}\nEl bootstrap tiene que reproducir la estructura de dependencia de los datos. Remuestrear observaciones de una serie de tiempo, o sumar residuos remuestreados a los valores ajustados sin iterar el modelo, produce muestras artificiales con otra dinámica y bandas que no significan nada. Cerca de una raíz unitaria el bootstrap también falla, porque la distribución del estimador cambia de forma de manera discontinua justo en $\\phi = 1$.\n:::\n\n## [0.12]{.header-section-number} Bayes y el muestreo de Gibbs {#sec-prelim-bayes .unnumbered}\n\nEl teorema de Bayes combina lo que se sabía antes de ver los datos, el **prior**, con lo que dicen los datos, la **verosimilitud**:\n\n$$ p(\\theta \\mid y) \\propto p(y \\mid \\theta)\\, p(\\theta) . $$\n\nEl [capítulo 5](05-bvar.qmd#sec-bvar-bayes) muestra el caso más simple, un parámetro con prior normal, en el que la media posterior es un promedio de la del prior y la del dato ponderado por sus precisiones. Aquí el objetivo es el paso siguiente: estimar el AR(1) con **todos** sus parámetros desconocidos, $\\beta = (c, \\phi)'$ y $\\sigma^2$.\n\nLa posterior conjunta de $(\\beta, \\sigma^2)$ no tiene una forma conocida, pero las dos condicionales sí. Con un prior normal $\\beta \\sim N(\\beta_0, V_0)$ y uno inversa-gamma $\\sigma^2 \\sim \\mathcal{IG}(a_0, d_0)$,\n\n$$ \\beta \\mid \\sigma^2, y \\sim N(\\bar{\\beta}, \\bar{V}), \\qquad \\bar{V} = \\big(V_0^{-1} + \\sigma^{-2} X'X\\big)^{-1}, \\qquad \\bar{\\beta} = \\bar{V}\\big(V_0^{-1}\\beta_0 + \\sigma^{-2} X'Y\\big), $$\n\n$$ \\sigma^2 \\mid \\beta, y \\sim \\mathcal{IG}\\Big(a_0 + \\tfrac{T-1}{2},\\ d_0 + \\tfrac{1}{2}(Y - X\\beta)'(Y - X\\beta)\\Big). $$\n\nEl **muestreador de Gibbs** alterna entre las dos: extrae $\\beta$ dada la última $\\sigma^2$, extrae $\\sigma^2$ dado el último $\\beta$, y repite. Después de un periodo inicial que se descarta, las extracciones se distribuyen según la posterior conjunta. Estas son exactamente las dos etapas del [algoritmo del capítulo 5](05-bvar.qmd#sec-bvar-gibbs) con una sola variable: $\\Sigma^{-1} \\otimes X'X$ se vuelve $\\sigma^{-2}X'X$ y la inversa-Wishart se vuelve una inversa-gamma.\n\nEl prior para $\\phi$ se centra en uno con desvío 0.2, que es la idea del prior de Minnesota del [capítulo 5](05-bvar.qmd#sec-bvar-minnesota): a falta de evidencia en contra, una serie macroeconómica se parece a una caminata aleatoria. El de la constante es difuso.\n\n::: {#prelim-gibbs .cell execution_count=27}\n``` {.python .cell-code}\nX = np.column_stack([np.ones(len(y_short) - 1), y_short[:-1]])\nY = y_short[1:]\nbeta0 = np.array([0.0, 1.0])\nV0_inv = np.diag([1 / 10.0, 1 / 0.2**2])\na0, d0 = 2.0, 1.0\n\nrng = np.random.default_rng(9)\nsigma2, keep = 1.0, []\nfor step in range(6000):\n    V = np.linalg.inv(V0_inv + X.T @ X / sigma2)\n    mean = V @ (V0_inv @ beta0 + X.T @ Y / sigma2)\n    beta = rng.multivariate_normal(mean, V)\n    e = Y - X @ beta\n    sigma2 = stats.invgamma.rvs(a0 + len(Y) / 2,\n                                scale=d0 + e @ e / 2,\n                                random_state=rng)\n    keep.append([beta[0], beta[1], sigma2])\n\ndraws = np.array(keep)[1000:]            # discard burn-in\nphi_draws = draws[:, 1]\nprint(f\"media posterior de phi: {phi_draws.mean():.3f} \"\n      f\"(MCO {b_hat[1]:.3f})\")\nprint(\"intervalo al 68 %:\",\n      np.round(np.quantile(phi_draws, [0.16, 0.84]), 3))\nprint(\"intervalo al 95 %:\",\n      np.round(np.quantile(phi_draws, [0.025, 0.975]), 3))\nprint(f\"P(phi >= 1 | y) = {(phi_draws >= 1).mean():.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nmedia posterior de phi: 0.877 (MCO 0.863)\nintervalo al 68 %: [0.816 0.937]\nintervalo al 95 %: [0.761 0.995]\nP(phi >= 1 | y) = 0.022\n```\n:::\n:::\n\n\n::: {.cell execution_count=28}\n``` {.python .cell-code}\nall_phi = np.array(keep)[:, 1]\ngrid = np.linspace(0.4, 1.4, 300)\n\nsize = figsize(0.38)\nfig, axes = plt.subplots(1, 2, figsize=size)\ncharts.trace(axes[0], all_phi, burn=1000)\naxes[0].set_title(\"cadena de φ\", fontsize=8.5)\naxes[0].set_xlabel(\"iteración\")\nprior_pdf = stats.norm(1, 0.2).pdf(grid)\ncharts.prior_posterior(axes[1], phi_draws,\n                       prior_density=prior_pdf,\n                       grid=grid, ols_value=b_hat[1])\naxes[1].set_xlim(0.4, 1.4)\naxes[1].set_yticks([])\naxes[1].set_title(\"posterior de φ\", fontsize=8.5)\ncharts.legend_outside(axes[1], ncol=3)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Muestreador de Gibbs del AR(1). Izquierda: la cadena de $\\phi$, con el periodo inicial descartado sombreado. Derecha: la posterior de $\\phi$, la densidad del prior y la estimación de mínimos cuadrados.](00-preliminares_files/figure-pdf/fig-prelim-gibbs-output-1.pdf){#fig-prelim-gibbs fig-pos='H'}\n:::\n:::\n\n\nLa media posterior de $\\phi$, 0.877, queda entre el prior y la estimación de mínimos cuadrados, 0.863, mucho más cerca de esta porque 79 observaciones informan más que un prior con desvío 0.2. Y la posterior responde una pregunta que el estimador clásico no puede responder directamente: la probabilidad de que el proceso tenga una raíz unitaria o sea explosivo, $P(\\phi \\geq 1 \\mid y)$, que aquí es de 2 %. El [capítulo 5](05-bvar.qmd#sec-bvar-gibbs) descarta esas extracciones cuando necesita respuestas al impulso bien definidas; aquí se reportan, porque son información.\n\n::: {.intuicion}\nEl muestreador de Gibbs cambia un problema difícil, extraer de una distribución conjunta sin forma conocida, por una sucesión de problemas fáciles, extraer de cada condicional sabiendo el resto. Funciona siempre que cada condicional se pueda muestrear, y esa es la razón por la que los priors conjugados, normal para los coeficientes e inversa-gamma o inversa-Wishart para las varianzas, dominan la macroeconometría bayesiana aplicada.\n:::\n\nEl [repaso bayesiano](../appendices/b-bayes.qmd) del apéndice B trata lo que queda fuera de este capítulo: el algoritmo de Metropolis-Hastings, el diagnóstico de convergencia de las cadenas y la elección de los priors.\n\n## [0.13]{.header-section-number} Otros temas {#sec-prelim-otros .unnumbered}\n\n### Optimización y máxima verosimilitud\n\nCuando la posterior no se puede muestrear o el modelo se estima por máxima verosimilitud, como los de espacio de estados del [capítulo 7](07-state-space.qmd), hace falta optimizar. `scipy.optimize.minimize` minimiza cualquier función de un vector de parámetros; se le pasa el **negativo** de la log-verosimilitud y un valor inicial. Tres prácticas evitan la mayoría de los problemas: reparametrizar para que los parámetros no tengan restricciones (el logaritmo de una varianza, en lugar de la varianza), partir de valores iniciales razonables y probar varios puntos de partida.\n\n### Álgebra numérica\n\nLas fórmulas del libro están escritas con inversas porque así se leen mejor, pero el código no siempre debe calcularlas: `solve` y la factorización de Cholesky son más estables. Una matriz que en teoría es simétrica sale del computador con asimetrías del orden de $10^{-16}$, suficientes para que algunas funciones la rechacen; por eso el [muestreador del capítulo 5](05-bvar.qmd#sec-bvar-gibbs) simetriza la covarianza con `(V + V.T) / 2` antes de extraer. Y `np.linalg.cholesky` es la forma más barata de verificar que una matriz es definida positiva: falla si no lo es.\n\n### Rendimiento\n\nLa primera regla es vectorizar. La segunda, medir antes de optimizar: casi siempre el tiempo se va en un solo bucle. Cuando ese bucle no se puede vectorizar, como en una recursión o en un muestreador, [Numba](https://numba.pydata.org/) lo compila con un decorador y sin reescribir el código.\n\n### Control de versiones y reproducibilidad\n\nUn proyecto empírico reproducible tiene tres piezas: el código bajo control de versiones con [git](https://git-scm.com/book/es/v2), un entorno fijado (en este libro, `pyproject.toml` y `uv.lock`) y los datos crudos separados de los construidos, con un script que va de unos a otros. La guía de @gentzkow2014 sigue siendo la mejor introducción breve a por qué importa y cómo se organiza.\n\n## Ideas clave {.unnumbered}\n\n::: {.ideas-clave}\n1. El AR(1) es un VAR de una variable: quien lo simula, lo estima, estudia su estabilidad y lo remuestrea con las herramientas de este capítulo ya tiene las piezas de los VAR.\n2. En NumPy, `@` es el producto matricial y `*` el producto elemento a elemento; los sistemas se resuelven con `solve`, y $\\operatorname{vec}$ se escribe con `order=\"F\"`.\n3. Los autovalores deciden la estabilidad y la forma de las respuestas: módulo menor que uno para que decaigan, parte imaginaria para que oscilen.\n4. La factorización de Cholesky simula normales correlacionadas y es la identificación recursiva; que $LQ$ sirva igual que $L$ es el problema de identificación.\n5. Monte Carlo aproxima esperanzas con promedios, el bootstrap aproxima distribuciones muestrales reestimando sobre muestras que respetan la dinámica, y el muestreo de Gibbs aproxima posteriores alternando entre condicionales conocidas.\n:::\n\n## Lecturas recomendadas {.unnumbered}\n\n::: {.lecturas}\n[QuantEcon](https://quantecon.org/lectures/)\n:   las lecciones de Sargent y Stachurski, en particular [*Python Programming for Economics and Finance*](https://python-programming.quantecon.org/intro.html) para el lenguaje y la [lección de álgebra lineal](https://python.quantecon.org/linear_algebra.html) para el repaso matemático.\n\nMcKinney (2022)\n:   [*Python for Data Analysis*](https://wesmckinney.com/book/), la referencia de pandas escrita por su creador; gratuito en línea.\n\nTurrell\n:   [*Coding for Economists*](https://aeturrell.github.io/coding-for-economists/), un manual de Python para economistas que cubre desde el entorno hasta la regresión y las series de tiempo.\n\nStrang (2016)\n:   el texto de álgebra lineal más claro que existe, acompañado de las [lecciones grabadas del curso 18.06](https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/).\n\nLütkepohl (2005), apéndice A\n:   todos los resultados de álgebra matricial que usan los VAR, con $\\operatorname{vec}$ y Kronecker incluidos.\n\nGelman et al. (2013)\n:   [*Bayesian Data Analysis*](https://sites.stat.columbia.edu/gelman/book/), gratuito en línea; su apéndice A es el catálogo de distribuciones de referencia.\n\nEfron y Tibshirani (1993)\n:   la introducción clásica al bootstrap, escrita por su inventor.\n:::\n\n## Ejercicios {.unnumbered}\n\n1. Modifique `simulate_ar1` para que acepte un valor inicial arbitrario y simule 1000 trayectorias de 200 periodos con $\\phi = 1$ y $c = 0$. Verifique que la varianza entre trayectorias crece linealmente con $t$, como corresponde a una caminata aleatoria, y compárela con el caso $\\phi = 0.8$.\n\n   ::: {.solucion}\n   Con $\\phi = 1$, $y_t = y_0 + \\sum_{s=1}^{t} \\varepsilon_s$, de modo que $\\operatorname{Var}(y_t) = t\\sigma^2$: la varianza entre trayectorias en el periodo $t$ debe estar cerca de $t$. Con $\\phi = 0.8$ la varianza es $(1 - 0.64^{t})/(1 - 0.64)$, que llega al 99 % de su límite, 2.78, en diez periodos y deja de crecer. Basta apilar las trayectorias en una matriz de $1000 \\times 200$ y calcular `paths.var(axis=0)`.\n   :::\n\n2. Para la matriz con autovalores complejos de la [sección 0.4](#sec-prelim-autovalores), obtenga con `np.linalg.eig` los autovalores y autovectores, verifique que $A^{10} = V\\Lambda^{10}V^{-1}$ y calcule el periodo de la oscilación.\n\n   ::: {.solucion}\n   ```python\n   lam, V = np.linalg.eig(A)\n   A10 = V @ np.diag(lam**10) @ np.linalg.inv(V)\n   np.allclose(A10.real, np.linalg.matrix_power(A, 10))\n   ```\n\n   La reconstrucción coincide con la potencia directa; la parte imaginaria de `A10` es del orden de $10^{-17}$, puro error de redondeo, y se descarta con `.real`. El ángulo de los autovalores, `np.angle(lam[0])`, es de 0.39 radianes, de modo que el periodo es $2\\pi/0.39 \\approx 16$ periodos.\n   :::\n\n3. Escriba la función inversa de `vec`, que reciba un vector y el número de filas y devuelva la matriz. Úsela para verificar que $\\operatorname{vec}(XB) = (I_n \\otimes X)\\operatorname{vec}(B)$ con $X$ de $50 \\times 5$ y $B$ de $5 \\times 3$.\n\n   ::: {.solucion}\n   `def unvec(v, rows): return v.reshape((rows, -1), order=\"F\")`. La verificación es `np.allclose(vec(X @ B), np.kron(np.eye(3), X) @ vec(B))`. Si se olvida `order=\"F\"` en cualquiera de los dos lados, la comparación falla aunque las formas coincidan.\n   :::\n\n4. Con el IPC peruano, calcule la inflación trimestral anualizada a partir de los promedios trimestrales del índice, $400\\,\\Delta \\ln \\bar{P}_q$, y compárela gráficamente con la inflación interanual del último mes de cada trimestre. ¿Cuál reacciona antes a los cambios de tendencia de 2021 y 2023?\n\n   ::: {.solucion}\n   `cpi_q = cpi.resample(\"Q\").mean()` y `400 * np.log(cpi_q).diff()`. La tasa trimestral anualizada sube y baja antes que la interanual, porque compara contra el trimestre anterior y no promedia los últimos doce meses; a cambio, es más ruidosa y conserva algo de estacionalidad, que habría que remover con los métodos del [capítulo 1](01-macro-data.qmd#sec-datos-desestacionalizar).\n   :::\n\n5. Estime por Monte Carlo el sesgo del estimador de mínimos cuadrados de $\\phi$ con $\\phi = 0.9$ y $T \\in \\{50, 100, 200, 400\\}$, y compárelo con la aproximación $-(1+3\\phi)/T$. ¿Qué implica el resultado para los VAR trimestrales estimados con veinte años de datos?\n\n   ::: {.solucion}\n   El sesgo se reduce aproximadamente a la mitad cada vez que $T$ se duplica, y la aproximación es buena salvo en la muestra más corta. Veinte años de datos trimestrales son 80 observaciones: el sesgo en la persistencia es del orden de cinco centésimas, suficiente para que las respuestas al impulso estimadas decaigan más rápido que las verdaderas. Es una de las razones para el bootstrap con corrección de sesgo y para el prior de Minnesota, que empuja la persistencia hacia arriba.\n   :::\n\n6. Repita el muestreador de Gibbs con un prior para $\\phi$ centrado en cero con desvío 0.5. Compare la media posterior con la de la [sección 0.12](#sec-prelim-bayes) y relacione la diferencia con el papel de $\\delta_i$ y $\\lambda_1$ en el prior de Minnesota.\n\n   ::: {.solucion}\n   Con el prior centrado en cero la media posterior de $\\phi$ baja por debajo de la estimación de mínimos cuadrados, porque el prior empuja hacia la ausencia de persistencia; con el prior centrado en uno sube por encima. La media del prior es el papel de $\\delta_i$, que fija hacia qué valor se encoge el primer rezago propio, y el desvío es el de $\\lambda_1$, que fija con cuánta fuerza. Con 79 observaciones la diferencia es de unas pocas centésimas; con 30 sería mucho mayor.\n   :::\n\n",
    "supporting": [
      "00-preliminares_files/figure-pdf"
    ],
    "filters": []
  }
}