{
  "text-color": "#2A231D",
  "background-color": null,
  "line-number-color": "#BFB3A6",
  "line-number-background-color": null,
  "text-styles": {
    "Alert": {
      "text-color": "#8E3620",
      "background-color": null,
      "bold": true,
      "italic": false,
      "underline": false
    },
    "Annotation": {
      "text-color": "#8A7F72",
      "background-color": null,
      "bold": false,
      "italic": true,
      "underline": false
    },
    "Attribute": {
      "text-color": "#2A231D",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "BaseN": {
      "text-color": "#8E3620",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Char": {
      "text-color": "#4E6E38",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Comment": {
      "text-color": "#8A7F72",
      "background-color": null,
      "bold": false,
      "italic": true,
      "underline": false
    },
    "CommentVar": {
      "text-color": "#8A7F72",
      "background-color": null,
      "bold": false,
      "italic": true,
      "underline": false
    },
    "Constant": {
      "text-color": "#7E6325",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "ControlFlow": {
      "text-color": "#3D647F",
      "background-color": null,
      "bold": true,
      "italic": false,
      "underline": false
    },
    "DataType": {
      "text-color": "#7E6325",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "DecVal": {
      "text-color": "#8E3620",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Documentation": {
      "text-color": "#8A7F72",
      "background-color": null,
      "bold": false,
      "italic": true,
      "underline": false
    },
    "Error": {
      "text-color": "#8E3620",
      "background-color": null,
      "bold": true,
      "italic": false,
      "underline": false
    },
    "Extension": {
      "text-color": "#7E6325",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Float": {
      "text-color": "#8E3620",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Function": {
      "text-color": "#2A231D",
      "background-color": null,
      "bold": true,
      "italic": false,
      "underline": false
    },
    "Import": {
      "text-color": "#3D647F",
      "background-color": null,
      "bold": true,
      "italic": false,
      "underline": false
    },
    "Information": {
      "text-color": "#8A7F72",
      "background-color": null,
      "bold": false,
      "italic": true,
      "underline": false
    },
    "Keyword": {
      "text-color": "#3D647F",
      "background-color": null,
      "bold": true,
      "italic": false,
      "underline": false
    },
    "Operator": {
      "text-color": "#6B5F52",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Other": {
      "text-color": "#7E6325",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Preprocessor": {
      "text-color": "#8A7F72",
      "background-color": null,
      "bold": false,
      "italic": true,
      "underline": false
    },
    "SpecialChar": {
      "text-color": "#7E6325",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "SpecialString": {
      "text-color": "#4E6E38",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "String": {
      "text-color": "#4E6E38",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Variable": {
      "text-color": "#2A231D",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "VerbatimString": {
      "text-color": "#4E6E38",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Warning": {
      "text-color": "#8E3620",
      "background-color": null,
      "bold": true,
      "italic": false,
      "underline": false
    }
  }
}